dydxprotocol/v4-chain

indexer/packages/postgres/src/types/websocket-message-types.ts
indexer/services/comlink/public/websocket-documentation.md
indexer/services/ender/__tests__/helpers/kafka-helper.test.ts
indexer/services/ender/src/helpers/kafka-helper.ts

context: https://dydx-team.slack.com/archives/C03S57F735K/p1693706039413799

Update price to oraclePrice for clarity

---

protocol/testing/genesis.sh
protocol/testing/testnet-dev/dev.sh
protocol/testing/testnet-local/local.sh
protocol/testing/testnet-staging/staging.sh

for testing in local, dev, and staging envs, reduced delay to
- 30 blocks in localnet
- 600 blocks in dev and staging

[CORE-550] reduce complete bridge delay in non-prod environments

---

indexer/services/comlink/public/api-documentation.md
indexer/services/comlink/public/swagger.json
indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
indexer/services/comlink/src/types.ts

Add a mock /screen endpoint that returns `true` if the input argument ends in between 'a' to 'm', and false otherwise for testing purposes.

[IND-372] Add mock /screen endpoint.

---

.github/labeler.yml
.github/workflows/labeler.yml

Adds a workflow to automatically label PRs.

[CORE-546] Add labeler workflow

---

protocol/app/app.go
protocol/daemons/pricefeed/client/client.go
protocol/daemons/pricefeed/client/handler/exchange_query_handler.go
protocol/daemons/server/types/bridge/bridge_event_manager.go
protocol/lib/time/time.go
protocol/lib/time/time_provider.go
protocol/lib/time/time_test.go
protocol/mocks/Makefile
protocol/x/bridge/types/genesis.go
protocol/x/prices/keeper/keeper.go

* Simply moving the file to a different package

[DEC-2104] move `time_provider.go` to `lib/time` package

---

protocol/x/prices/keeper/keeper.go
protocol/x/sending/keeper/keeper.go

Result of using `maps.ArrayToMapInterface()` function after it was removed

fix bad merge

---

indexer/packages/postgres/__tests__/helpers/constants.ts
indexer/packages/postgres/__tests__/stores/compliance-data-table.test.ts
indexer/packages/postgres/src/db/migrations/migration_files/20230912110846_create_compliance_data_table.ts
indexer/packages/postgres/src/helpers/db-helpers.ts
indexer/packages/postgres/src/models/compliance-data-model.ts
indexer/packages/postgres/src/stores/compliance-table.ts
indexer/packages/postgres/src/types/compliance-data-types.ts
indexer/packages/postgres/src/types/db-model-types.ts
indexer/packages/postgres/src/types/index.ts
indexer/packages/postgres/src/types/query-types.ts

From [spec](https://www.notion.so/dydx/OFAC-Checks-and-Geo-blocking-d4f749e8f4314fa1b258cd52033fb30d?d=16745ab83111473b84fc2c789c860f8c#ca39f11df37744cd9464881c95cd79c4).
Will not merge until spec is finalized.

[IND-373] Add compliance data table.

---

protocol/scripts/bridge_events.go

Adds a script that can be used to test bridge events and also help construct a `genesis.json` file if needed

add BridgeEvents script

---

protocol/lib/ante/app_injected_msg.go
protocol/lib/ante/internal_msg.go
protocol/lib/ante/nested_msg.go
protocol/lib/ante/unsupported_msgs.go

Just moving around the msgs and adding more comments

[DEC-2082] Refactor `lib/ante`

---

protocol/app/simulation_test.go

https://dydx-team.slack.com/archives/GTGEVSCUU/p1695156740555549

Simtest fix for daemon monitoring

---

protocol/daemons/pricefeed/client/constants/static_exchange_market_config.go
protocol/daemons/pricefeed/client/constants/static_exchange_market_config_test.go
protocol/daemons/pricefeed/client/constants/static_exchange_startup_config_test.go
protocol/daemons/pricefeed/client/constants/testdata/btc_exchange_config.json
protocol/daemons/pricefeed/client/constants/testdata/doge_exchange_config.json
protocol/daemons/pricefeed/client/constants/testdata/eth_exchange_config.json
protocol/daemons/pricefeed/client/constants/testdata/usdt_exchange_config.json
protocol/x/prices/client/testutil/binance.go

https://dydx-team.slack.com/archives/C05FTK5D8QG/p1695071430544969?thread_ts=1695067680.294969&cid=C05FTK5D8QG

[CORE-589] - Remove binanceUS from all markets.

---

protocol/app/module/slashing_test.go

Minor swap to JSONEq for comparison.

[DEC-2081] Audit app/module/slashing.go

---

protocol/app/msgs/all_msgs_test.go
protocol/app/msgs/app_injected_msgs_test.go
protocol/app/msgs/app_test.go
protocol/app/msgs/internal_msgs_test.go
protocol/app/msgs/nested_msgs_test.go
protocol/app/msgs/normal_msgs_test.go
protocol/app/msgs/unsupported_msgs_test.go

Minor changes:
* rename common test utility method
* add gov value test
* minor slices usage improvements

[DEC-2081] Audit app/msgs/**

---

protocol/app/ante/msg_type.go
protocol/app/ante/msg_type_test.go

* Minor changes:
* exit early in the loop
* swap to slices.Clone in the test

[DEC-2081] Audit app/ante/msg_type.go

---

protocol/x/delaymsg/keeper/msg_server.go
protocol/x/delaymsg/keeper/msg_server_test.go

[Slack thread](https://dydx-team.slack.com/archives/C05FTK5D8QG/p1695049275814479)

[DEC-2118] - Remove panics from DelayMessage

---

protocol/testing/genesis.sh

Referenced this [sheet](https://docs.google.com/spreadsheets/d/1QmuwS0LljTrZmkFiYMhUR9MfFa4jhgfzhgDC9z0v2LQ/edit#gid=1671431771).

Update CLOB / Perpetual params in genesis to match research defined values.

---

protocol/app/app.go
protocol/app/app_test.go
protocol/app/basic_manager/basic_manager.go
protocol/app/msgs/all_msgs.go
protocol/app/msgs/normal_msgs.go
protocol/app/msgs/normal_msgs_test.go
protocol/app/simulation_test.go
protocol/app/testdata/default_genesis_state.json
protocol/lib/ante/app_injected_msg_test.go
protocol/lib/ante/internal_msg_test.go
protocol/lib/ante/nested_msg_test.go
protocol/lib/ante/unsupported_msgs_test.go

* [Context](https://dydx-team.slack.com/archives/C03FY21CSF6/p1695325960116449)
* Compare with [PR that removed it](https://github.com/dydxprotocol/v4/pull/938/files#diff-0f1d2976054440336a576d47a44a37b80cdf6701dd9113012bce0e3c425819b7R890)

Re-enable evidence module

---

indexer/services/roundtable/src/config.ts
indexer/services/roundtable/src/index.ts

See [spec](https://www.notion.so/dydx/OFAC-Checks-and-Geo-blocking-d4f749e8f4314fa1b258cd52033fb30d?pvs=4#2fe4fcf8a39642fca90b21b25d3e6e48).

[IND-370] Run task to update compliance data.

---

protocol/daemons/pricefeed/client/types/price_feed_mutable_market_configs.go
protocol/daemons/pricefeed/client/types/price_feed_mutable_market_configs_test.go

Should log `marketParam.Id` instead of array index

Log correct market param id in price daemon error

---

protocol/x/clob/keeper/process_operations.go
protocol/x/clob/keeper/process_operations_stateful_validation.go
protocol/x/clob/keeper/process_operations_stateful_validation_test.go
protocol/x/clob/keeper/process_operations_test.go
protocol/x/clob/keeper/process_single_match.go
protocol/x/clob/types/match_with_orders.go
protocol/x/clob/types/match_with_orders_test.go

Miscellaneous code cleanup from the `DeliverTx` flow audit.
Note this PR shouldn't contain any logic changes.

CLOB `DeliverTx` audit cleanup

---

indexer/services/roundtable/src/helpers/loops-helper.ts

- move the wait for lock to expire + jitter logic into a separate function
- If initial redis lock was not acquired, wait and continue the loop so that all of the more complex logic can be unindented

Improve readability for loops-helper.ts

---

protocol/app/module_accounts_test.go

Added the single test that was missing.

[DEC-2081] Audit app/module_accounts.go

---

protocol/daemons/pricefeed/client/client_test.go
protocol/daemons/pricefeed/client/price_fetcher/mutable_state.go
protocol/daemons/pricefeed/client/types/market_to_price.go
protocol/daemons/pricefeed/client/types/price_feed_mutable_market_configs.go
protocol/daemons/pricefeed/metrics/market_pairs.go
protocol/daemons/server/types/liquidations/liquidatable_subaccount_ids.go
protocol/daemons/server/types/pricefeed/market_to_exchange_prices.go

According to [this thread](https://dydx-team.slack.com/archives/GTGEVSCUU/p1695669700849339).

[DEC-2078,DEC-2079] - Swap sync.RWMutex for sync.Mutex in all daemon code

---

indexer/services/roundtable/__tests__/tasks/update-compliance-data.test.ts
indexer/services/roundtable/src/tasks/update-compliance-data.ts

Add additional error-handling so that the task continues to update data for addresses even if some in the batch encounter errors when calling the compliance provider.

Add error handling for compliance.

---

protocol/scripts/bridge_events/bridge_events.go

example:
```
tianqin@Tians-MBP protocol % go run scripts/bridge_events/bridge_events.go -rpc https://eth-sepolia.g.alchemy.com/v2/HgoWxKwRrh4iusoyEKqHl7WI_dGFQX67 -toblock 4300000
Using the following configuration (modifiable via flags):
denom: adv4tnt
totalsupply: 1000000000000000000000000000
rpc: https://eth-sepolia.g.alchemy.com/v2/HgoWxKwRrh4iusoyEKqHl7WI_dGFQX67
address: 0xcca9D5f0a3c58b6f02BD0985fC7F9420EA24C1f0
toblock: 4300000
Total amount bridged: 223
Remaining bridge module account balance: 999999999999999999999999777
"bridge.event_params": {
"denom": "adv4tnt",
"eth_chain_id": 11155111,
"eth_address": "0xcca9D5f0a3c58b6f02BD0985fC7F9420EA24C1f0"
}
"bridge.acknowledged_event_info": {
"next_id": 1,
"eth_block_height": 4291860
}
"bank.balances": [
{
"address": …
```

output total amount bridged and remaining in bridge events script

---

protocol/daemons/server/types/update_monitor.go
protocol/daemons/server/types/update_monitor_test.go

Disable daemon health check panic

---

v4-proto-js/package.json

Fix v4-proto-js becoming private

---

protocol/x/clob/keeper/deleveraging.go

Downgrade log from Error to Debug.

downgrade log in deleveraging

---

protocol/lib/metrics/util.go
protocol/x/perpetuals/keeper/perpetual.go

- Add method to support sampling of module measure since.

Sample latency metrics in hot code path

---

protocol/lib/metrics/util.go
protocol/x/perpetuals/keeper/perpetual.go

defer time now

---

protocol/scripts/genesis/check_sample_pregenesis_uptodate.sh
protocol/scripts/genesis/prod_pregenesis.sh
protocol/testing/genesis.sh

- Seed rewards vester with realistic balance in testing environment 
- Clean up some balance constant in `genesis.sh` 
Added a script to check whether `sample_pregenesis.json` is up-to-date
- Ran `make localnet start`
- Also, made sure this doesn't affect prod_genesis with a script (also added in this PR) to compare old `sample_pregenesis.json` vs. newly generated one.

Update vester account balance at genesis

---

protocol/lib/metrics/util.go

fix issue where GetCallbackMetricFromCtx

---

protocol/daemons/bridge/client/client.go
protocol/daemons/bridge/client/client_test.go

Bridge daemon audit results. Mainly adding more comments. 
See audit log of bridge daemon [here](https://www.notion.so/dydx/Internal-Audit-5328768f07154d928f0794121b355644?pvs=4#825b17a1cdda45a0b5524ac9bc59c41c)

[CORE-649] add comments to bridge daemon functions and slight optimization of slice initialization

---

protocol/x/delaymsg/keeper/dispatch.go
protocol/x/delaymsg/types/keys.go

[CORE-648] fix delaymsg error logging

---

protocol/go.mod
protocol/go.sum

- Bump cosmos sdk fork version to get rid to the in memory sink.

[CLOB-955] Bump cosmos sdk fork

---

protocol/app/prepare/prepare_proposal.go
protocol/app/prepare/prepare_proposal_test.go

Mainly swap to use multi value return with error as its own type since this is idiomatic for Go. Minor test improvements.
Existing tests that are updated. Coverage here is pretty good but without app e2e test support for daemons can't easily convert to e2e test.

[DEC-2081] Audit app/prepare/prepare_proposal.go

---

protocol/README.md

Remove make proto-gen from README.md
none

Remove make proto-gen documentation

---

indexer/CHANGELOG.md
indexer/services/ender/__tests__/handlers/order-fills/liquidation-handler.test.ts
indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
indexer/services/ender/src/handlers/order-fills/abstract-order-fill-handler.ts
indexer/services/ender/src/scripts/dydx_get_order_status.sql
indexer/services/ender/src/scripts/dydx_order_fill_handler_per_order.sql

Change the way ender processes orderFills and correctly update the order status
Unit tests

[IND-412]: Correctly set order status for all order types

---

indexer/packages/v4-protos/package.json
indexer/pnpm-lock.yaml

[IND-390]: Bump protobufjs version

---

protocol/lib/big_math.go
protocol/lib/big_math_test.go
protocol/lib/math.go
protocol/lib/math_test.go
protocol/x/perpetuals/keeper/perpetual.go

Comments and method renames to clarify cases when methods may cause panics, rounding behavior.
- Confirmed that panics which bubble up to x/perpetuals are expected/desired.
- Rounding behavior in modules was already audited, but added documentation.
No behavior changes.

[DEC-2097] - lib/math audit

---

protocol/testing/genesis.sh

Reduce TEST-USD subticks_per_tick in genesis

---

indexer/services/ender/src/handlers/order-fills/abstract-order-fill-handler.ts
indexer/services/ender/src/scripts/dydx_get_order_status.sql

Fix FOK orders so status is always FILLED

---

protocol/testutil/app/app.go

A clob e2e test that spawns multiple go routines is causing race test failures due to cometbft using a cached testing logger, see these failures:
- https://github.com/dydxprotocol/v4-chain/actions/runs/6499692557/job/17653547531?pr=595
- https://github.com/dydxprotocol/v4-chain/actions/runs/6498165667/job/17648913591?pr=587
- https://github.com/dydxprotocol/v4-chain/actions/runs/6498966545/job/17651354169?pr=588
This PR adds a method that manually creates a new logger each time it is used in `TestApp.CheckTx` to resolve the race condition.

[DEC-2149] Fix race test failures caused by cached cometbft test logger

---

protocol/x/delaymsg/keeper/msg_server.go

Remove error logging where errors are already returned.

[CORE-648] - Remove unnecessary logging from delaymsg.

---

protocol/x/rewards/types/keys.go
protocol/x/rewards/types/keys_test.go
protocol/x/vest/types/keys.go
protocol/x/vest/types/keys_test.go

Remove unused keys in vest, rewards. [Context](https://dydx-team.slack.com/archives/C051L432H5M/p1697059938303149)
N/A

Remove unused keys in vest, rewards

---

protocol/lib/eth/util.go
protocol/lib/eth/util_test.go

- Cleanup lib/eth code and add tests
- Added more unit tests

[CORE-654] Audit lib/eth

---

protocol/lib/metrics/constants.go
protocol/x/prices/keeper/msg_server_create_oracle_market.go
protocol/x/prices/keeper/msg_server_test.go
protocol/x/prices/keeper/msg_server_update_market_param.go

Add telemetry for new msg service methods. Remove unused test file.

[CORE-658] - Telemetry updates, remove commented out test file

---

protocol/x/sending/keeper/transfer_test.go

[CORE-650] add unit test to sending module governance message

---

protocol/daemons/bridge/client/client.go
protocol/daemons/bridge/client/client_test.go
protocol/daemons/bridge/client/types/eth_client.go
protocol/daemons/bridge/client/types/query_client.go

Minor cleanup of bridge daemon
N/A

Minor cleanup of bridge daemon

---

protocol/x/clob/memclob/memclob.go

explanation in slack: https://dydx-team.slack.com/archives/C03SLFHC3L7/p1697151824501269?thread_ts=1697058864.556479&cid=C03SLFHC3L7
Basically, a Preexisting Stateful Order and Order Removal operation both being in the ops queue can result in duplicate placements in ReplayOperations. 
Order Removals should never precede Preexisting stateful orders in the queue. If a preexisting stateful order placement precedes an order removal, skip the order removal.

Prevent stateful orders from being replayed twice

---

protocol/x/perpetuals/keeper/msg_server_add_premium_votes.go
protocol/x/perpetuals/keeper/perpetual.go
protocol/x/perpetuals/types/constants.go
protocol/x/perpetuals/types/errors.go
protocol/x/perpetuals/types/genesis.go
protocol/x/perpetuals/types/liquidity_tier.go

- Add additional comments for readability, broken invariant
- Removed staled TODO items
- Removed unused variables
- Added a panic where an invariant is broken
N/A

[CORE-664] Add comment/remove unnecessary lines in `x/perpetual`

---

protocol/app/app.go
protocol/daemons/bridge/client/client.go
protocol/daemons/liquidation/client/client.go
protocol/daemons/pricefeed/client/client.go

- logs flags for the liquidations daemon

Add INFO logs for all parsed flags (app, daemons, clob)

---

protocol/x/perpetuals/types/genesis.go
protocol/x/perpetuals/types/liquidity_tier.go

Nits mentioned [here](https://dydx-team.slack.com/archives/C03FP255RRU/p1697221645799359?thread_ts=1697215546.282749&cid=C03FP255RRU)
N/A

Fix nits in x/perpetual 

---

protocol/x/clob/keeper/deleveraging.go
protocol/x/clob/keeper/liquidations.go

address comments for pull/613

---

protocol/app/app.go
protocol/app/upgrades.go
protocol/app/upgrades_test.go

Add a test that covers setting up the upgrade handlers.

[DEC-2081] Audit upgrades.go

---

indexer/packages/redis/src/caches/orderbook-levels-cache.ts

Improve logging for error log

---

indexer/README.md

Remove references to private repos

---

protocol/scripts/genesis/prod_pregenesis.sh
protocol/scripts/genesis/sample_pregenesis.json

Update default slashing params. Latest changes are discussed [here](https://www.notion.so/dydx/AC-Priv-Genesis-Parameters-d2321636dd494ee49cc95b7825cbbc98?pvs=4#1fae11680769402d89167d9e4c43a426)
Ran `make update-sample-pregenesis` to update `sample_pregenesis.json`

Update default slashing params

---

.github/workflows/indexer-build-and-push-dev-staging.yml
.github/workflows/indexer-build-and-push-testnet.yml
.github/workflows/protocol-build-and-push-snapshot.yml
.github/workflows/protocol-build-and-push.yml

Fix typo that's causing workflows not to run on some release branches.

Fix workflow branch names

---

protocol/lib/metrics/constants.go
protocol/x/clob/keeper/keeper.go
protocol/x/clob/keeper/mev_test.go
protocol/x/clob/keeper/msg_server_cancel_orders.go
protocol/x/clob/keeper/msg_server_cancel_orders_test.go
protocol/x/clob/keeper/msg_server_place_order.go
protocol/x/clob/keeper/msg_server_place_order_test.go

Cherrypick logging updates to release branch

---

protocol/x/clob/keeper/keeper.go
protocol/x/clob/keeper/keeper_test.go
protocol/x/clob/keeper/orders.go
protocol/x/clob/keeper/orders_test.go
protocol/x/clob/keeper/stateful_order_state.go
protocol/x/clob/keeper/stateful_order_state_test.go

- Include untriggered conditional orders in stateful order count.

Include untriggered conditional orders in stateful order count

---

protocol/scripts/genesis/sample_pregenesis.json
protocol/testing/genesis.sh

Update `min_position_notional_liquidated` to 1000 USDC.
[Slack thread for context](https://dydx-team.slack.com/archives/C04BNGM82HM/p1697559168985669).

Update `min_position_notional_liquidated` to 1000 USDC

---

protocol/scripts/genesis/sample_pregenesis.json
protocol/testing/genesis.sh

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/640 from `main`

[Cherry-pick] update base position notional in genesis.sh

---

protocol/scripts/genesis/prod_pregenesis.sh
protocol/scripts/genesis/sample_pregenesis.json

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/636

Cherry pick: slashing params

---

protocol/x/clob/keeper/deleveraging.go
protocol/x/clob/keeper/liquidations.go
protocol/x/clob/keeper/process_operations.go
protocol/x/clob/keeper/process_single_match.go
protocol/x/clob/types/stat_internal_operations.go

- Improve liquidation and deleveraging telemetry by switching to use AddSampleWithLabels

More telemetry improvements for liquidation and deleveraging

---

protocol/daemons/pricefeed/client/constants/testdata/ldo_exchange_config.json
protocol/daemons/pricefeed/client/constants/testdata/near_exchange_config.json
protocol/scripts/genesis/sample_pregenesis.json
protocol/testutil/daemons/pricefeed/exchange_config/testnet_exchange_market_config.go

- Add OKX exchange for NEAR
- Add adjust by USDT/USD for LDO/USDT

Fix `x/prices` exchange config

---

protocol/x/rewards/keeper/keeper_test.go

In reward unit test, update test reward denom to -18 for realism
N/A

[CORE-645] Update test reward denom to -18

---

protocol/lib/quantums.go
protocol/lib/quantums_test.go

- Improve comments in `lib/quantums.go`.
- Added additional unit tests
Unit tests

[DEC-2099] lib/quantums.go audit: improve comments, add unit tests

---

protocol/.env
protocol/daemons/flags/flags.go
protocol/docker-compose.yml
protocol/testing/containertest/testnet.go
protocol/testing/snapshotting/snapshot.sh

Require bridge daemon eth rpc endpoint flag in start command
Tried running localnet without specifying the flag and it errored out due to flag being required.

[CORE-715] require bridge daemon eth rpc endpoint flag in start command

---

protocol/x/clob/abci_test.go
protocol/x/clob/keeper/process_proposer_matches_events.go
protocol/x/clob/keeper/process_proposer_matches_events_test.go
protocol/x/clob/memclob/memclob.go
protocol/x/clob/types/process_proposer_matches_events.go

Panic if PPME is ever set with duplicate order ids.

Duplicate validation checking for ProcessProposerMatchesEvents

---

protocol/go.mod
protocol/scripts/iaviewer/iaviewer.go

- Fork iaviewer from https://github.com/cosmos/iavl/blob/v0.20.0/cmd/iaviewer/main.go
- Small change backported to avoid usage of internal package: https://github.com/cosmos/iavl/commit/6aa391fc4c0d1b9f42c7cd2ffc9c8037dc39e601#diff-23bb305cd4981c07e53c8349961a155609fd292e0bcaddfc0154c0856d150675
- Manually tried it out: `go run scripts/iaviewer/iaviewer.go localnet/dydxprotocol0/application.db "" 1`

Fork iaviewer

---

protocol/cmd/dydxprotocold/cmd/tendermint.go

- Add debug tendermint command

Add debug tendermint command

---

protocol/daemons/bridge/client/client.go
protocol/daemons/bridge/client/client_test.go

[CORE-715] fix bridge client tests and add test on empty eth rpc endpoint

---

indexer/packages/postgres/src/helpers/db-helpers.ts
indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
indexer/services/ender/src/scripts/dydx_get_fee_from_liquidity.sql
indexer/services/ender/src/scripts/dydx_get_order_status.sql
indexer/services/ender/src/scripts/dydx_get_total_filled_from_liquidity.sql
indexer/services/ender/src/scripts/dydx_order_fill_handler_per_order.sql

Fix order handler to return correct updatedAt/updatedAtHeight.
Also rename functions to have dydx_ prefix to allow for script deletion to successfully remove and update these functions during ender deployment.
Updated existing tests to use initial values that differ from the expected updated state.

Fix order handler to return correct updatedAt/updatedAtHeight

---

protocol/testing/e2e/funding/funding_e2e_test.go

Settle each subaccount with an open position at the `funding-tick` and check that the funding payment is as expected.
E2E tests

[CORE-703] Check funding settlement in e2e test

---

protocol/testing/e2e/funding/funding_e2e_test.go
protocol/testing/e2e/trading_rewards/trading_rewards_test.go
protocol/testutil/clob/human_order.go
protocol/testutil/clob/order.go
protocol/testutil/pricefeed/index_price.go

Add an E2E test suite for testing vesting and trading rewards
E2E tests

[CORE-617] Add vest/rewards e2e test suite

---

protocol/scripts/governance/enable_all_clob_pairs.sh

Add a sample bash script to generate a gov proposal to enable trading on all clob pairs
Sent test gov proposal to staging, and proposal successfully passed validation.
Also manually compared the output matches with the previous proposal I constructed to enable all trading pairs from `INITIALIZING` on staging

Add sample script to generate gov proposal for enabling trading

---

indexer/services/ender/__tests__/handlers/update-clob-pair-handler.test.ts
indexer/services/ender/__tests__/handlers/update-perpetual-handler.test.ts
indexer/services/ender/src/config.ts
indexer/services/ender/src/handlers/update-perpetual-handler.ts
indexer/services/ender/src/helpers/postgres/postgres-functions.ts
indexer/services/ender/src/scripts/dydx_update_clob_pair_handler.sql
indexer/services/ender/src/scripts/dydx_update_perpetual_handler.sql

[IND-476] Update ender update perpetual handler to execute updates via a SQL function.

[IND-476] Update ender update perpetual handler to execute updates via a SQL function.

---

indexer/services/ender/__tests__/handlers/perpetual-market-handler.test.ts
indexer/services/ender/src/config.ts
indexer/services/ender/src/handlers/perpetual-market-handler.ts
indexer/services/ender/src/helpers/postgres/postgres-functions.ts
indexer/services/ender/src/scripts/dydx_perpetual_market_handler.sql

[IND-473] Update ender perpetual market create to execute updates via a SQL function.

[IND-473] Update ender perpetual market create to execute updates via a SQL function.

---

indexer/packages/postgres/src/constants.ts
indexer/packages/postgres/src/index.ts
indexer/packages/postgres/src/models/liquidity-tiers-model.ts
indexer/services/ender/__tests__/handlers/liquidity-tier-handler.test.ts
indexer/services/ender/src/config.ts
indexer/services/ender/src/handlers/liquidity-tier-handler.ts
indexer/services/ender/src/helpers/postgres/postgres-functions.ts
indexer/services/ender/src/scripts/dydx_liquidity_tier_handler.sql

[IND-472] Update ender liquidity tier upsert to execute updates via a SQL function.

[IND-472] Update ender liquidity tier upsert to execute updates via a SQL function.

---

.github/workflows/indexer-build-and-push-mainnet.yml

Add workflow to push to mainnet AWS ECR repo.
N/A

[CLOB-976] Push indexer ECR images to mainnet.

---

protocol/testing/snapshotting/snapshot.sh

- Add additional pruning configs to reduce snapshot size
- Tested these configurations on a snapshot node

Add more pruning configs

---

protocol/testing/e2e/funding/funding_e2e_test.go

- Add test with varying funding rate 
- Update how oracle price is updated
E2E test

[CORE-712] Add e2e funding test with varying funding rate; update how oracle price is updated

---

protocol/app/constants.go
protocol/app/module/slashing.go
protocol/app/prepare/metrics.go

* Removing TODOs that are obsolete
N/A

[DEC-1106] Remove obsolete TODOs

---

protocol/x/prices/keeper/update_price.go

Remove info logs for missing index prices, smoothed prices, for newly created markets, to reduce user confusion over a non-error condition and test log volume, which makes it difficult to detect actual test errors.

[CORE-793] - Remove log for recent markets.

---

protocol/mocks/MemClobKeeper.go
protocol/testutil/memclob/keeper.go
protocol/x/clob/e2e/order_removal_test.go
protocol/x/clob/keeper/orders.go
protocol/x/clob/keeper/orders_test.go
protocol/x/clob/memclob/memclob.go
protocol/x/clob/types/mem_clob_keeper.go

slack [link](https://dydx-team.slack.com/archives/C03SLFHC3L7/p1700586467347989?thread_ts=1700585921.453239&cid=C03SLFHC3L7)
We should validate stateful orders in PrepareCheckState Replay.

Statefully validate stateful orders in PrepareCheckState Replay

---

protocol/app/upgrades/v2.0.0/constants.go

Chore: Height fix

---

protocol/scripts/governance/bridge_vesters_set_rewards.py

Add sample script
Example output:
```
% python3 scripts/governance/bridge_vesters_set_rewards.py
Estimated block height for rewards multiplier update 1 2023-12-19T15:00:00+00:00 = 3609052
Estimated block height for rewards multiplier update 2 2024-01-16T15:00:00+00:00 = 5571096
Output written to proposal_bridge_vesters_set_rewards.json
```
Output file:
```
"denom": "adv4tnt",
"denomExponent": -18,
"marketId": 1000001,
"fee_multiplier_ppm": 330000
}
},
{
"@type": "/dydxprotocol.delaymsg.MsgDelayMessage",
"authority": "dydx10d07y265gmmuvt4z0w9aw880jnsr700jnmapky",
"msg": {
"@type": "/dydxprotocol.rewards.MsgUpdateParams",
"authority": "dydx1mkkvp26dngu6n8rmalaxyp3gwkjuzztq5zx6tr",
"params": {
"treasuryAccount": "rewards_treasury",
"denom": "adv4tnt",
"denomExponent": -18,
"marketId": …
```

Sample gov script for funding vesters + adjust trading rewards

---

protocol/testing/e2e/funding/funding_e2e_test.go
protocol/testing/e2e/trading_rewards/trading_rewards_test.go
protocol/testutil/clob/human_order.go
protocol/testutil/clob/order.go
protocol/testutil/pricefeed/index_price.go

[CORE-617] [Resubmit] Add vest/rewards e2e test suite

---

protocol/app/app.go
protocol/x/clob/flags/flags.go
protocol/x/clob/flags/flags_test.go
protocol/x/clob/keeper/keeper.go
protocol/x/clob/keeper/mev.go
protocol/x/clob/mev_telemetry/telemetry.go

Duplicate of https://github.com/dydxprotocol/v4-chain/pull/831, but committed from my account so that the commits are signed.

Enable using multiple mev telemetry hosts

---

e2e-testing/.env
e2e-testing/docker-compose-e2e-test.yml
e2e-testing/run-containerized-env.sh
protocol/Makefile
protocol/testing/e2etest-local/Dockerfile
protocol/testing/e2etest-local/local.sh
protocol/testing/genesis.sh

create a containerized Docker environment running the protocol locally with fixed prices for 3 markets (btc, eth, sol), Indexer, and all Indexer dependencies.
ran locally

[IND-510] setup containerized Docker env for e2e testing

---

.github/workflows/indexer-build-and-push-mainnet.yml
indexer/packages/postgres/__tests__/db/helpers.test.ts
indexer/packages/postgres/src/db/helpers.ts
indexer/services/comlink/__tests__/controllers/api/v4/addresses-controller.test.ts
indexer/services/comlink/__tests__/controllers/api/v4/perpetual-positions-controller.test.ts
indexer/services/comlink/__tests__/lib/helpers.test.ts
indexer/services/comlink/src/lib/helpers.ts
indexer/services/roundtable/src/helpers/pnl-ticks-helper.ts

Cherry-pick changes for indexer v1.0.3
Will test in `testnet`

Cherry-pick changes for indexer v1.0.3

---

protocol/daemons/liquidation/client/client.go
protocol/daemons/liquidation/client/grpc_helper.go
protocol/daemons/liquidation/client/grpc_helper_test.go
protocol/lib/metrics/metric_keys.go
protocol/mocks/QueryClient.go
protocol/testutil/grpc/client.go

[CLOB-1037] grpc to get all perpetuals and liquidity tiers

---

protocol/daemons/liquidation/client/sub_task_runner.go
protocol/daemons/liquidation/client/sub_task_runner_test.go
protocol/testutil/constants/perpetuals.go
protocol/testutil/constants/subaccounts.go
protocol/x/perpetuals/keeper/perpetual.go
protocol/x/subaccounts/keeper/subaccount.go
protocol/x/subaccounts/types/expected_keepers.go

- Replicate funding settlements on liquidation daemon

[CLOB-1044] replicate funding settlement on liquidation daemon

---

protocol/testutil/constants/clob_pair.go
protocol/x/clob/keeper/clob_pair.go
protocol/x/clob/keeper/orders_test.go

- reject all orders in CheckTx for markets in final settlement

[CLOB-1010] final settlement checktx validation

---

indexer/services/comlink/__tests__/lib/helpers.test.ts
indexer/services/comlink/src/lib/helpers.ts

We no longer adjust IMF. Remove adjusted IMF calculation.
This bug is currently causing a div by 0 error in comlink `/addresses` endpoint when paired with the most recent protocol changes.
unit tested.

remove adjusted IMF calculation

---

protocol/app/ante/msg_type_test.go
protocol/app/app.go
protocol/app/app_test.go
protocol/app/basic_manager/basic_manager.go
protocol/app/module_accounts.go
protocol/app/module_accounts_test.go
protocol/app/msgs/all_msgs.go
protocol/app/msgs/normal_msgs.go
protocol/app/msgs/normal_msgs_test.go
protocol/app/msgs/unsupported_msgs.go
protocol/app/msgs/unsupported_msgs_test.go
protocol/app/process/acknowledge_bridges.go
protocol/app/simulation_test.go
protocol/app/testdata/default_genesis_state.json
protocol/app/upgrades/v3.0.0/constants.go
protocol/app/upgrades/v3.0.0/upgrade.go
protocol/app/upgrades/v3.0.0/upgrade_test.go
protocol/lib/ante/app_injected_msg_test.go
protocol/lib/ante/disallow_msg_test.go
protocol/lib/ante/unsupported_msgs.go
protocol/lib/ante/unsupported_msgs_test.go
protocol/scripts/genesis/sample_pregenesis.json
protocol/testing/genesis.sh
protocol/testutil/encoding/utils.go

- Add ICA Host Submodule
- Add upgrade handler for `v3.0.0`
See [doc](https://www.notion.so/dydx/Supporting-Interchain-Accounts-Liquid-Staking-33e7b09f0bcf44a5b3d1d6931c58d99c?pvs=4) for context.
References used:
- [Osmosis](https://github.com/osmosis-labs/osmosis/pull/1564/files#diff-5753166d13156fd5aef1942b3f43e956e611eedca722219a7da88e29f926e765) (small fix [here](https://github.com/osmosis-labs/osmosis/pull/2539/files))
- Example dYdX Chain [PR](https://github.com/dydxprotocol/v4-chain/pull/461)

[CORE-848] Add ICA Host Submodule

---

.github/mergify.yml

Update mergify rules for latest release branches.
N/A

Update mergify rules

---

indexer/services/ender/__tests__/handlers/trading-rewards-handler.test.ts
indexer/services/ender/src/lib/block-processor.ts
indexer/services/scripts/src/helpers/block-helpers.ts
indexer/services/scripts/src/helpers/types.ts

Add trading_rewards to print block script, and expect the block to be processed from the end block
None

Add trading_rewards to print block script

---

indexer/services/ender/__tests__/handlers/trading-rewards-handler.test.ts
indexer/services/ender/src/lib/block-processor.ts
indexer/services/scripts/src/helpers/block-helpers.ts
indexer/services/scripts/src/helpers/types.ts

Fix Trading reward event processing (#913)

---

protocol/app/app.go
protocol/x/ratelimit/keeper/keeper.go
protocol/x/ratelimit/keeper/keeper_test.go
protocol/x/ratelimit/types/expected_keepers.go
protocol/x/ratelimit/types/params.go

Pretty straightforward logic change. Mostly adding/updating tests

[CORE-836] Implement `GetBaseline`

---

indexer/services/ender/__tests__/handlers/order-fills/deleveraging-handler.test.ts
indexer/services/ender/__tests__/handlers/order-fills/liquidation-handler.test.ts
indexer/services/ender/src/handlers/order-fills/liquidation-handler.ts

add more granular stats for liquidations/deleveraging
unit tested

add more granular stats for liquidations/deleveraging

---

protocol/scripts/genesis/sample_pregenesis.json
protocol/testing/genesis.sh

Update `controller_enabled` to false in `genesis.sh`

---

indexer/services/comlink/__tests__/controllers/api/v4/addresses-controller.test.ts
indexer/services/comlink/public/api-documentation.md
indexer/services/comlink/public/swagger.json
indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
indexer/services/comlink/src/types.ts

Update /v4/addresses/:address to return totalTradingRewards
Updated unit test

[IND-504]: Update /v4/addresses/:address to return totalTradingRewards

---

protocol/x/clob/keeper/match_state.go
protocol/x/clob/keeper/match_state_test.go
protocol/x/clob/keeper/stores.go
protocol/x/clob/types/keys.go

- Update state R/W methods for improved conditional order triggering

[CLOB-1054] update state R/W methods

---

protocol/scripts/governance/community_treasury_sending.py

See title.
Example input csv:
```
addr1,1234.5
addr2,0.34
```
Example output json:
```
{
"title": "TODO: Fill in proposal title",
"deposit": "10000000000000000000000adv4tnt",
"summary": "\nTODO: Fill in proposal content. \nInclude detailed description of the proposal, links to governance discussion forums (if applicable).\nAny signal proposal in text should also be added here.\n",
"messages": [
{
"@type": "/dydxprotocol.sending.MsgSendFromModuleToAccount",
"authority": "dydx10d07y265gmmuvt4z0w9aw880jnsr700jnmapky",
"sender_module_name": "community_treasury",
"recipient": "addr1",
"coin": {
"amount": "1234500000000000000000",
"denom": "adv4tnt"
}
},
{
"@type": "/dydxprotocol.sending.MsgSendFromModuleToAccount",
"authority": "dydx10d07y265gmmuvt4z0w9aw880jnsr700jnmapky", …
```

Add sample script to generate governance proposal to send from community treasury

---

protocol/app/app.go
protocol/wasmbinding/README.md
protocol/wasmbinding/bindings/oracle_query.go
protocol/wasmbinding/queries.go
protocol/wasmbinding/query_plugin.go
protocol/wasmbinding/wasm.go

Used https://github.com/sei-protocol/sei-chain/pull/63 and https://github.com/osmosis-labs/osmosis/tree/main/wasmbinding as example

Add Golang handler for custom querier OracleQuery

---

protocol/wasmbinding/README.md
protocol/wasmbinding/queries.go
protocol/wasmbinding/query_plugin.go

add subaccount module querying support

add subaccount module querying support

---

protocol/dydx-cosmwasm/.cargo/config
protocol/dydx-cosmwasm/Cargo.lock
protocol/dydx-cosmwasm/cargo.toml
protocol/dydx-cosmwasm/src/bytes_helper.rs
protocol/dydx-cosmwasm/src/lib.rs
protocol/dydx-cosmwasm/src/proto_structs.rs
protocol/dydx-cosmwasm/src/querier.rs
protocol/dydx-cosmwasm/src/query.rs
protocol/dydx-cosmwasm/src/response_helper.rs
protocol/dydx-cosmwasm/src/route.rs

add rust lib for subaccount query
unit tested

add rust lib for subaccount query

---

protocol/app/upgrades/v4.0.0/constants.go
protocol/testing/containertest/testnet_test.go

[CORE-538] Update upgrade test to use 3.0.0 binaries.
Existing test passes.

[CORE-538] Update upgrade test to use 3.0.0 binaries.

---

protocol/app/app.go
protocol/contracts/dydx-messages-example/src/contract.rs
protocol/contracts/dydx-messages-example/src/msg.rs
protocol/dydx-cosmwasm/src/lib.rs
protocol/dydx-cosmwasm/src/msg.rs
protocol/wasmbinding/bindings/msg.go
protocol/wasmbinding/msg_plugin.go
protocol/wasmbinding/wasm.go

- Build, deploy, instantiate contract as usual.
- Construct a json payload 
```
PLACE_ORDER='{ 
"place_order": {
"subaccount_id": {
"owner": "dydx199tqg4wdlnu4qjlxchpd7seg454937hjrknju4",
"number": 0
},
"client_id": 0,
"order_flags": 0,
"clob_pair_id": 0,
"side": 1,
"quantums": 10000000,
"subticks": 5000000000,
"good_til_block": 30,
"time_in_force": 0,
"reduce_only": false,
"client_metadata": 0,
"condition_type": 0,
"conditional_order_trigger_subticks": 0
}
}'
```
- Send a transaction to contract 
```
dydxprotocold tx wasm execute dydx14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s2de90j "$PLACE_ORDER" --from alice --gas auto --fees 1256394675000000000adv4tnt --chain-id localdydxprotocol --node $NODE
```
- Verify that transaction went …

placing orders

---

protocol/x/blocktime/keeper/keeper.go

remvoe some print statements

---

protocol/x/clob/e2e/order_removal_test.go
protocol/x/delaymsg/keeper/dispatch_test.go

[CORE-538] Split out fixing test to its own separate task.
N/A

[CORE-538] Split out fixing test to its own separate task.

---

indexer/packages/postgres/src/db/migrations/migration_files/20240122143649_add_compliance_table_address_index.ts

Add index to address for compliance_data to speed up comlink query for compliance. Currently the endpoint takes ~100ms
N/A

[IND-558]: Add index to address for compliance_data

---

indexer/services/comlink/__tests__/controllers/api/v4/addresses-controller.test.ts
indexer/services/comlink/__tests__/controllers/api/v4/historical-block-trading-reward-controller.test.ts
indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
indexer/services/comlink/src/controllers/api/v4/historical-block-trading-rewards-controller.ts

Fix addresses endpoing requiring Wallet
Unit tests

Fix addresses endpoing requiring Wallet

---

protocol/lib/metrics/metric_keys.go
protocol/x/clob/keeper/untriggered_conditional_orders.go
protocol/x/govplus/keeper/keeper_test.go
protocol/x/ratelimit/types/params.go

[CLOB-1063] add latency and gauge metrics for conditional orders

---

indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts

Fix typo for historical trading rewards

Fix typo for historical trading rewards

---

indexer/packages/postgres/src/stores/candle-table.ts
indexer/packages/postgres/src/stores/fill-table.ts
indexer/packages/postgres/src/stores/funding-index-updates-table.ts
indexer/packages/postgres/src/stores/oracle-price-table.ts
indexer/packages/postgres/src/stores/order-table.ts
indexer/packages/postgres/src/stores/perpetual-position-table.ts
indexer/packages/postgres/src/stores/pnl-ticks-table.ts
indexer/packages/postgres/src/stores/subaccount-table.ts
indexer/packages/postgres/src/stores/tendermint-event-table.ts
indexer/packages/postgres/src/stores/trading-reward-aggregation-table.ts
indexer/packages/postgres/src/stores/trading-reward-table.ts
indexer/packages/postgres/src/stores/transaction-table.ts
indexer/packages/postgres/src/stores/transfer-table.ts
indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts

Fix Aggregate Historical Trading rewards and always use generated id in tables (#1022)

---

protocol/app/ante.go

[STAB-24] Migrate over to cosmos version now that performance improvement had been released.
Existing tests.

[STAB-24] Migrate over to cosmos version now that performance improvement had been released.

---

.github/ISSUE_TEMPLATE/default-template.md

Adding a default issue template that will tag `v4-chain` on all issues. This will be directly piped to Linear which should help with us managing and prioritizing them

Update issue templates

---

.github/mergify.yml

Add backport label for `v4.x` release

---

indexer/packages/postgres/__tests__/helpers/constants.ts
indexer/packages/postgres/__tests__/stores/compliance-status-table.test.ts
indexer/packages/postgres/src/db/migrations/migration_files/20240131142122_create_compliance_status_table.ts
indexer/packages/postgres/src/helpers/db-helpers.ts
indexer/packages/postgres/src/helpers/stores-helpers.ts
indexer/packages/postgres/src/models/compliance-status-model.ts
indexer/packages/postgres/src/stores/compliance-status-table.ts
indexer/packages/postgres/src/types/compliance-status-types.ts
indexer/packages/postgres/src/types/db-model-types.ts
indexer/packages/postgres/src/types/index.ts
indexer/packages/postgres/src/types/query-types.ts

add compliance status table
unit tested.

[OTE-131] add compliance status table

---

indexer/services/socks/src/lib/message-forwarder.ts
indexer/services/vulcan/src/lib/on-message.ts

Reduce number of logs by logging to debug
none

Reduce number of logs by logging to debug

---

indexer/packages/postgres/src/stores/funding-index-updates-table.ts

Optimize funding index update query (#1061)

---

protocol/x/subaccounts/types/position_size_test.go

[CORE-596] Remove TODO to add tests

---

protocol/lib/metrics/metric_keys.go
protocol/x/clob/keeper/liquidations.go
protocol/x/subaccounts/keeper/subaccount.go

Needed to create a monitor on when high rate of subaccounts are created

Metric for when subaccounts are created

---

indexer/services/roundtable/src/lib/athena-ddl-tables/orders.ts

`triggerPrice` is missing from the Research Env `orders` table. So add it in 😄 

Add triggerPrice to Athena table

---

protocol/app/e2e/query_test.go
protocol/go.mod
protocol/go.sum

[OTE-180] Update Cosmos SDK and add parallel query tests.
Tests added.

[OTE-180] Update Cosmos SDK and add parallel query tests.

---

indexer/services/scripts/README.md

Add `print-block` cmd to scripts README

Add `print-block` cmd to scripts README

---

indexer/services/roundtable/src/lib/athena-ddl-tables/orders.ts

Cherry pick https://github.com/dydxprotocol/v4-chain/pull/1083 into release

Cherry pick https://github.com/dydxprotocol/v4-chain/pull/1083 into release

---

indexer/packages/postgres/src/stores/order-table.ts
indexer/packages/postgres/src/types/query-types.ts
indexer/services/comlink/__tests__/controllers/api/v4/orders-controller.test.ts
indexer/services/comlink/src/controllers/api/v4/orders-controller.ts
indexer/services/roundtable/src/tasks/cancel-stale-orders.ts

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/1100 into release branch
Unit tested

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/1100 into release branch

---

indexer/services/ender/__tests__/handlers/funding-handler.test.ts
indexer/services/ender/__tests__/helpers/constants.ts
indexer/services/ender/__tests__/validators/funding-validator.test.ts
indexer/services/ender/src/config.ts
indexer/services/ender/src/scripts/handlers/dydx_funding_handler.sql
indexer/services/ender/src/validators/funding-validator.ts

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/1093 into v4

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/1093 into v4

---

indexer/services/roundtable/src/lib/athena-ddl-tables/orders.ts

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/1104 into v4

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/1104 into v4

---

protocol/x/clob/abci_test.go
protocol/x/subaccounts/keeper/transfer_test.go

Change indenting in an existing PR.

Change back indenting.

---

protocol/app/module_accounts.go
protocol/app/module_accounts_test.go
protocol/app/upgrades/v3.0.0/upgrade.go
protocol/testutil/keeper/auth.go
protocol/x/clob/abci_test.go
protocol/x/clob/client/cli/liquidations_cli_test.go
protocol/x/clob/keeper/deleveraging.go
protocol/x/clob/keeper/deleveraging_test.go
protocol/x/clob/keeper/liquidations_test.go
protocol/x/clob/keeper/mev_test.go
protocol/x/clob/keeper/process_operations_liquidations_test.go
protocol/x/clob/keeper/process_operations_long_term_test.go
protocol/x/clob/module_test.go
protocol/x/clob/types/keys.go
protocol/x/clob/types/keys_test.go
protocol/x/perpetuals/types/addresses.go
protocol/x/perpetuals/types/addresses_test.go
protocol/x/perpetuals/types/keys.go
protocol/x/perpetuals/types/keys_test.go
protocol/x/subaccounts/keeper/transfer.go
protocol/x/subaccounts/keeper/transfer_test.go

Move all references to the insurance fund into x/perpetuals
Existing tests should suffice since this is a refactor

[TRA-63] Move insurance fund into x/perpetuals

---

indexer/services/scripts/src/helpers/block-helpers.ts
indexer/services/scripts/src/helpers/types.ts

add DELEVERAGING event type to print-block script
ran on devbox

add DELEVERAGING event type to print-block script

---

protocol/app/ante.go

[OTE-151] Don't attempt to write the store during simulated transactions.

[OTE-151] Don't attempt to write the store during simulated transactions.

---

indexer/pnpm-lock.yaml
indexer/services/comlink/__tests__/controllers/api/v4/compliance-v2-controller.test.ts
indexer/services/comlink/package.json
indexer/services/comlink/src/controllers/api/v4/compliance-v2-controller.ts
indexer/services/comlink/src/lib/constants.ts

Implement skeleton & timestamp/signature validation for post /compliance/geoblock endpoint
unit tested

[OTE-141] Implement skeleton for post /compliance/geoblock endpoint

---

protocol/mocks/ClobKeeper.go
protocol/streaming/grpc/grpc_streaming_manager.go
protocol/streaming/grpc/noop_streaming_manager.go
protocol/streaming/grpc/types/manager.go
protocol/x/clob/abci.go
protocol/x/clob/keeper/keeper.go
protocol/x/clob/keeper/orders.go
protocol/x/clob/types/clob_keeper.go

[CT-647] initialize new streams and send orderbook snapshot

---

indexer/services/comlink/public/api-documentation.md
indexer/services/comlink/public/swagger.json
indexer/services/comlink/src/controllers/api/v4/candles-controller.ts
indexer/services/comlink/src/controllers/api/v4/fills-controller.ts
indexer/services/comlink/src/controllers/api/v4/historical-block-trading-rewards-controller.ts
indexer/services/comlink/src/controllers/api/v4/historical-funding-controller.ts
indexer/services/comlink/src/controllers/api/v4/historical-pnl-controller.ts
indexer/services/comlink/src/controllers/api/v4/historical-trading-reward-aggregations-controller.ts
indexer/services/comlink/src/controllers/api/v4/orders-controller.ts
indexer/services/comlink/src/controllers/api/v4/perpetual-markets-controller.ts
indexer/services/comlink/src/controllers/api/v4/perpetual-positions-controller.ts
indexer/services/comlink/src/controllers/api/v4/trades-controller.ts
indexer/services/comlink/src/controllers/api/v4/transfers-controller.ts

Update Api documentation to have correct required fields

---

indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts

use read replica rather than main instance (#1190)

---

protocol/app/app.go
protocol/x/vault/abci.go
protocol/x/vault/keeper/keeper.go
protocol/x/vault/keeper/orders.go
protocol/x/vault/keeper/orders_test.go
protocol/x/vault/keeper/shares.go
protocol/x/vault/module.go
protocol/x/vault/types/expected_keepers.go
protocol/x/vault/types/vault_id.go
protocol/x/vault/types/vault_id_test.go

scaffold x/vault endblocker
unit tests

[TRA-85] scaffold x/vault endblocker

---

protocol/daemons/slinky/client/client.go
protocol/daemons/slinky/client/client_test.go
protocol/daemons/slinky/client/price_fetcher_test.go

Move the stateful grpc server test out of the Suite.
Run CI

test: Fix flaky slinky client test

---

protocol/README.md

Update go version to 1.22 in README.md
None

Update go version to 1.22 in README.md

---

indexer/packages/postgres/__tests__/helpers/constants.ts
indexer/packages/postgres/__tests__/lib/api-translations.test.ts
indexer/packages/postgres/src/lib/api-translations.ts
indexer/services/comlink/__tests__/controllers/api/v4/addresses-controller.test.ts
indexer/services/comlink/__tests__/lib/helpers.test.ts
indexer/services/comlink/public/api-documentation.md
indexer/services/comlink/public/swagger.json
indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
indexer/services/comlink/src/controllers/api/v4/fills-controller.ts
indexer/services/comlink/src/lib/helpers.ts
indexer/services/comlink/src/types.ts

Implement GET /address/parentSubaccountNumber API
Added tests

[TRA-110] Implement GET /address/parentSubaccountNumber API

---

protocol/x/vault/keeper/msg_server_deposit_to_vault_test.go
protocol/x/vault/keeper/shares.go
protocol/x/vault/keeper/shares_test.go
protocol/x/vault/types/keys.go
protocol/x/vault/types/vault_id.go

Track shares of owners in vaults
Unit / integration tests

[TRA-170] Track shares of owners in vaults

---

protocol/app/upgrades/v5.0.0/upgrade_container_test.go

Add checks that that soft OI caps are set up correctly.
Container test

[OTE-249] Test upgrade handlers for OIMF

---

protocol/x/vault/keeper/orders.go
protocol/x/vault/keeper/orders_test.go
protocol/x/vault/keeper/vault.go
protocol/x/vault/types/errors.go
protocol/x/vault/types/expected_keepers.go
protocol/x/vault/types/params.go
protocol/x/vault/types/params_test.go

implement full vault strategy
unit tests

[TRA-114] implement full vault strategy

---

protocol/x/vault/client/cli/query.go
protocol/x/vault/client/cli/tx.go
protocol/x/vault/client/cli/util.go

* add cli for deposit to vault
* use cast library

[Backport] [TRA-188] add cli for deposit to vault (#1276)

---

protocol/x/clob/abci.go

[CT-712] send updates for both normal order matches and liquidation

---

indexer/services/socks/src/helpers/wss.ts

Cherry-pick socks logging change

Cherry-pick socks logging change

---

indexer/services/socks/src/helpers/wss.ts

Cherry pick #1294 into v4.x release branch
N/A

Cherry pick "Use sample rate with stream destroyed stats. (#1294)"

---

protocol/daemons/slinky/client/price_fetcher.go

Improve Slinky logs to prevent unnecessary logs

---

protocol/x/vault/keeper/orders.go
protocol/x/vault/keeper/orders_test.go

do not quote if order size is 0
- unit test
- tested on localnet

[TRA-198] vaults do not quote if order size is 0

---

protocol/x/vault/keeper/shares.go
protocol/x/vault/keeper/shares_test.go
protocol/x/vault/types/errors.go

return error if shares to mint is rounded down to zero
- unit tests
- localnet

[TRA-213] return error if shares to mint is rounded down to zero

---

protocol/go.mod
protocol/go.sum

- Proper initial version setting in iavl. Bug introduced by previous fixes.
N/A

Add iavl initial version fix

---

protocol/.github/workflows/release.yml
protocol/go.mod
protocol/go.sum

IAVL fix for pruned v1 nodes

---

protocol/go.mod
protocol/go.sum

Fix metrics initialization.  Comet diff:
```
> git diff 3b085f30b46213eddffa1dfb9f9ff62163e9b4ad c50784d39a5f9b8a138d883924884ff2d822d454
diff --git a/mempool/metrics.gen.go b/mempool/metrics.gen.go
index 17ece1656..f88442281 100644
--- a/mempool/metrics.gen.go
+++ b/mempool/metrics.gen.go
@@ -52,6 +52,18 @@ func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
Name:      "evicted_txs",
Help:      "Number of evicted transactions.",
}, labels).With(labelsAndValues...),
+               PurgedDurationTxs: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
+                       Namespace: namespace,
+                       Subsystem: MetricsSubsystem,
+                       Name:      "purged_duration_txs",
+                       Help:      "Number of purged …
```

Fix metrics initialization in cometbft fork

---

protocol/app/upgrades.go
protocol/app/upgrades/v4.1.0/constants.go
protocol/app/upgrades/v4.1.0/upgrade.go
protocol/testing/containertest/testnet.go

Add upgrade handler for v4.1.0

---

protocol/go.mod
protocol/go.sum

- New stores don't save on the upgrade block
- Edge case where pruned iavl v1 nodes don't save properly

Upgrade IAVL to fix issues saving to disk

---

protocol/lib/metrics/constants.go
protocol/x/vault/keeper/orders.go

Track how many vaults are active
N/A

[TRA-230] emit metric on number of active vaults

---

indexer/pnpm-lock.yaml
indexer/services/comlink/__tests__/controllers/api/v4/compliance-v2-controller.test.ts
indexer/services/comlink/package.json
indexer/services/comlink/src/controllers/api/v4/compliance-v2-controller.ts

- Validate that address corresponds to public key
- Take base64 encoded string for signedMessage and for pubKey
Unit tests

Fix Compliance types and validation

---

protocol/app/prepare/other_msgs.go

[OTE-255] Improve error log around RemoveDisallowMsg decoder

---

protocol/app/process/slinky_market_price_decoder.go
protocol/x/prices/keeper/market.go

https://www.notion.so/dydx/Slinky-Audit-notes-e036dbaef65543bdbd3ee927b2565b0c?pvs=4
none

Update comment and error in response to internal audit

---

protocol/app/app.go
protocol/app/prepare/other_msgs.go
protocol/app/prepare/other_msgs_test.go
protocol/app/prepare/prepare_proposal.go
protocol/app/prepare/prepare_proposal_test.go

Fix RemoveDisallowMsgs: tx parse error
Unit tests

[OTE-255]: Fix RemoveDisallowMsgs: tx parse error

---

protocol/app/app.go
protocol/lib/metrics/constants.go
protocol/mocks/PricesKeeper.go
protocol/x/prices/abci.go
protocol/x/prices/keeper/keeper.go
protocol/x/prices/module.go
protocol/x/prices/types/types.go

Move price cache population to Preblocker

[TRA-234]: Move price cache population to Preblocker

---

indexer/services/roundtable/src/tasks/create-pnl-ticks.ts

No error logging in this section of `create-pnl-ticks`, which is currently erroring out

simple error logging for create-pnl-ticks

---

indexer/services/roundtable/src/tasks/create-pnl-ticks.ts

Cherrypick: simple error logging for create-pnl-ticks (#1425)

---

indexer/services/roundtable/src/helpers/pnl-ticks-helper.ts

`getPnlTicksCreateObjects` is erroring out but the error isn't popping up in the logs. I figured it will be faster to fix + also find the bug if we skip any pnl ticks that error out but continue processing the ones that did not error

skip errored pnl ticks

---

.github/mergify.yml

Add mergify workflow for v5.x so that we can use labels to start backport PR

---

protocol/x/clob/e2e/app_test.go

e2e test for hydration in preblocker

---

protocol/x/subaccounts/keeper/subaccount.go

Cherry-pick https://github.com/dydxprotocol/v4-chain/pull/921
N/A

Make funding payment event ordering deterministic

---

protocol/app/app.go
protocol/lib/metrics/metric_keys.go
protocol/streaming/grpc/grpc_streaming_manager.go

Metrics for grpc full node streaming

---

indexer/packages/kafka/package.json
indexer/pnpm-lock.yaml
indexer/services/auxo/package.json
indexer/services/bazooka/package.json
indexer/services/ender/package.json
indexer/services/roundtable/package.json
indexer/services/scripts/package.json
indexer/services/socks/package.json
indexer/services/vulcan/package.json

Upgrade kafkajs to 2.2.4 in Indexer

---

protocol/go.mod
protocol/go.sum

Upgrade cosmos sdk to allow tx decoding to fail in GetBlockWithTxs

---

proto/README.md

Update proto README.md

---

protocol/docker-compose.yml

Reduce Slinky logs by filtering to only output error logs locally

---

indexer/tsconfig.json

Should be safe I think. 
https://www.typescriptlang.org/tsconfig/#declarationMap

Turn on declaration maps for vscode click through between packages

---

protocol/docker-compose.yml

Upgrade Slinky Sidecar Version to v0.4.6

Upgrade Slinky Sidecar Version to v0.4.6

---

indexer/pnpm-lock.yaml
indexer/services/comlink/package.json
indexer/services/comlink/public/api-documentation.md
indexer/services/comlink/public/swagger.json
indexer/services/comlink/src/scripts/generate-swagger.ts

Upgrade widdershins to fix autogenerated documentation
Viewed api_documentation and it looks good

Upgrade widdershins to fix autogenerated documentation

---

protocol/Dockerfile
protocol/app/app.go
protocol/contracts/dydx-messages-example/Cargo.lock
protocol/contracts/dydx-messages-example/Cargo.toml
protocol/contracts/dydx-messages-example/src/contract.rs
protocol/contracts/dydx-messages-example/src/dydx_msg.rs
protocol/contracts/dydx-messages-example/src/msg.rs
protocol/dydx-cosmwasm/Cargo.lock
protocol/dydx-cosmwasm/cargo.toml
protocol/dydx-cosmwasm/src/lib.rs
protocol/dydx-cosmwasm/src/msg.rs
protocol/dydx-cosmwasm/src/proto_structs.rs
protocol/lib/tx_mode.go
protocol/wasmbinding/bindings/msg.go
protocol/wasmbinding/msg_plugin.go
protocol/wasmbinding/wasm.go
protocol/x/clob/keeper/msg_server_place_order.go

Adding interfaces for messages for cosmwasm to unblock elixir
- Adds custom messages to cosmwasm
- includes bindings, example contract and related go functions
- Added the following messages
DepositToSubaccount
WithdrawFromSubaccount
Placeorder
CancelOrder
Tested by instantiating and executing contract
Need to add unit tests, will do it in subsequent PRs

Add custom messages to cosmwasm

---

protocol/app/app.go
protocol/app/flags/flags.go
protocol/app/flags/flags_test.go
protocol/lib/metrics/metric_keys.go
protocol/mocks/ClobKeeper.go
protocol/mocks/MemClobKeeper.go
protocol/streaming/grpc/grpc_streaming_manager.go
protocol/streaming/grpc/noop_streaming_manager.go
protocol/streaming/grpc/types/manager.go
protocol/testutil/memclob/keeper.go
protocol/x/clob/keeper/keeper.go
protocol/x/clob/keeper/order_state.go
protocol/x/clob/keeper/process_operations.go
protocol/x/clob/memclob/memclob.go
protocol/x/clob/types/clob_keeper.go
protocol/x/clob/types/mem_clob_keeper.go

This reverts commit c672943e82c884ef235c6ead7021815b1f122f74.

Revert "GRPC Streaming Batching (backport #1633) (#1663)"

---

indexer/services/comlink/public/api-documentation.md
indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-placement-handler.test.ts
indexer/services/ender/src/config.ts
indexer/services/ender/src/handlers/stateful-order/stateful-order-placement-handler.ts
indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
indexer/services/vulcan/src/handlers/order-place-handler.ts

Code cleanup

---

indexer/services/socks/src/lib/message-forwarder.ts

this PR unintentionally added back logging: https://github.com/dydxprotocol/v4-chain/pull/1646

Rm dbg logs

---

protocol/mocks/MemClobKeeper.go
protocol/testutil/memclob/keeper.go
protocol/x/clob/e2e/order_removal_test.go
protocol/x/clob/keeper/orders_test.go
protocol/x/clob/memclob/memclob.go
protocol/x/clob/memclob/memclob_cancel_order_test.go
protocol/x/clob/memclob/memclob_get_order_filled_amount_test.go
protocol/x/clob/memclob/memclob_place_order_long_term_test.go
protocol/x/clob/memclob/memclob_place_order_test.go
protocol/x/clob/memclob/memclob_purge_invalid_memclob_state_test.go
protocol/x/clob/memclob/memclob_remove_order_test.go
protocol/x/clob/memclob/memclob_test_util.go
protocol/x/clob/types/mem_clob_keeper.go

Reverts dydxprotocol/v4-chain#1682

Revert "Revert "Remove collateralization-check for unmatched orders (backport…"

---

protocol/app/app.go
protocol/testutil/keeper/vault.go
protocol/x/vault/keeper/keeper.go
protocol/x/vault/keeper/msg_server_deposit_to_vault.go
protocol/x/vault/types/expected_keepers.go

This reverts commit a061868ff8f8584a8bd620d244e4c94fcfeb55c9.

Revert "[TRA-219] emit transfer indexer event on vault deposit

---

.github/workflows/protocol-release.yml

Reverts dydxprotocol/v4-chain#1643

Revert "Disable arm release build (backport #1641)"

---

protocol/dydx-cosmwasm/README.md

Adds documentation on dydx<>cosmwasm

Add documentation on getting started with dydx-cosmwasm

---

indexer/packages/redis/__tests__/caches/orderbook-levels-cache.test.ts
indexer/packages/redis/src/caches/orderbook-levels-cache.ts

Don't throw errors when invalid price level updates occur, instead set price level to 0.
N/A

Handle invalid price level updates gracefully.

---

protocol/dydx-cosmwasm/README.md

add local testing docs

---

indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
indexer/services/comlink/src/lib/helpers.ts

Reverts dydxprotocol/v4-chain#1761

Revert "Fix screen endpoint (backport #1759)"

---

indexer/services/comlink/__tests__/controllers/api/v4/compliance-v2-controller.test.ts
indexer/services/comlink/src/controllers/api/v4/compliance-v2-controller.ts

Reverts dydxprotocol/v4-chain#1729

Revert "[OTE-420]: Deprecate ONBOARD from Indexer (backport #1728)"

---

indexer/services/comlink/__tests__/lib/compliance-and-geo-check.test.ts
indexer/services/comlink/src/lib/compliance-and-geo-check.ts

Reverts dydxprotocol/v4-chain#1725

Revert "[OTE-438] Allow users to read data if they are in FIRST_STRIKE_CLOSE_ONLY (backport #1716)"

---

indexer/services/comlink/__tests__/lib/compliance-and-geo-check.test.ts
indexer/services/comlink/src/lib/compliance-and-geo-check.ts

Reverts dydxprotocol/v4-chain#1818

Revert "Revert "[OTE-438] Allow users to read data if they are in FIRST_STRIKE_CLOSE_ONLY (backport #1716)""

---

indexer/services/comlink/__tests__/controllers/api/v4/compliance-v2-controller.test.ts
indexer/services/comlink/src/controllers/api/v4/compliance-v2-controller.ts

Reverts dydxprotocol/v4-chain#1817

Revert "Revert "[OTE-420]: Deprecate ONBOARD from Indexer (backport #1728)""

---

indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
indexer/services/comlink/src/lib/helpers.ts

Reverts dydxprotocol/v4-chain#1816

Revert "Revert "Fix screen endpoint (backport #1759)""

---

indexer/services/comlink/src/config.ts

increase default API limit from 100 -> 1000

increase default API limit from 100 -> 1000

---

protocol/indexer/events/subaccount_update.go

[CT-989] update indexer subaccount updates to include new quote balance

---

protocol/x/subaccounts/keeper/margining.go
protocol/x/subaccounts/keeper/margining_test.go

[CT-1002] small optimization for rebalancing

---

protocol/dydx-cosmwasm/src/serializable_int.rs

- the bigint var in serialiable int is private. Adding a public function to get the big in value

add helper function to get big int value

---

protocol/app/upgrades.go
protocol/app/upgrades/v6.0.0/upgrade.go
protocol/app/upgrades/v6.0.0/upgrade_container_test.go
protocol/x/vault/keeper/params.go

1. initialize `DefaultQuotingParams` based on old `Params`
2. remove old `Params`
container test
staging upgrade test

add v6 upgrade handler for x/vault

---

indexer/services/vulcan/src/config.ts
indexer/services/vulcan/src/helpers/kafka/kafka-controller.ts

Set fromBeginning to false by default (#2101)

---

protocol/testing/testnet/testnet.sh
protocol/testing/version/version.sh

Build image with different pre and post upgrade versions for testnet

---

indexer/services/bazooka/src/index.ts

Reverts dydxprotocol/v4-chain#2208

Revert "Fix bug in clearing topics (backport #2202)"

---

protocol/app/ante.go
protocol/app/ante/market_update.go
protocol/app/ante/market_update_test.go
protocol/app/ante_test.go

Reverts dydxprotocol/v4-chain#2317

Revert "feat: usdt protection in antehandler (backport #2315)"

---

indexer/packages/base/package.json
indexer/packages/base/src/az-id.ts
indexer/packages/base/src/config.ts
indexer/packages/base/src/index.ts
indexer/pnpm-lock.yaml

Kafka broker rack ids are the AZ id, so we need to fetch this to configure the consumers.

Add function to fetch availability zone id

---

protocol/app/ante.go
protocol/app/ante/market_update.go
protocol/app/ante/market_update_test.go
protocol/app/ante_test.go

Reverts dydxprotocol/v4-chain#2322

Revert "Revert "feat: usdt protection in antehandler (backport #2315)""

---

protocol/app/upgrades/v7.0.0/upgrade.go
protocol/app/upgrades/v7.0.0/upgrade_container_test.go
protocol/testing/containertest/preupgrade_genesis.json
protocol/x/vault/keeper/deprecated_state.go

migrate vault shares to megavault shares in v7 upgrade handler

---

protocol/app/upgrades.go
protocol/app/upgrades/v6.0.0_testnet_fix_1/constants.go
protocol/app/upgrades/v6.0.0_testnet_fix_1/upgrade.go

Add upgrade handler for v6_0_0_testnet_fix_1

---

indexer/services/ender/__tests__/lib/candles-generator.test.ts
indexer/services/ender/src/lib/candles-generator.ts

Removes code that hits the OrderbookCache when generating candles. This change will be fixed in a later update

Return undefined from getOrderbookMidPriceMap

---

protocol/testing/genesis.sh

don't initialize megavault subaccount if balance is 0 in genesis

---

indexer/services/ender/__tests__/handlers/order-fills/liquidation-handler.test.ts
indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
indexer/services/ender/src/scripts/helpers/dydx_liquidation_fill_handler_per_order.sql
indexer/services/ender/src/scripts/helpers/dydx_update_perpetual_position_aggregate_fields.sql

This reverts commit 54b3bced767db99e461a2d8a63e14b7990287ae5.

Revert "[CT-629] Fix entryPrice calc (backport #2455) (#2496)"

---

indexer/services/roundtable/__tests__/tasks/subaccount-username-generator.test.ts

Fix username generator unit test

---

.github/workflows/protocol-release.yml

This reverts commit 744a58babfb825df5b3b569c2d8e9ec8fc4b9d4c.

Revert "Use release env for release github workflow (#2608)"

---

protocol/go.mod
protocol/go.sum

bump ibc-go to latest patch on fork (commit 8733b3e)

---

indexer/services/roundtable/src/tasks/market-updater.ts

[outage] Measure call latency in market-updater

---

protocol/x/perpetuals/keeper/perpetual.go

[Context](https://dydx-team.slack.com/archives/C05FPTMD5PT/p1742073594175809?thread_ts=1742061202.138299&cid=C05FPTMD5PT)

fix(funding): Gracefully handle individual market errors in `sampleAllPerpetuals`

---

protocol/x/accountplus/keeper/timestampnonce.go

[Context](https://dydx-team.slack.com/archives/C8NL26KK2/p1747245307779229?thread_ts=1746834563.718159&cid=C8NL26KK2)
Add warn log on timestamp nonce rejection on full nodes, so we can better troubleshoot issue. 

chore: add warn log for ts nonce rejection

---

.github/workflows/protocol-release.yml

fix py release workflow

---

indexer/packages/postgres/__tests__/helpers/constants.ts
indexer/packages/postgres/src/db/migrations/migration_files/20250529150054_create_funding_payments.ts
indexer/packages/postgres/src/types/funding-payments-types.ts
indexer/services/roundtable/__tests__/tasks/update-funding-payments.test.ts
indexer/services/roundtable/src/scripts/update_funding_payments.sql

Add funding index column (backport #2905)
