dydxprotocol/v4-chain

- protocol/testutil/clob/clob_pair.go
- protocol/testutil/keeper/clob.go
- protocol/testutil/keeper/perpetuals.go
- protocol/testutil/perpetuals/perpetuals.go
- protocol/testutil/prices/market_param_price.go
- protocol/x/clob/genesis_test.go
- protocol/x/clob/keeper/clob_pair.go
- protocol/x/clob/keeper/clob_pair_test.go
- protocol/x/clob/keeper/grpc_query_clob_pair_test.go
- protocol/x/clob/keeper/msg_server_create_clob_pair.go
- protocol/x/clob/keeper/msg_server_create_clob_pair_test.go
- protocol/x/clob/keeper/msg_server_update_clob_pair.go
- protocol/x/clob/types/clob_pair.go
- protocol/x/clob/types/errors.go
- protocol/x/clob/types/message_create_clob_pair.go
- protocol/x/clob/types/message_create_clob_pair_test.go
- protocol/x/clob/types/message_update_clob_pair.go
- protocol/x/clob/types/message_update_clob_pair_test.go
- protocol/x/perpetuals/keeper/grpc_query_perpetual_test.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/perpetuals/keeper/stateful_premium_votes_validation_test.go
Implemented `MsgCreateClobPair` and also refactored `MsgUpdateClobPair` to use the same stateless validation.
> [CORE-504] Implement `MsgCreateClobPair`

- protocol/x/clob/simulation/genesis.go
https://github.com/dydxprotocol/v4-chain/pull/190 added a check that each newly created clob pair should map to an unused perpetual id.
To fix simulation, this PR modifies clob simulation so each clob pair maps to a unique perpetual id
> Fix clob simulation: each clob maps to a unique perpetual

- protocol/Makefile
I think these build args got out of sync with the dockerfile at some point. Previously this didn't matter because the dockerfile didn't expect any build args, but now we expect build args to pass in version and commit.
> Fix release docker build args

- .gitignore
- Makefile
Fix the build of v4-proto-py, as I was trying to import it into the `v4-client-py` with no luck. The following changes worked for me:
* Build everything under `v4_proto` (when importing the package, it gets put under `v4-proto`, which has incompatible naming with python)
* Add a boilerplate `__init__.py`. This was in the original `dydxpy`, i'm not completely familiar with what it does but it helped to set the subdirectories correctly
> Fix v4-proto-py package

- protocol/x/delaymsg/keeper/block_message_ids.go
- protocol/x/delaymsg/keeper/block_message_ids_test.go
- protocol/x/delaymsg/keeper/grpc_query.go
- protocol/x/delaymsg/keeper/grpc_query_test.go
This issue came up in conversation with auditors.
Originally, an int64 type was chosen to represent block_height in the delayedmsg module because the context stores block height as an int64, so no type conversions or bound checks were required.
However, the implementation of delaymsg contains a bug: auditors pointed out that we potentially allow queries with negative block height and could even return valid results for another block height if it shares the same uint64 representation as the negative int64. This PR disallows negative numbers from the query and returns "not found" for the keeper method.
> [CORE-551] - Disallow negative block height queries for delayed message ids

- protocol/daemons/pricefeed/client/types/price_feed_mutable_market_configs_test.go
- protocol/lib/json/json.go
- protocol/lib/json/json_test.go
- protocol/testutil/constants/prices.go
- protocol/testutil/keeper/prices.go
- protocol/testutil/prices/cli/util.go
- protocol/testutil/prices/market_param_price.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/perpetuals/module_test.go
- protocol/x/prices/keeper/market_param_test.go
- protocol/x/prices/keeper/market_test.go
- protocol/x/prices/module_test.go
- protocol/x/prices/types/errors.go
- protocol/x/prices/types/genesis_test.go
- protocol/x/prices/types/market_param.go
- protocol/x/prices/types/market_param_test.go
- protocol/x/prices/types/message_create_oracle_market.go
- protocol/x/prices/types/message_create_oracle_market_test.go
- protocol/x/rewards/keeper/keeper_test.go
- Implement `GetSigners` and `ValidateBasic`. 
- Added `ExchangeConfigJson` validation in `MarketParams.Validate` which is run in `MsgCreateOracleMarket.ValidateBasic`. This necessitated changes in a bunch of tests since previously tests are set up with empty `ExchangeConfigJson`.
> Implement `message_create_oracle_market` msg type

- protocol/x/prices/simulation/genesis.go
Fix broken sim test on `main` after https://github.com/dydxprotocol/v4-chain/pull/228 introduces stateless validations on exchange config json
> Fix simulation test - use empty, valid exchange config json

- protocol/go.mod
- protocol/go.sum
Use commit `65f7a2f25c18257600efb21de8bce090718692c8` on https://github.com/dydxprotocol/cometbft/commits/dydx-fork-v0.37.2
Incorporates a few consensus fixes backported to `dydx-fork-v0.37.2`.
Running stably in dev3 since[ 9/12 6pm](https://app.datadoghq.com/dashboard/wr9-2px-quy/v4?refresh_mode=paused&tpl_var_env%5B0%5D=dev3&from_ts=1694552808836&to_ts=1694571739000&live=false)
> Use latest cometbft fork

- indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
`address` is in query and not params.
Missed added middleware to validate the schema.
Update metric name.
> Fix compliance endpoint to use query params.

- protocol/lib/time/time.go
- protocol/lib/time/time_test.go
- protocol/x/bridge/types/genesis.go
1. Move `lib/time.go` to `lib/time/time.go`. I intend to move `time_provider.go` under this new dir in a future PR
2. Add unit tests for `lib/time/time.go`
> [DEC-2104] move `time.go` to `lib/time` and add unit tests

- protocol/x/prices/keeper/update_price.go
- protocol/x/prices/types/constants.go
Looks like 10s did not fully cover the time it takes for the pricefeed daemon to populate valid index prices. delay the escalation of these logs to error level for another 10s - that's 7-8 seconds of extra margin over the 12-13 seconds we're seeing in dev.
> [CORE-322] - Up time to 20s to account for extra 2-3s of errors we're seeing in dev.

- protocol/x/assets/keeper/asset.go
- protocol/x/assets/keeper/asset_test.go
- protocol/x/clob/keeper/liquidations_test.go
- protocol/x/clob/keeper/msg_server_place_order_test.go
- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/sending/keeper/transfer_test.go
- protocol/x/subaccounts/keeper/subaccount.go
- protocol/x/subaccounts/keeper/subaccount_test.go
- protocol/x/subaccounts/types/errors.go
- protocol/x/subaccounts/types/expected_keepers.go
- protocol/x/subaccounts/types/position_size.go
Per discussion with @BrendanChou, added logic to reject a `SubaccountUpdate` if *any* of any of the `update.PerpetualUpdate` involves a perpetual market with `0` oracle price.
> [CORE-494] Reject subaccount update if it's for a market with `0` oracle price.

- indexer/packages/postgres/__tests__/stores/subaccount-table.test.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20230918143243_update_subaccount_table_add_updated_at_index.ts
- indexer/packages/postgres/src/stores/subaccount-table.ts
- indexer/packages/postgres/src/types/query-types.ts
- update `findAll` for subaccounts table to search for subaccounts updated after a certain date
- add an index for `updatedAt`
Preparation for round table task to find all active subaccounts, which are ones that have been updated after a certain date.
> [IND-370] Add function to get subaccounts updated after date.

- indexer/services/comlink/__tests__/lib/compliance-check.test.ts
- indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
- indexer/services/comlink/src/controllers/api/v4/asset-positions-controller.ts
- indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
- indexer/services/comlink/src/controllers/api/v4/fills-controller.ts
- indexer/services/comlink/src/controllers/api/v4/historical-pnl-controller.ts
- indexer/services/comlink/src/controllers/api/v4/orders-controller.ts
- indexer/services/comlink/src/controllers/api/v4/perpetual-positions-controller.ts
- indexer/services/comlink/src/controllers/api/v4/transfers-controller.ts
- indexer/services/comlink/src/lib/compliance-check.ts
Middleware that extracts the `address` parameter from the request and checks if it is blocked according to the compliance data stored in the Indexer.
Does not make any new queries to compliance providers as a separate `roundtable` job will be querying for both new addresses and refreshing the compliance data for existing addresses.
See [spec](https://www.notion.so/dydx/OFAC-Checks-and-Geo-blocking-d4f749e8f4314fa1b258cd52033fb30d?pvs=4#2b58e5c947b54a1da1b86d9029e4478f) for more details.
> [IND-368] Add middleware to check compliance.

- protocol/lib/metrics/constants.go
- protocol/x/epochs/keeper/epoch_info.go
- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/sending/keeper/transfer.go
https://linear.app/dydx/issue/CORE-339/avoid-using-infinite-cardinality-labels-when-emitting-stats
> [CORE-339] Remove metric labels with infinite cardinality

- protocol/testing/genesis.sh
Since we don't use the oracle price for anything (because usdt index prices are used for adjustments on the daemon), let's go ahead and up this to 1k in order to reduce the frequency of USDT price change proposals, which cause the majority of price rejections.
See https://dydx-team.slack.com/archives/C05FTK5D8QG/p1695071966395639?thread_ts=1695067680.294969&cid=C05FTK5D8QG for context.
> Up USDT min change ppm to 1k

- protocol/lib/metrics/constants.go
- protocol/x/perpetuals/keeper/perpetual.go
Realize this [monitor](https://app.datadoghq.com/monitors/120602974/edit) cares about whether epoch number is `1` or not
> Use `IsEpochOne` instead of `IsEpochZero` 

- protocol/app/middleware/middleware.go
- protocol/app/middleware/middleware_test.go
Changes:
* swap to use test cases
* ensure that the middle ware logger is restored after the test finishes
> [DEC-2081] Audit app/middleware/middleware.go

- protocol/app/app.go
- protocol/app/app_test.go
- protocol/app/flags/flags.go
- protocol/app/flags/flags_test.go
- protocol/daemons/bridge/client/client.go
- protocol/daemons/bridge/client/client_test.go
- protocol/daemons/flags/flags.go
- protocol/daemons/flags/flags_test.go
- protocol/daemons/liquidation/client/client.go
- protocol/daemons/liquidation/client/client_test.go
- protocol/daemons/pricefeed/client/client.go
- protocol/daemons/pricefeed/client/client_integration_test.go
- protocol/daemons/pricefeed/client/client_test.go
- protocol/testutil/appoptions/app_options.go
- protocol/x/clob/client/cli/cancel_order_cli_test.go
- protocol/x/clob/client/cli/liquidations_cli_test.go
- protocol/x/clob/client/cli/place_order_cli_test.go
- protocol/x/prices/client/cli/prices_cli_test.go
As a P1 result from the prices outage, eliminate duplicate flag configuring gRPC address for daemons. Additionally, panic if the app starts with gRCP disabled, as for now it is required to operate. (The application would have panicked anyway if an expected daemon did not come up, but this way the error source is more clear.)
Tests:
- existing unit / integration
- make localnet-startd looks good
- built this image locally and modified container to have grpc disabled - causes panic.
- built this image locally and modified container to have grpc address of 10101 - protocol runs and netstat on the container shows port 10101 in use, 9090 not in use.
Sanity checks:
- vanilla build from main with grcp disabled in config causes daemon panics
- vanilla build from main with grpc address changed, …
> [CORE-535] - Remove duplicate daemon flag for grpc.address config.

- indexer/packages/postgres/__tests__/stores/compliance-data-table.test.ts
- indexer/packages/postgres/src/models/compliance-data-model.ts
- indexer/packages/postgres/src/stores/compliance-table.ts
- indexer/services/comlink/__tests__/controllers/api/v4/compliance-controller.test.ts
- indexer/services/comlink/src/caches/rate-limiters.ts
- indexer/services/comlink/src/config.ts
- indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
- indexer/services/comlink/src/controllers/api/v4/height-controller.ts
- indexer/services/comlink/src/lib/errors.ts
- indexer/services/comlink/src/lib/rate-limit.ts
Add logic to `/screen` endpoint to either retrieve the compliance data from the provider for new addresses / addresses with out-dated data or gets the data from the database.
Added rate-limiting logic directly into the controller as the custom logic depends on finding the compliance data in the database first.
Added `upsert` function for compliance data table.
> [IND-372] Add caching / rate-limiting logic to screen endpoint.

- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/prices/types/constants.go
Do not log error/increment stats if missing index price is observed during the first 20 blocks (price daemon initialization period)
[Context](https://dydx-team.slack.com/archives/C05AWN29RS4/p1695396499623849?thread_ts=1695391605.690219&cid=C05AWN29RS4)
Safe to backport - no application behavior change
> Height gate missing index price err log

- protocol/lib/error/log_contextualizer.go
- protocol/lib/error/logging.go
- protocol/lib/error/logging_test.go
- coverage was already 100%
- added more comments
- removed homecooked mock logger and replaced it with a generated mock class, then refactored test case to use expectations to validate logger calls.
- added an additinoal test case for logging plain errors.
> [DEC-2084] - `lib/error` audit refactors

- .github/mergify.yml
This rule will allow users to backport to the latest release branch.
> Add backport rule for mergify bot

- protocol/daemons/bridge/client/client.go
- protocol/daemons/server/types/bridge/bridge_event_manager.go
- protocol/daemons/server/types/bridge/bridge_event_manager_test.go
- protocol/lib/metrics/constants.go
- protocol/x/bridge/app_test.go
If recognized event ID is smaller than acknowledged event ID (see [here](https://github.com/dydxprotocol/v4-chain/pull/365/files#diff-1e30e65863b15e431d8c52fb682f4b60d4e80aab68dc1535a69af96f501bdf71R266-R272) for what can cause this), bridge server will throw an error like:
```
AddBridgeEvents: Event ID 2 is greater than the Next Id 0.
```
1st commit adds a test case that demonstrates the issue ([see error here](https://github.com/dydxprotocol/v4-chain/actions/runs/6303972749/job/17114348754?pr=365#step:5:133))
> allow bridge daemon to add events that have IDs greater than off-chain recognized event ID

- protocol/daemons/pricefeed/client/constants/static_exchange_market_config.go
- protocol/daemons/pricefeed/client/constants/static_exchange_market_config_test.go
- protocol/daemons/pricefeed/client/constants/testdata/ada_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/btc_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/dot_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/eth_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/sol_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/usdt_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/xlm_exchange_config.json
- protocol/daemons/pricefeed/client/constants/testdata/xrp_exchange_config.json
- protocol/testutil/pricefeed/exchangeserver.go
- protocol/x/prices/client/testutil/bitfinex.go
- protocol/x/prices/client/testutil/constants.go
As per [this conversation](https://dydx-team.slack.com/archives/C05FTK5D8QG/p1695415034712729?thread_ts=1695067680.294969&cid=C05FTK5D8QG). BinanceUS already removed for all pairs, Gate USDT-USD also already removed.
> [CORE-594] - Remove all bitfinex exchange symbols. Update Binance USDT ticker to 1 / USDCUSDT

- protocol/scripts/bech32_to_hex/bech32_to_hex.go
- protocol/scripts/bridge_events/bridge_events.go
Adding a script to convert a `bech32` address to a hexadecimal bytes representation.
Minor change: Each script should be in it's own folder so it can be in a `main` package (as I have not set up Cobra for these scripts)
https://stackoverflow.com/questions/27140130/having-multiple-main-functions-on-go
> add a script to output hex from bech32

- protocol/app/module/slashing.go
- protocol/app/msgs/app_injected_msgs.go
- protocol/app/process/acknowledge_bridges_test.go
- protocol/app/process/process_proposal_test.go
- protocol/lib/eth/util.go
- protocol/lib/eth/util_test.go
- protocol/testutil/bank/bank_helpers.go
- protocol/testutil/constants/bridge.go
- protocol/x/assets/keeper/asset.go
- protocol/x/assets/keeper/asset_test.go
- protocol/x/bridge/app_test.go
- protocol/x/bridge/keeper/complete_bridge_test.go
- protocol/x/bridge/keeper/msg_server_complete_bridge_test.go
- protocol/x/bridge/types/bridge_event_test.go
- protocol/x/clob/abci_test.go
- protocol/x/clob/keeper/deleveraging_test.go
- protocol/x/clob/keeper/liquidations_test.go
- protocol/x/clob/keeper/mev_test.go
- protocol/x/clob/keeper/process_operations_liquidations_test.go
- protocol/x/clob/keeper/process_operations_test.go
- protocol/x/delaymsg/keeper/dispatch_test.go
- protocol/x/rewards/keeper/keeper.go
- protocol/x/rewards/keeper/keeper_test.go
- protocol/x/subaccounts/keeper/transfer_test.go
- protocol/x/subaccounts/simulation/genesis.go
- protocol/x/subaccounts/simulation/genesis_test.go
- protocol/x/vest/keeper/keeper_test.go
This simplifies the upgrade to Cosmos 0.50.0.
See https://github.com/cosmos/cosmos-sdk/blob/3b509c187e1643757f5ef8a0b5ae3decca0c7719/types/math.go#L9 for the deprecation.
> [CORE-538] Swap to cosmossdk.io/math module since the package we are using has deprecated these functions and is removed on 0.50.

- Makefile
To avoid potential collisions caused by adding unnecessary things to python path such as `google.api`, we'll hack around the proto issue by fixing the import statements instead.
Also, add a comment documenting why we're doing these hacks.
> [CORE-549] Change the hack we're using to generate python protos

- indexer/packages/base/src/errors.ts
- indexer/packages/compliance/.env
- indexer/packages/compliance/__tests__/clients/elliptic-provider.test.ts
- indexer/packages/compliance/package.json
- indexer/packages/compliance/src/clients/elliptic-provider.ts
- indexer/packages/compliance/src/config.ts
- indexer/packages/compliance/src/index.ts
- indexer/packages/compliance/src/lib/error.ts
- indexer/packages/compliance/tsconfig.json
- indexer/pnpm-lock.yaml
- indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
- indexer/services/comlink/src/lib/errors.ts
Takes the logic from the v3 [Elliptic client](https://github.com/dydxprotocol/stacks/blob/master/src/clients/elliptic.ts) and put it into a `ComplianceClient` class.
Main changes:
- instead of returning `null` risk scores for errors, throw errors to indicate an address could not be queried from Elliptic
- remove logic around usd volume
> [IND-369] Add Elliptic compliance provider.

- protocol/app/ante_whitebox_test.go
- protocol/app/encoding.go
Minor clean-ups (mainly not shadowing a global variable).
> [DEC-2081] Audit ante.go and encoding.go

- protocol/testing/containertest/testnet.go
- protocol/testing/containertest/testnet_test.go
- Fixed `order.Sutbticks` to be multiple of `ClobPair.SubticksPerTick`
- Fixed a test error log
Current result:
```
code: 12
codespace: clob
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'Order subticks 10000 must be a multiple of the ClobPair''s SubticksPerTick
100000: MsgPlaceOrder is invalid'
timestamp: ""
tx: null
txhash: 0295FA11536837BC3794DED6F7B56F8AD7B035D3C26F2F19896A46D638B1F363l
```
> Small fix to container test

- .github/workflows/proto.yml
The swagger gen command is currently incorrectly pulling in the latest Cosmos / IBC protos to generate the swagger, instead of the protos depended on by the built binary.
> Remove swagger gen workflow.

- protocol/docker-compose.yml
- protocol/testing/snapshotting/Dockerfile.snapshot
- protocol/testing/snapshotting/snapshot.sh
- protocol/testing/start.sh
- protocol/testing/testnet-dev/Dockerfile
- protocol/testing/testnet-dev/dev.sh
- protocol/testing/testnet-local/Dockerfile
- protocol/testing/testnet-local/local.sh
- protocol/testing/testnet-staging/Dockerfile
- protocol/testing/testnet-staging/staging.sh
- Setup cosmovisor in all local, dev, staging images. They can still be run with the binary.
- Change the snapshotting image to use cosmovisor.
> Build images so they can be run with cosmovisor in addition to the binary directly

- protocol/Makefile
- protocol/docker-compose.yml
Gradually more and more people have been having the issue where docker compose is looking for `dydxprotocol-base` in docker hub when it exists locally already. Building outside of docker compose fixes this.
> Fix localnet docker issues

- protocol/app/upgrades/v0.3.0/upgrade.go
- protocol/x/perpetuals/keeper/perpetual.go
For reference, the old writer is [here](https://github.com/dydxprotocol/v4-chain/pull/279/files#diff-e08f57dcab4d145924734fc1d6be83f85c3db4eae51dcd3597d0145a720e6ffbL1362).
> Remove NumLiquidityTiersKey in upgrade handler

- protocol/x/clob/memclob/memclob.go
the `RemoveShortTermOrderTxBytes(order)` call panics if it cannot find the order hash in the map
> remove duplicate panic

- protocol/daemons/server/types/constants.go
Addressing issue in [this thread](https://dydx-team.slack.com/archives/C041FHN48G0/p1695840754499849).
> Double startup daemon grace period to 1 minute

- protocol/x/prices/keeper/util.go
- protocol/x/prices/keeper/util_test.go
math methods generally look fine in x/prices, with a few apparent exceptions. I added some comments here to show why those exceptions are actually fine. Also added a little extra test coverage for our `isCrossing*Price` methods. Confirmed on slack with Brendan that medianization rounding behavior [is fine](https://dydx-team.slack.com/archives/C03TDPD3MC4/p1695848350401879) for x/prices, also.
> [DEC-2070] - x/prices audit: add test cases to util, clarifying comments

- protocol/testing/snapshotting/snapshot.sh
- protocol/testing/testnet-dev/dev.sh
- protocol/testing/testnet-local/local.sh
- protocol/testing/testnet-staging/staging.sh
`cosmovisor init /bin/dydxprotocold` already adds a symlink in this location; there's no need to copy the binary each time. I verified this works by running the localnet.
> Stop including multiple copies of binary in images

- protocol/testutil/keeper/assets.go
- protocol/x/assets/genesis.go
- protocol/x/assets/keeper/asset.go
- protocol/x/assets/keeper/asset_test.go
- protocol/x/assets/keeper/grpc_query_asset.go
- protocol/x/assets/keeper/keeper.go
- protocol/x/assets/types/errors.go
- protocol/x/assets/types/genesis.go
- protocol/x/assets/types/genesis_test.go
- protocol/x/assets/types/keys.go
- protocol/x/clob/keeper/deleveraging.go
- protocol/x/clob/keeper/deleveraging_test.go
- protocol/x/clob/types/expected_keepers.go
- protocol/x/rewards/keeper/keeper.go
- protocol/x/rewards/types/expected_keepers.go
- protocol/x/subaccounts/keeper/subaccount_test.go
- protocol/x/subaccounts/keeper/transfer_test.go
- Drop `NumAsset` and consecutive asset ID requirement (similar to recent changes in `x/clob`, `x/perpetuals`, `x/prices`
- Reserve `assetId == 0` for USDC
> [DEC-2127] Asset Id refactoring

- protocol/app/app.go
- protocol/x/prices/keeper/market.go
- protocol/x/prices/keeper/market_test.go
- protocol/x/prices/keeper/update_price.go
The code change to cause daemon panics when daemons fail to respond in a timely fashion has led to an unintended effect: when genesis time is delayed after a node starts, the node will sleep, and the daemon monitoring service will cause a panic.  The root cause of this is unavailability of the cosmos gRPC service - daemons will hang when trying to establish a connection to this service and will never send calls to the daemon server.
This PR delays daemon / daemon service start until after the gRPC service is initilialized.
I implemented with a minimal change by adding a closure function that is called whenever gRPC routes are registered on the gRPC server. Open to other suggestions. This fixes the issue locally and all tests pass.
> [CORE-627] - Fix daemon panics by delaying daemon start until gRPC service is available

- protocol/lib/metrics/constants.go
- protocol/x/vest/keeper/keeper.go
This panic is highly unlikely and represents an unexpected error. Replace it with an emitted error metric + a log statement and continue so we don't cause liveness issue in the event of vesting transfer failure. Validator operators can alert on the metric and investigate based on the log statement.
> [DEC-2075] - Remove panic from ProcessVesting, called in BeginBlocker

- v4-proto-js/package.json
Package seems to be reverting to private every publish, so lets force it to public
> Force public for v4-proto-js

- protocol/scripts/genesis/prod_pregenesis.sh
- protocol/testing/genesis.sh
Prefer to have network-generic parameters live in `genesis.sh` so testing environments are as realistic as possible
> Move `consensus_params` to `genesis.sh` from `prod_genesis.sh`

- protocol/CHANGELOG.md
- protocol/daemons/pricefeed/client/price_function/binance/exchange_query_details.go
- protocol/daemons/pricefeed/client/price_function/binance/exchange_query_details_test.go
Use `data-api.binance.vision` instead of `data.binance.com`
https://binance-docs.github.io/apidocs/spot/en/#change-log:~:text=API%20Market%20data%20from%20data.binance.com%20can%20now%20be%20accessed%20from%20data%2Dapi.binance.vision.
Even though this technically can affect `PrepareProposal` and `ProcessProposal`, I would consider it non-breaking since prices from exchanges are already medianized and very similar to each other
Tested locally and in internal `funder` service
> Use new binance endpoint

- protocol/x/clob/keeper/liquidations.go
Fix a bug in the hotfix. The bug was with how the `deltaQuantums` value was calculated using the liquidation order that is no longer useful
N/A
> bugfix for hotfix: fix deltaQuantums calculation

- protocol/lib/metrics/constants.go
- protocol/x/clob/flags/flags.go
- protocol/x/clob/flags/flags_test.go
- protocol/x/clob/keeper/deleveraging.go
- protocol/x/clob/keeper/keeper.go
- protocol/x/clob/keeper/liquidations.go
- Add a commandline flag to control the number of subaccounts iterated per deleveraging event.
> add flag to limit the number of subaccounts iterated for deleveraging

- protocol/testutil/keeper/prices.go
- protocol/x/prices/genesis.go
- protocol/x/prices/keeper/indexer.go
- protocol/x/prices/keeper/market_price.go
- protocol/x/prices/module.go
* Rename `GenerateMarketPriceUpdateEvents` to `GenerateMarketPriceUpdateIndexerEvents`
* Remove telemetry from `EndBlocker` since there's no logic there and there's no need to measure telemetry
N/A
> [CORE-658] Remove telemetry from `x/prices/EndBlocker` and rename indexer event method

- protocol/x/bridge/types/msg_update_event_params.go
- protocol/x/bridge/types/msg_update_event_params_test.go
- protocol/x/bridge/types/msg_update_propose_params.go
- protocol/x/bridge/types/msg_update_propose_params_test.go
- protocol/x/bridge/types/msg_update_safety_params.go
- protocol/x/bridge/types/msg_update_safety_params_test.go
1. add `Params` validation to bridge governance messages
2. add unit test on non-empty authority validation in bridge governance messages
> [CORE-652] add params validation to bridge message validation and add non-empty authority unit test

- indexer/CHANGELOG.md
- indexer/services/socks/__tests__/lib/subscriptions.test.ts
- indexer/services/socks/src/lib/subscription.ts
Bugfix. The initial payload for the `v4_subaccounts` websocket channel should contain all active (open or untriggered) orders, but currently doesn't contain any open (`BEST_EFFORT_OPENED`) short-term orders.
Unit test added to ensure the initial payload URL is updated correctly.
Tested in a dev environment for verify the actual behavior.
> Return short-term orders in initial payload for v4_subaccounts channel.

- protocol/x/blocktime/keeper/keeper.go
- protocol/x/blocktime/types/keys.go
These keys were missed in the original pass for standardizing keys.
> [CORE-659] Standardize keys for x/blocktime

- protocol/x/prices/genesis_test.go
- `ExportGenesis`was already tested, but I wrote a more comprehensive test that also validates keeper state after genesis import before exporting.
- Added panic test for invalid genesis state.
> [CORE-672] - x/prices genesis test refactors

- protocol/x/bridge/app_test.go
- protocol/x/bridge/keeper/acknowledge_bridges.go
- protocol/x/bridge/keeper/acknowledge_bridges_test.go
- protocol/x/bridge/keeper/bridge_event.go
- protocol/x/bridge/keeper/bridge_event_info.go
- protocol/x/bridge/keeper/complete_bridge.go
- protocol/x/bridge/keeper/complete_bridge_test.go
- protocol/x/bridge/keeper/grpc_query_test.go
1. add more test cases and comments to bridge module, specifically
* delay bridge completion by 0 blocks
* more failure cases of bridge tx rejection due to mismatching bridge event content
* delay msg error is propagated `AcknowledgeBridges`
* completing a bridge whose coin amount is negative
2. do not panic in `AcknowledgeBridges` if it fails to delay a complete bridge message
3. do not measure latency if there's no bridge event to acknowledge or if bridging is disabled
> [CORE-652] add more test cases and comments to bridge module

- protocol/.golangci.yml
- protocol/daemons/pricefeed/client/price_fetcher/price_fetcher.go
- protocol/lib/ante/disallow_msg_test.go
- protocol/lib/ante/internal_msg_test.go
- protocol/testutil/app/app.go
- protocol/x/clob/keeper/msg_server_update_clob_pair_test.go
- protocol/x/clob/keeper/uncommitted_stateful_order_state.go
- protocol/x/clob/memclob/memclob_get_premium_price_test.go
- protocol/x/clob/types/quantums.go
- protocol/x/feetiers/keeper/keeper.go
- protocol/x/perpetuals/client/cli/query_perpetual_test.go
- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/rewards/keeper/keeper.go
- protocol/x/stats/types/errors.go
- protocol/x/subaccounts/keeper/transfer_test.go
- protocol/x/subaccounts/simulation/genesis.go
- Add the `misspell` linter to `golangci-lint`.
- Use the linter to automatically fix typos
N/A
> Add `misspell` to linter. Fix common typos.

- .github/workflows/proto.yml
Proto gen workflow is broken because the old proto-builder image doesn't have go 1.21. This updated image have it.
N/A
> Update cosmos/proto-builder image to 14.0

- protocol/app/process/expected_keepers.go
- protocol/app/process/process_proposal.go
- protocol/mocks/PricesKeeper.go
- protocol/x/prices/keeper/smoothed_price.go
- protocol/x/prices/keeper/smoothed_price_test.go
- protocol/x/prices/types/types.go
Update our price smoothing logic to not terminate early in case of error, but retain errors and continue attempting updates until all markets have been visited.
Adding testing for this behavioral change required a modification to the keeper's interface to pass in the interpolator.
I also changed the iteration pattern to be deterministic for the sake of generating consistent error messages and also ensuring that unit tests are testing the intended conditions.
Additional unit tests to confirm errors.Join behavior and continuing to execute updates after errors.
> [CORE-568] - UpdateSmoothedPrices continues to update after error

- protocol/x/delaymsg/keeper/msg_server_test.go
> [CORE-648] fix error string in delaymsg unit test

- protocol/x/clob/keeper/clob_pair.go
- protocol/x/clob/keeper/clob_pair_test.go
- protocol/x/clob/keeper/msg_server_create_clob_pair.go
- protocol/x/clob/keeper/msg_server_update_block_rate_limit_config.go
- protocol/x/clob/keeper/msg_server_update_clob_pair.go
- protocol/x/clob/keeper/msg_server_update_clob_pair_test.go
- protocol/x/clob/keeper/msg_server_update_equity_tier_limit_config.go
- protocol/x/clob/keeper/msg_server_update_liquidations_config.go
cosmos sdk currently doesn't recover from a governance message execution failure (until v4-chain upgrades to cosmos 0.50 I believe).
> [CORE-650] clob governance message handlers: do not panic or emit metric on deliverTx

- protocol/testutil/ibc/ibc.go
- protocol/testutil/ibc/ibc_test.go
Move ibc util function `DenomTraceToIBCDenom` testutil package
N/A
> [DEC-2096] IBC audit: move ibc util function to testutil package

- protocol/x/prices/keeper/validate_market_price_updates.go
Map with bool values is less efficient as a set implementation in go than map of empty structs. See [this article](https://itnext.io/set-in-go-map-bool-and-map-struct-performance-comparison-5315b4b107b).
This one is a pretty big nit because the set is small and this change is unlikely to have a large performance impact, but it makes our codebase more canonical.
> [CORE-658] - Migrate set type to map with empty struct value

- protocol/x/clob/keeper/mev.go
> [DEC-2145] Audit: Explicitly panic when insurance fund delta is not int64

- protocol/app/process/market_prices_test.go
- protocol/app/process/proposed_operations_test.go
- protocol/testutil/constants/operations.go
Add tests for `app/process/proposed_operations.go`
Minor fixes to other tests which were calling `Validate` twice needlessly.
New tests, no changes to existing code.
> [DEC-2081] Add tests for app/process/proposed_operations.go

- protocol/lib/metrics/constants.go
- protocol/x/clob/abci.go
Remove duplicate CLOB `PrepareCheckState` latency metric. Currently using the `commit` metric instead in datadog [here](https://app.datadoghq.com/dashboard/fbc-gkh-ywa/xclob?refresh_mode=paused&from_ts=1696875609087&to_ts=1697480409087&live=false&tile_focus=8842746538142110), which is measured in the codebase [here](https://github.com/dydxprotocol/v4-chain/blob/9338c8cfc940ff71260d34c023413d6e39110ede/protocol/x/clob/module.go#L193).
N/A.
> [refactor] Remove duplicate CLOB `PrepareCheckState` latency metric

- protocol/x/clob/keeper/deleveraging.go
- protocol/x/clob/keeper/liquidations.go
- technically it's possible that the position is closed before deleveraging is attempted. so this PR is meant to address that extreme edge case.
> fix edge case where position is closed before deleveraging

- indexer/packages/postgres/src/types/websocket-message-types.ts
- indexer/services/ender/__tests__/lib/candles-generator.test.ts
- indexer/services/ender/src/lib/candles-generator.ts
- indexer/services/socks/__tests__/helpers/from-kafka-helpers.test.ts
- indexer/services/socks/src/helpers/from-kafka-helpers.ts
- indexer/services/socks/src/types.ts
- Remove fields in socks that weren't being sent to users, and sent candle resolutions through websockets, because previously it was expected that candle resolution was sent
unit tests
> [IND-288]: Remove unused socks fields and add candle resolutions for websockets

- protocol/lib/metrics/constants.go
- protocol/x/clob/keeper/msg_server_cancel_orders.go
- protocol/x/clob/keeper/msg_server_cancel_orders_test.go
- protocol/x/clob/keeper/msg_server_place_order.go
- protocol/x/clob/keeper/msg_server_place_order_test.go
This PR updates MsgPlaceOrder DeliverTx `defer` logic to log errors due to failed collateralization checks as `info` instead of `error`. Errors should be actionable, and it is a legitimate possibility that this error occurs due to collateralization of an account changing between CheckTx and DeliverTx due to matches in the operations queue processed before the placement in DeliverTx. 
Slack thread: https://dydx-team.slack.com/archives/C03SLFHC3L7/p1697479226938579?thread_ts=1697463950.962099&cid=C03SLFHC3L7
> Conditionally info log in PlaceOrder DeliverTx if collat check fails

- indexer/services/ender/__tests__/caches/block-cache.test.ts
- indexer/services/ender/src/caches/block-cache.ts
> Prevent blocks from being skipped by ender

- protocol/app/app.go
- protocol/app/simulation_test.go
- protocol/testing/e2e/gov/add_new_market_test.go
- protocol/testing/e2e/gov/bridge_test.go
- protocol/testing/e2e/gov/sending_test.go
- protocol/testing/e2e/gov/stats_test.go
- protocol/testutil/app/app.go
- protocol/testutil/network/network.go
- protocol/x/clob/e2e/equity_tier_limit_test.go
- protocol/x/clob/e2e/long_term_orders_test.go
- protocol/x/clob/e2e/order_matches_test.go
- protocol/x/delaymsg/keeper/dispatch_test.go
- protocol/x/sending/app_test.go
This hook is invoked on [application shutdown](https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/server/start.go#L256) so we can re-use it within our tests. Note that there is an [open issue against Cosmos SDK](https://github.com/cosmos/cosmos-sdk/issues/18151) about removing the `Close` call that is added for `simapp` and `Network` tests to function.
Existing tests.
> [CORE-29, CORE-682] Add Close() shutdown hook to Application which is invoked in simapp, Network, and e2e tests.

- protocol/scripts/genesis/sample_pregenesis.json
- protocol/testing/genesis.sh
update the genesis.sh file to reflect recommendation on the base position notional values for midcap and long tail liquidity tiers https://dydx-team.slack.com/archives/C04BNGM82HM/p1697493986734849?thread_ts=1697487833.033209&cid=C04BNGM82HM
same changes as in this pr but verified commit https://github.com/dydxprotocol/v4-chain/pull/638
> update base position notional in genesis.sh

- protocol/testutil/app/app.go
- protocol/x/bridge/app_test.go
- protocol/x/stats/keeper/keeper_test.go
Discussed offline with @lcwik to fix the blocktime behavior of `AdvanceToBlock` function. Previously comment indicates that `options.BlockTime` is only for the requested (latest) block, but the implementation actually applies `options.BlockTime` to the first advanced block.
Fixed a few e2e tests affected by this behavior change. All other e2e tests still passing
> Fix `AdvanceToBlock` blocktime behavior

- protocol/daemons/pricefeed/client/client_integration_test.go
`expectPricesWithTimeout` was not properly checking for equality of all expected prices. Updated the logic and fixed an incorrectly set price for USDT conversions. 
Validated all test output for the file was terminating as expected with print statements.
> [CORE-686] - Pricefeed integration tests bugfix

- protocol/app/module_accounts.go
- protocol/app/module_accounts_test.go
Add `x/delaymsg` as a module accounts to `maccPerms`, the list of module accounts passed to the bank module. Also added unit test that checks the address of `delaymsg` module account. This came up during audit of delay message authority. 
Note: `delaymsg` module account doesn’t really “exist in state” in the sense that it does not exist as an entry under the x/bank or x/auth state.
The only effect of this PR is that the authKeeper/bankKeeper will now also has delaymsg as a module account (in memory object) , but since it has nil permissions, is not one of the blockedModuleAccounts , so this PR is effectively backwards compatible. However we don’t need to backport to v1.x, and the main purpose of this PR is to document the address of  delaymsg
N/A
> Add delaymsg module as a module account

- protocol/scripts/bridge_events/bridge_events.go
command run:
`go run scripts/bridge_events/bridge_events.go -toblock 4179719`
* Next ID is expected to be 1 as there's only one event up to block 4179719 
output:
```
Total amount bridged: 123
Remaining bridge module account balance: 999999999999999999999999877
"bridge.event_params": {
"denom": "adv4tnt",
"eth_chain_id": 11155111,
"eth_address": "0xcca9D5f0a3c58b6f02BD0985fC7F9420EA24C1f0"
}
"bridge.acknowledged_event_info": {
"next_id": 1,
"eth_block_height": 4179719
}
"bank.balances": [
{
"address": "dydx1zg69v7yszg69v7yszg69v7yszg69v7ysuz0wqr",
"coins": [
{
"amount": "123",
"denom": "adv4tnt"
}
]
}
]
```
> set next id in bridge events script to event id + 1

- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/prices/keeper/update_price.go
Change log messages for missing index prices to contain filterable marketId field. This way we can filter out errors that are due to the TestExchange / test currency, which does not run with the regular flow and occasionally causes errors not worth debugging / fixing.
See [this slack thread](https://dydx-team.slack.com/archives/C05AWN29RS4/p1697742253357799?thread_ts=1697739433.258809&cid=C05AWN29RS4).
> Change log messages for missing index prices to contain filterable marketId field

- protocol/x/clob/e2e/equity_tier_limit_test.go
- protocol/x/clob/keeper/equity_tier_limit.go
- protocol/x/clob/keeper/stateful_order_state.go
- protocol/x/clob/keeper/untriggered_conditional_orders.go
- protocol/x/clob/keeper/untriggered_conditional_orders_test.go
- protocol/x/clob/types/keys.go
- protocol/x/clob/types/keys_test.go
Remove counting of untriggered conditional orders since they are already in the subaccount order state count.
The change to the error message contains the actual count which was 2 in the case of the conditional order and not 1 showing the double counting.
> [CLO-987] Subaccount equity tier count was double counting conditional orders.

- protocol/scripts/genesis/prod_pregenesis.sh
- protocol/scripts/genesis/sample_pregenesis.json
- protocol/testing/genesis.sh
- protocol/testing/testnet-external/pregenesis.sh
* Sets the `gov.params.min_initial_deposit_ratio` to 0.2 (=20%) to avoid gov proposal spamming.
* Run `make update-sample-pregenesis`
N/A
> [DEC-2155] Set `gov.params.min_initial_deposit_ratio` to 0.2 to avoid spamming

- protocol/x/subaccounts/keeper/subaccount.go
- protocol/x/subaccounts/keeper/subaccount_helper.go
- protocol/x/subaccounts/types/subaccount.go
- protocol/x/subaccounts/types/subaccount_test.go
Remove errors from subaccounts keeper functions that don't return errors.
This is part of a larger subaccounts keeper refactor to simplify the code by removing returned errors when invariants are broken, and instead panicing earlier.
> [refactor] Remove errors from subaccounts keeper functions that don't return errors

- indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-placement-handler.test.ts
- indexer/services/ender/src/handlers/stateful-order/stateful-order-placement-handler.ts
- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/__tests__/helpers/websocket-helpers.ts
- indexer/services/vulcan/__tests__/lib/send-message-helper.test.ts
- indexer/services/vulcan/src/config.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
- indexer/services/vulcan/src/handlers/order-remove-handler.ts
- indexer/services/vulcan/src/handlers/order-update-handler.ts
- indexer/services/vulcan/src/index.ts
- indexer/services/vulcan/src/lib/send-message-helper.ts
Fixes issue found in testing #683 , where `ender` does not find the cached update. There's a race condition where `ender` processes a block before `vulcan` caches the order update. Moved re-queuing logic to `vulcan` to fix the issue as the order update will either be cached beforethe order place is received, or the order update will be processed after the order place is received.
Other updates:
- remove re-queuing of order updates from `ender`
- update `vulcan` to send both keys and values in Kafka messages
Unit tested, and tested on `dev`.
> [IND-402] Have vulcan re-queue cached order updates instead of ender.

- protocol/testutil/constants/bridge.go
- protocol/x/bridge/app_test.go
- protocol/x/delaymsg/keeper/dispatch.go
- protocol/x/delaymsg/types/keys.go
- protocol/x/delaymsg/types/logs.go
- Explicitly log out message content and typeurl when message execution fails during dispatching. Action item from [here](https://dydx-team.slack.com/archives/C05A2JZRZ8D/p1698098164646319?thread_ts=1698095898.635139&cid=C05A2JZRZ8D)
- Also add e2e test case where delayed MsgCompleteBridge fails to execute
Added e2e test where a BridgeEvent contains `0adv4tnt` transfer. The error log shows up as following:
```
E[2023-10-23|20:23:32.382] failed to execute delayed message            module=x/delaymsg id=1 error="0adv4tnt: invalid coins" message_content="authority:\"dydx1mkkvp26dngu6n8rmalaxyp3gwkjuzztq5zx6tr\" event:<coin:<denom:\"adv4tnt\" amount:\"0\" > address:\"dydx199tqg4wdlnu4qjlxchpd7seg454937hjrknju4\" > " message_type_url=/dydxprotocol.bridge.MsgCompleteBridge
```
> [CORE-708] Explicitly log out delayed message when execution fails

- protocol/app/ante/gas_test.go
- protocol/app/prepare/full_node_prepare_proposal_test.go
- protocol/testutil/app/app.go
- protocol/x/clob/e2e/app_test.go
- protocol/x/clob/e2e/long_term_orders_test.go
- protocol/x/clob/e2e/short_term_orders_test.go
- protocol/x/rewards/keeper/keeper_test.go
- protocol/x/sending/app_test.go
Remove Reset method and swap to appOptions/baseAppOptions being explicitly set instead of an appCreatorFn
This will simplify creating e2e test framework that better tests non-determinism/flags/... since the e2e test framework will want to control how the App instance is created.
Update existing tests to remove/change usage.
> [CLOB-930] Remove Reset method and swap to appOptions/baseAppOptions being explicitly set instead of an appCreatorFn

- protocol/daemons/pricefeed/metrics/market_pairs.go
- protocol/daemons/pricefeed/metrics/market_pairs_test.go
- protocol/daemons/pricefeed/metrics/metrics_test.go
When getting market id labels, always return the printed market id if the pair string is not available.
> [CORE-711] Always log market id when pair information is missing.

- protocol/testing/e2e/funding/funding_e2e_test.go
- protocol/testutil/app/app.go
- protocol/testutil/app/block_advancement.go
- protocol/testutil/app/order.go
- protocol/testutil/clob/order.go
- protocol/testutil/perpetuals/perpetuals.go
- protocol/testutil/perpetuals/perpetuals_test.go
- protocol/testutil/pricefeed/index_price.go
- protocol/testutil/prices/market_param_price.go
- protocol/testutil/prices/market_param_price_test.go
Added an funding e2e test that can be built upon in the future. Current behavior tested:
- Set up orders on the book
- Advance to start of full `funding-tick` period
- Measure a full `60 min` `funding-tick` period and check expected funding samples and resulting `fundingIndex`. 
> [CORE-704] Initial E2E testing framework for funding

- protocol/x/clob/keeper/liquidations.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/memclob/memclob.go
Small `PrepareCheckState` fixes from audit (nothing major that needs to be backported to the release).
> Initial `PrepareCheckState` audit

- indexer/packages/v4-protos/src/codegen/dydxprotocol/perpetuals/query.lcd.ts
- indexer/packages/v4-protos/src/codegen/dydxprotocol/perpetuals/query.rpc.Query.ts
- indexer/packages/v4-protos/src/codegen/dydxprotocol/perpetuals/query.ts
- proto/dydxprotocol/perpetuals/query.proto
- protocol/x/perpetuals/client/cli/query.go
- protocol/x/perpetuals/client/cli/query_params.go
- protocol/x/perpetuals/client/cli/query_params_test.go
- protocol/x/perpetuals/client/cli/query_premiums.go
- protocol/x/perpetuals/client/cli/query_premiums_test.go
- protocol/x/perpetuals/keeper/grpc_query_params.go
- protocol/x/perpetuals/keeper/grpc_query_params_test.go
- protocol/x/perpetuals/keeper/grpc_query_premiums.go
- protocol/x/perpetuals/keeper/grpc_query_premiums_test.go
- protocol/x/perpetuals/module_test.go
- protocol/x/perpetuals/types/query.pb.go
- protocol/x/perpetuals/types/query.pb.gw.go
Add gRPC and cli query commands to access perpetuals state.
Added cli, qRPC tests.
> [CORE-695] - add queries for x/perpetuals state

- protocol/daemons/pricefeed/client/price_fetcher/price_fetcher.go
- protocol/lib/metrics/constants.go
Track availability of market symbols in each exchange for alerting purposes.
Existing tests, this is a telemetry change.
> [CORE-354] - Add tracking for market availability in order to alert in datadog

- protocol/app/ante/gas_test.go
- protocol/app/app_test.go
- protocol/app/prepare/full_node_prepare_proposal_test.go
- protocol/cmd/dydxprotocold/cmd/config.go
- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/go.mod
- protocol/go.sum
- protocol/testutil/app/app.go
- protocol/x/clob/e2e/order_removal_test.go
- protocol/x/sending/app_test.go
Extend the e2e test framework to start the cosmos app using cmd.
This works towards enabling and passing in flags for flag based testing. This also works towards enabling daemons on e2e app start-up once the daemons can be cleaned up. This relies on https://github.com/dydxprotocol/cosmos-sdk/pull/29
Existing tests updated and pass.
> [CLOB-930, CORE-29] Extend the e2e test framework to start the cosmos app using cmd.

- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
Prevent order placement events that do no place or replace on book and are `BEST_EFFORT_OPENED` from sending subaccount update messages
Unit tests
> [IND-171]: Do not send subaccount websocket message for unplaced and unreplaced BEST_EFFORT_OPENED orders

- protocol/app/app.go
- protocol/app/simulation_test.go
- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/testing/e2e/funding/funding_e2e_test.go
- protocol/testutil/app/app.go
- protocol/testutil/network/network.go
- protocol/x/bridge/app_test.go
- protocol/x/clob/e2e/equity_tier_limit_test.go
- protocol/x/clob/e2e/rate_limit_test.go
- protocol/x/clob/keeper/order_cancellation_test.go
- protocol/x/clob/keeper/orders_test.go
Add 3 additional validator invariant checkers (PR) for almost all existing e2e tests:
* parallelApp is responsible for seeing all CheckTx requests, block proposals, blocks, and RecheckTx requests. This allows it to detect state differences due to inconsistent in-memory structures (for example iteration order in maps).
* noCheckTxApp is responsible for seeing all block proposals and blocks. This allows it to simulate a validator that never received any of the CheckTx requests and that it will still accept blocks and arrive at the same state hash.
* crashingApp is responsible for restarting before processing a block and sees all CheckTx requests, block proposals, and blocks. This allows it to check that in memory state can be restored successfully on application restart and that it will …
> [CLOB-930] Run three other instances of the application during e2e tests that check for non-determinism

- protocol/scripts/iaviewer/iaviewer.go
- protocol/scripts/iaviewer/unmarshaller.go
- Migrate cli to use cobra
- Add `data-all` command to list iavl tree for all modules
- Unmarshal proto values and output human readable strings if they are in the registry
- Manually tried all commands on a db from localnet
> Make iaviewer usage more human friendly

- indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
- indexer/services/comlink/src/controllers/api/v4/asset-positions-controller.ts
- indexer/services/comlink/src/controllers/api/v4/candles-controller.ts
- indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
- indexer/services/comlink/src/controllers/api/v4/fills-controller.ts
- indexer/services/comlink/src/controllers/api/v4/height-controller.ts
- indexer/services/comlink/src/controllers/api/v4/historical-funding-controller.ts
- indexer/services/comlink/src/controllers/api/v4/historical-pnl-controller.ts
- indexer/services/comlink/src/controllers/api/v4/orderbook-controller.ts
- indexer/services/comlink/src/controllers/api/v4/orders-controller.ts
- indexer/services/comlink/src/controllers/api/v4/perpetual-markets-controller.ts
- indexer/services/comlink/src/controllers/api/v4/perpetual-positions-controller.ts
- indexer/services/comlink/src/controllers/api/v4/sparklines-controller.ts
- indexer/services/comlink/src/controllers/api/v4/trades-controller.ts
- indexer/services/comlink/src/controllers/api/v4/transfers-controller.ts
- indexer/services/comlink/src/lib/helpers.ts
Log request in comlink in case of errors
Verifies that the query and parameters correct print out
> [IND-458]: In case of errors in comlink log request

- indexer/docker-compose-local-deployment.yml
- indexer/docker-compose.yml
Add context for docker-compose builds since it is necessary for newer versions of Docker.
Otherwise docker-compose up fails with an error saying build context is required.
Tested locally + existing integration tests
> Add context for docker-compose builds since it is necessary for newer versions of Docker.

- protocol/x/perpetuals/e2e/authorities_test.go
- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/perpetuals/types/errors.go
- protocol/x/perpetuals/types/genesis_test.go
- protocol/x/perpetuals/types/params.go
- protocol/x/perpetuals/types/params_test.go
Another round of audit changes for `x/perpetuals`. Added an additional validation for  `MinNumVotesPerSample` (state incompatible). 
Otherwise, mostly code sanitation and unit tests.
Updated tests
> [CORE-664] Perpetual audit: add validation on `MinNumVotesPerSample`, add unit tests

- indexer/packages/postgres/src/models/fill-model.ts
- indexer/packages/postgres/src/models/order-model.ts
- indexer/services/ender/__tests__/handlers/order-fills/liquidation-handler.test.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/handlers/order-fills/liquidation-handler.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/scripts/dydx_liquidation_fill_handler_per_order.sql
[IND-465] Add support for liquidation handler to use a single SQL function.
Also fix fill and order models since clientMetadata is a nullable field.
New tests.
> [IND-465] Add support for liquidation handler to use a single SQL function.  Also fix fill and order models since clientMetadata is a nullable field.

- indexer/packages/postgres/src/constants.ts
- indexer/packages/postgres/src/index.ts
- indexer/packages/postgres/src/loops/market-refresher.ts
- indexer/packages/postgres/src/models/market-model.ts
- indexer/services/ender/__tests__/handlers/markets/market-create-handler.test.ts
- indexer/services/ender/__tests__/lib/sync-handlers.test.ts
- indexer/services/ender/__tests__/scripts/scripts.test.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/handlers/markets/market-create-handler.ts
- indexer/services/ender/src/handlers/order-fills/liquidation-handler.ts
- indexer/services/ender/src/handlers/order-fills/order-handler.ts
- indexer/services/ender/src/handlers/subaccount-update-handler.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/lib/on-message.ts
- indexer/services/ender/src/scripts/dydx_market_create_handler.sql
[IND-467] Push ender market create logic to use a single sql function
> [IND-467] Push ender market create logic to use a single sql function

- indexer/services/ender/__tests__/handlers/markets/market-modify-handler.test.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/handlers/markets/market-modify-handler.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/scripts/dydx_market_modify_handler.sql
[IND-468] Push ender market modify logic to use a single SQL function
> [IND-468] Push ender market modify logic to use a single SQL function

- indexer/packages/postgres/src/constants.ts
- indexer/packages/postgres/src/index.ts
- indexer/packages/postgres/src/models/asset-model.ts
- indexer/services/ender/__tests__/handlers/asset-handler.test.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/handlers/asset-handler.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/scripts/dydx_asset_create_handler.sql
[IND-470] Update asset create handler to use SQL function.
> [IND-470] Update asset create handler to use SQL function.

- protocol/app/simulation_test.go
Make the test run 9 instead of 15 apps. Maybe excessive memory usage is causing github to shut these down? I ran CI on this quite a few times and it seems to not flake anymore.
Run CI a bunch of times
> Deflake test-sim-nondeterminism 

- indexer/packages/redis/__tests__/caches/canceled-orders-cache.test.ts
- indexer/packages/redis/src/caches/canceled-orders-cache.ts
- indexer/packages/redis/src/types.ts
- indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
- indexer/services/ender/src/handlers/order-fills/abstract-order-fill-handler.ts
- indexer/services/ender/src/handlers/order-fills/liquidation-handler.ts
- indexer/services/ender/src/handlers/order-fills/order-handler.ts
- indexer/services/ender/src/scripts/dydx_get_order_status.sql
- indexer/services/ender/src/scripts/dydx_liquidation_fill_handler_per_order.sql
- indexer/services/ender/src/scripts/dydx_order_fill_handler_per_order.sql
- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/__tests__/handlers/order-remove-handler.test.ts
- indexer/services/vulcan/__tests__/helpers/helpers.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
- indexer/services/vulcan/src/handlers/order-remove-handler.ts
- Convert CanceledOrdersCache to have a cache for `BEST_EFFORT_CANCELED` and `CANCELED`
- Update vulcan `remove-order-handler.ts` to update CanceledOrdersCache with status
- Update ender's `abstract-order-fill-handler.ts` to update short term GTT and short term post-only orders to the correct status
- Fix bug in ender's `abstract-order-fill-handler.ts` to never set stateful orders to `BEST_EFFORT_CANCELED` because stateful orders are never added to the CanceledOrdersCache in vulcan, and because we never send `BEST_EFFORT_CANCELED` for stateful orders
Tested in unit tests, verified previous behavior in dev
> [IND-450]: Prevent orders transitioning from canceled to best effort canceled

- protocol/x/clob/keeper/orders.go
`placeOrder` was only called in `func (k Keeper) PlaceShortTermOrder(`.
Combine these functions, as there is no point in having a thin wrapper function.
Functionally should have no change in behavior.
Testing: Looking for tests to pass.
> Small short term place order refactor

- protocol/x/perpetuals/client/cli/query_premiums_test.go
See [bug report](https://dydx-team.slack.com/archives/GTGEVSCUU/p1699386424785019)
The flakiness seems to depend on how long the test takes to run, but I was unable to reproduce the unexpected (NumPremiums occasionally nonzero) by waiting for a specific block ,and I did not want to extend the test case runtime by waiting for a block with a specific timeout. So here, I de-tune query response check to reduce test flakes.
> Fix flaky TestQueryPremiumSamples test

- indexer/packages/postgres/src/lib/order-translations.ts
- indexer/services/ender/__tests__/handlers/stateful-order/conditional-order-placement-handler.test.ts
- indexer/services/ender/__tests__/handlers/stateful-order/conditional-order-triggered-handler.test.ts
- indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-placement-handler.test.ts
- indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-removal-handler.test.ts
- indexer/services/ender/__tests__/scripts/scripts.test.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/handlers/abstract-stateful-order-handler.ts
- indexer/services/ender/src/handlers/stateful-order/conditional-order-placement-handler.ts
- indexer/services/ender/src/handlers/stateful-order/conditional-order-triggered-handler.ts
- indexer/services/ender/src/handlers/stateful-order/stateful-order-placement-handler.ts
- indexer/services/ender/src/handlers/stateful-order/stateful-order-removal-handler.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/scripts/dydx_from_protocol_order_side.sql
- indexer/services/ender/src/scripts/dydx_protocol_condition_type_to_order_type.sql
- indexer/services/ender/src/scripts/dydx_stateful_order_handler.sql
[IND-477, IND-478, IND-479, IND-480] Update all stateful order handlers to use a SQL function to perform reads & updates.
Updated existing tests and added some new ones.
> [IND-477, IND-478, IND-479, IND-480] Update all stateful order handlers to use a SQL function to perform reads & updates.

- protocol/testutil/constants/orders.go
- protocol/testutil/constants/subaccounts.go
- protocol/x/clob/e2e/liquidation_deleveraging_test.go
- E2E tests to make sure liquidations respect position block limits and subaccount block limits.
> [CLOB-858] Add liquidation tests with different block limits

- indexer/services/roundtable/src/config.ts
External and dev indexers have no need to create athena snapshots. I have enabled athena snapshots for our staging, public-testnet, and mainnet.
was not tested
> Default athena snapshots to be off

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/__tests__/helpers/mock-generators.ts
- indexer/packages/postgres/__tests__/stores/perpetual-position-table.test.ts
- indexer/packages/postgres/src/stores/perpetual-position-table.ts
- indexer/services/ender/__tests__/handlers/order-fills/liquidation-handler.test.ts
- indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
- indexer/services/ender/src/scripts/dydx_liquidation_fill_handler_per_order.sql
- indexer/services/ender/src/scripts/dydx_update_perpetual_position_aggregate_fields.sql
Change existing queries to `perpetual_positions` to order by `openEventId` rather than `createdAtHeight` and change the corresponding SQL statement in Ender to also use `opentEventId`
Unit tests
> [IND-485]: Query for PerpetualPositions by openEventId

- indexer/packages/kafka/src/constants.ts
- indexer/packages/postgres/src/types/websocket-message-types.ts
- indexer/services/comlink/public/api-documentation.md
- indexer/services/comlink/public/swagger.json
- indexer/services/comlink/public/websocket-documentation.md
- indexer/services/comlink/src/request-helpers/request-transformer.ts
- indexer/services/comlink/src/types.ts
- indexer/services/ender/__tests__/helpers/constants.ts
- indexer/services/ender/__tests__/helpers/indexer-proto-helpers.ts
- indexer/services/ender/__tests__/lib/kafka-publisher.test.ts
- indexer/services/ender/src/handlers/order-fills/abstract-order-fill-handler.ts
- indexer/services/ender/src/helpers/kafka-helper.ts
consolidate `/v4/trades` API endpoint response and websocket message.
unit tested.
> [IND-486] update trades api with fill type

- protocol/app/app.go
- protocol/app/app_test.go
- protocol/daemons/liquidation/client/client.go
- protocol/daemons/liquidation/client/client_test.go
- protocol/daemons/liquidation/client/sub_task_runner.go
- protocol/daemons/liquidation/client/sub_task_runner_test.go
- protocol/daemons/pricefeed/client/client.go
- protocol/daemons/pricefeed/client/client_test.go
- protocol/daemons/types/health_checkable.go
- protocol/daemons/types/health_checkable_test.go
- protocol/testutil/daemons/common.go
Implement the HealthCheck on the liquidations daemon, complete with refactors that both allow for easier mocking (for the sake of healthcheck unit tests) and prepare the daemon for implementing a Stop method in the future.
- daemon initializes to unhealthy
- daemon toggles to healthy whenever loop success occurs
- daemon toggles to unhealthy whenever the task loop returns an error
- no change but FYI: this shared health tracking type still initializes as unhealthy and updates to healthy when the most recent report was successful
- change: I removed the logic that toggles the HealthCheckable to unhealthy if the last success report was > 5 minutes old. We now log an error instead.
Updated existing tests and added a new set of unit tests for health checks. Also added checks in unit tests for …
> [CORE-666] - Implement liquidations healthcheck

- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/scripts/dydx_get_perpetual_market_for_clob_pair.sql
- indexer/services/ender/src/scripts/dydx_liquidation_fill_handler_per_order.sql
- indexer/services/ender/src/scripts/dydx_order_fill_handler_per_order.sql
- indexer/services/ender/src/scripts/dydx_stateful_order_handler.sql
- indexer/services/ender/src/scripts/dydx_update_perpetual_position_aggregate_fields.sql
Refactor out looking up clob pair into SQL function.
No change.
> Refactor out looking up clob pair into SQL function.

- protocol/testing/e2e/gov/add_new_market_test.go
In add-new-market gov e2e test, place order on new market with `0` oracle price. This results in a recovered panic during `CheckTx`. 
e2e test
> [CORE-585] In add-new-market gov e2e test, place order on new market with `0` oracle price

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20231110103241_remove_market_fills_type.ts
- indexer/packages/postgres/src/types/fill-types.ts
- indexer/services/comlink/public/api-documentation.md
- indexer/services/comlink/public/swagger.json
- indexer/services/comlink/public/websocket-documentation.md
- indexer/services/ender/__tests__/helpers/constants.ts
- indexer/services/ender/__tests__/lib/kafka-publisher.test.ts
remove market enum from FillsType
unit tested.
> [IND-487] remove market enum from FillsType

- protocol/lib/metrics/constants.go
- protocol/testutil/constants/clob_pair.go
- protocol/x/clob/keeper/clob_pair_test.go
- protocol/x/clob/keeper/get_price_premium_test.go
- protocol/x/clob/keeper/process_operations.go
- protocol/x/clob/keeper/process_operations_test.go
- protocol/x/clob/memclob/memclob.go
- protocol/x/clob/types/message_proposed_operations.go
slack thread [here](https://dydx-team.slack.com/archives/C03SLFHC3L7/p1699473001736049?thread_ts=1699415363.029589&cid=C03SLFHC3L7).
order removal reason Fully filled is only used within indexer services, thus it is not a valid removal reason for process operations.
> Disallow order removal reason fully filled

- protocol/scripts/governance/bridge_vesters_set_rewards.py
-  use estimated proposal pass time to calculate delay_blocks
- Nit
Tested on localnet
Example output
```
% python3 scripts/governance/bridge_vesters_set_rewards.py
Estimated proposal pass time (4 days from now) = 2023-11-28T03:01:45+00:00
Estimated block delay for first update @ 2023-12-19T15:00:00+00:00 = 1428842
Estimated block delay for first update @ 2024-01-16T15:00:00+00:00 = 3289765
Output written to proposal_bridge_vesters_set_rewards.json
```
Example json file
```
{
"title": "TODO: Fill in proposal title",
"deposit": "10000000000000000000000adv4tnt",
"summary": "\nTODO: Fill in proposal content. \nInclude detailed description of the proposal, links to governance discussion forums (if applicable).\nAny signal proposal in text should also be added here.\n",
"messages": [
{ …
```
> Fix sample rewards script

- protocol/testing/e2e/gov/prices_test.go
- protocol/testutil/prices/market_param_price.go
add integration tests for `MsgUpdateMarketParam`
> [CORE-517] add integration tests for prices governance messages

- protocol/x/sending/app_test.go
add e2e tests for `MsgCreateTransfer`, which transfers between subaccounts
> [CORE-619] add e2e tests for subaccount transfers

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/__tests__/stores/transfer-table.test.ts
- indexer/packages/postgres/__tests__/stores/wallet-table.test.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20231128175805_add_wallets_total_trading_rewards.ts
- indexer/packages/postgres/src/models/wallet-model.ts
- indexer/packages/postgres/src/types/db-model-types.ts
- indexer/packages/postgres/src/types/wallet-types.ts
- indexer/services/comlink/__tests__/controllers/api/v4/transfers-controller.test.ts
- indexer/services/ender/__tests__/handlers/transfer-handler.test.ts
- indexer/services/ender/src/scripts/dydx_transfer_handler.sql
Update wallets postgres table with totalTradingRewards field
Updated tests
> [IND-495]: Update wallets postgres table with totalTradingRewards field

- indexer/services/ender/src/lib/on-message.ts
Track lag for block time to ingestion time
None, just adding metrics
> Track lag for block time to ingestion time

- .github/pull_request_template.md
> Update PR template for indexer breaking postgres changes

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/__tests__/stores/trading-rewards-table.test.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20231129153017_create_trading_rewards_table.ts
- indexer/packages/postgres/src/helpers/db-helpers.ts
- indexer/packages/postgres/src/models/trading-reward-model.ts
- indexer/packages/postgres/src/models/wallet-model.ts
- indexer/packages/postgres/src/stores/trading-reward-table.ts
- indexer/packages/postgres/src/types/db-model-types.ts
- indexer/packages/postgres/src/types/index.ts
- indexer/packages/postgres/src/types/query-types.ts
- indexer/packages/postgres/src/types/trading-reward-types.ts
Create trading_rewards postgres table
Test with unit tests
> [IND-494]: Create trading_rewards postgres table

- protocol/lib/metrics/constants.go
- protocol/lib/metrics/lib.go
- protocol/lib/metrics/metric_keys.go
- protocol/lib/metrics/util.go
- protocol/x/clob/abci.go
- protocol/x/clob/keeper/deleveraging.go
- protocol/x/clob/keeper/liquidations.go
- protocol/x/clob/keeper/mev.go
- protocol/x/clob/types/order_id.go
Provide a standard for metrics going forward.
First step to do this is to create a singular entrypoint method that we report metrics through.
We currently have multiple different ways we report telemetry, using these two libraries across all files in the codebase:
```
gometrics "github.com/armon/go-metrics"
"github.com/cosmos/cosmos-sdk/telemetry"
```
Barrel everything through metric functions in `metrics/lib.go`.
Files should be migrated one by one, so here's a start with migrating a few libraries.
There should be _no_ change in how metrics are reported.
After everything goes through the singular entrypoint method, we can look at unifying the metrics libraries.
Also, un-modularize the metrics keys instead.
instead of passing in `[]string{"clob", "place_order", "count"}`, we should just …
> [CLOB-1014] [CLOB-1004] Unify metrics library, un-modularize metrics keys

- indexer/packages/postgres/__tests__/db/helpers.test.ts
- indexer/packages/postgres/src/db/helpers.ts
- indexer/services/comlink/__tests__/controllers/api/v4/addresses-controller.test.ts
- indexer/services/comlink/__tests__/controllers/api/v4/perpetual-positions-controller.test.ts
- indexer/services/comlink/__tests__/lib/helpers.test.ts
- indexer/services/comlink/src/lib/helpers.ts
- indexer/services/roundtable/src/helpers/pnl-ticks-helper.ts
Fix unsettled funding sign
Since the sign was changed in the shared `getUnsettledFunding` function, updated minus -> plus in roundtable pnl calculation task. Pnl unit tests are still passing.
Unit tests
> Fix unsettled funding sign

- protocol/daemons/liquidation/client/grpc_helper.go
- protocol/daemons/liquidation/client/grpc_helper_test.go
- protocol/daemons/liquidation/client/sub_task_runner.go
- No functional change, only organizational update
> [CLOB-1036] organizational update for liquidation daemon

- protocol/app/app.go
- protocol/app/flags/flags.go
- protocol/daemons/flags/flags.go
- protocol/daemons/flags/flags_test.go
- protocol/daemons/pricefeed/client/client_integration_test.go
- protocol/daemons/server/types/health_checker.go
- protocol/daemons/server/types/health_monitor.go
- protocol/daemons/server/types/health_monitor_test.go
- protocol/docker-compose.yml
- protocol/x/clob/client/cli/cancel_order_cli_test.go
- protocol/x/clob/client/cli/liquidations_cli_test.go
- protocol/x/clob/client/cli/place_order_cli_test.go
Add 2 flags:
- configure # of seconds before unhealthy daemon causes a panic
- enable panicking behavior or log error when daemon health check fails
- unit tests for daemonFlags
- tested both flags with localnet.
> [CORE-668,CORE-669] - Add health monitor flags

- protocol/daemons/liquidation/client/client.go
- protocol/daemons/liquidation/client/grpc_helper.go
- protocol/daemons/liquidation/client/grpc_helper_test.go
- protocol/lib/metrics/metric_keys.go
- grpc to get all market prices 
- 
> [CLOB-1038] liquidation daemon - grpc to get all market prices

- protocol/x/clob/keeper/stateful_order_state.go
- protocol/x/subaccounts/keeper/negative_tnc_subaccount.go
- protocol/x/subaccounts/keeper/negative_tnc_subaccount_test.go
- protocol/x/subaccounts/types/keys.go
Implement `GetNegativeTncSubaccountSeenAtBlock` and `SetNegativeTncSubaccountSeenAtBlock`.
Unit tests only, didn't write E2E tests since this isn't used in any top-level functionality yet.
> Implement `GetNegativeTncSubaccountSeenAtBlock` and `SetNegativeTncSubaccountSeenAtBlock` [CLOB-1026]

- protocol/app/app.go
- protocol/indexer/events/constants.go
- protocol/testing/e2e/trading_rewards/trading_rewards_test.go
- protocol/testutil/app/app.go
- protocol/testutil/keeper/clob.go
- protocol/testutil/keeper/rewards.go
- protocol/x/rewards/keeper/keeper.go
- protocol/x/rewards/module_test.go
- Emit TradingRewardEventV1 for indexer to process trading rewards
- Decouple usage of appOpts and disabling update monitor for testing in `TestApp`. Sometimes, like in this PR, we might want to have appOpts and also still disable the update monitor.
- Extended existing e2e test
> Emit TradingRewardEventV1 events in rewards module

- protocol/x/clob/flags/flags.go
[Causing error logs in `dev`](https://app.datadoghq.com/logs?query=env%3Adev%20status%3Aerror%20&cols=host%2Cservice&event=AgAAAYxaQNyGckFdyAAAAAAAAAAYAAAAAEFZeGFRTl81QUFEcjJjXzU1QVZsendBRQAAACQAAAAAMDE4YzVhNDAtZTE5MS00ZGZjLTk2YzYtODVhNmVlMGE1YTFm&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&view=spans&viz=stream&from_ts=1702304471302&to_ts=1702318871302&live=true) since this flag is being [parsed as a list of length 1 with the element being th empty string](https://app.datadoghq.com/logs?query=env%3Adev%20Parsed%20CLOB%20flags%20&cols=host%2Cservice&event=AgAAAYxaELhzcMGBxAAAAAAAAAAYAAAAAEFZeGFFTHFFQUFBTmdPNEVselE5TVFBSwAAACQAAAAAMDE4YzVhMTQtMDAzOS00MGQ3LTgzZTEtZmI1N2ViMGVmZGE0&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&view=spans&viz=st …
> Fix CLOB flag parsing for MEV telemetry hosts

- protocol/daemons/server/types/health_checker.go
Race tests are detecting potential conflict in the initialization of the health checker mutable state timer, and updates to the timer after polling starts. This race is logically impossible, but to prevent the false positive I moved the initialization of the timer to a method where it isgated behind the lock on the mutable state object.
Existing tests should continue to pass + no more race failures.
> Fix false positive race tests by gating all R/W access to timers behind synchronization

- v4-proto-js/package-lock.json
- v4-proto-js/package.json
bump stargate version of v4-proto to 0.32.1
> [IND-519] bump cosmjs/stargate dependency version to 0.32.1

- indexer/scripts/deploy-commit-to-env.sh
- indexer/scripts/push-commit-to-ecr.sh
> Update commit scripts

- protocol/app/app.go
- protocol/app/flags/flags.go
- protocol/daemons/flags/flags.go
- protocol/x/clob/flags/flags.go
Add special casing for empty string when parsing string flags. This will run into an error when the default value is not the empty string.
Note this special casing already exists with other string flag parsing, such as [parsing the Kafka connection string](https://github.com/dydxprotocol/v4-chain/blob/316473cf115ee901a1371151512a8e97987f66da/protocol/indexer/flags.go#L81).
Ran this locally and verified that the empty string flag is parsed out, therefore requiring the empty string check.
> Add empty string check to string flag parsing

- protocol/daemons/liquidation/client/grpc_helper.go
- protocol/daemons/liquidation/client/grpc_helper_test.go
- protocol/daemons/liquidation/client/sub_task_runner.go
- protocol/daemons/liquidation/client/sub_task_runner_test.go
- protocol/daemons/server/liquidation.go
- protocol/daemons/server/types/liquidations/daemon_liquidation_info.go
- protocol/daemons/server/types/liquidations/daemon_liquidation_info_test.go
- protocol/lib/metrics/constants.go
- populate subaccounts with open positions in grpc request
> [CLOB-1047] populate subaccounts with open positions in grpc request

- protocol/daemons/liquidation/client/grpc_helper.go
- protocol/daemons/liquidation/client/grpc_helper_test.go
- protocol/daemons/liquidation/client/sub_task_runner.go
- protocol/daemons/liquidation/client/sub_task_runner_test.go
- protocol/daemons/server/liquidation.go
- protocol/daemons/server/liquidation_test.go
- protocol/daemons/server/types/liquidations/daemon_liquidation_info.go
- protocol/daemons/server/types/liquidations/daemon_liquidation_info_test.go
- protocol/lib/metrics/constants.go
- protocol/testutil/constants/subaccounts.go
- populate block height and negative tnc subaccounts in liquidation daemon grpc request.
> [CLOB-1046] populate negative tnc subaccounts in grpc request

- indexer/packages/compliance/src/constants.ts
- indexer/services/socks/__tests__/lib/subscriptions.test.ts
- indexer/services/socks/__tests__/websocket/index.test.ts
- indexer/services/socks/src/lib/subscription.ts
- indexer/services/socks/src/types.ts
- indexer/services/socks/src/websocket/index.ts
- indexer/services/socks/src/websocket/restrict-countries.ts
Update `socks` to return a blocked error message when subscribing to subaccounts channel from a restricted region. This is done by storing additional metadata per websocket connection indicating which country the connection was made from.
In the case where no country exists, this blocking logic fails-open (allows subscribing to subaccounts).
Unit tests.
> [IND-526] Block subscribing to subaccounts from restricted regions for read-only mode.

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/__tests__/helpers/conversion-helpers.ts
- indexer/packages/postgres/__tests__/stores/trading-reward-aggregation-table.test.ts
- indexer/packages/postgres/src/constants.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20231221153944_update_trading_rewards_amount_scale.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20231221165820_update_wallet_total_trading_rewards_scale.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20231221233356_update_trading_reward_aggregations_amount_scale.ts
- indexer/packages/postgres/src/index.ts
- indexer/packages/postgres/src/stores/trading-reward-table.ts
- indexer/packages/postgres/src/types/websocket-message-types.ts
- indexer/services/ender/__tests__/handlers/trading-rewards-handler.test.ts
- indexer/services/ender/__tests__/handlers/transfer-handler.test.ts
- indexer/services/ender/__tests__/helpers/constants.ts
- indexer/services/ender/__tests__/helpers/conversion-helpers.ts
- indexer/services/ender/src/handlers/trading-rewards-handler.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/lib/block-processor.ts
- indexer/services/ender/src/lib/helper.ts
- indexer/services/ender/src/lib/on-message.ts
- indexer/services/ender/src/lib/types.ts
- indexer/services/ender/src/scripts/handlers/dydx_block_processor_unordered_handlers.sql
- indexer/services/ender/src/scripts/handlers/dydx_trading_rewards_handler.sql
- indexer/services/ender/src/scripts/helpers/dydx_process_trading_reward_event.sql
- indexer/services/ender/src/scripts/helpers/dydx_uuid_from_trading_rewards_parts.sql
- indexer/services/ender/src/validators/trading-rewards-validator.ts
Add support for Trading Rewards Handler
Unit tests
> [IND-498]: Add TradingRewardsHandler

- indexer/packages/redis/__tests__/helpers/constants.ts
- indexer/packages/v4-proto-parser/src/order-helpers.ts
- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/__tests__/handlers/order-remove-handler.test.ts
- indexer/services/vulcan/__tests__/handlers/order-update-handler.test.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
- indexer/services/vulcan/src/handlers/order-remove-handler.ts
- indexer/services/vulcan/src/handlers/order-update-handler.ts
Previously, it was possible that an IOC/FOK order is updated to have non-zero remaining amount, and the logic in the order handlers would then add a price level for that IOC/FOK order (e.g. a buy order with price $50 would lead to the creation of a $50 price level on the buy side). This is incorrect as the IOC/FOK order should never lead to the order book having a new price level as it never rests on the book.
This change update the `order-update-handler` to not change orderbook price levels when the remaining amount of FOK/IOC orders change. Logic around decreasing price levels when orders are removed which exist in the `order-place-handler` (for replacing orders) and `order-remove-handler` also needed to be changed to exclude FOK/IOC orders.
This will require some clean-up of orderbook …
> [IND-546] Prevent IOC/FOK orders from changing order book levels / sending updates.

- indexer/packages/postgres/__tests__/lib/protocol-translations.test.ts
- indexer/packages/postgres/src/lib/protocol-translations.ts
- indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
- indexer/services/ender/src/scripts/dydx_from_protocol_time_in_force.sql
Emergency patch to handle invalid `TimeInForce` value of `4` in block `4686923`.
Tested on internal mainnet indexer.
> Emergency patch to handle invalid TimeInForce.

- indexer/packages/base/src/stats-util.ts
- indexer/packages/postgres/__tests__/stores/block-table.test.ts
- indexer/packages/postgres/src/stores/block-table.ts
- indexer/services/comlink/__tests__/controllers/api/v4/height-controller.test.ts
- indexer/services/comlink/__tests__/lib/helpers.test.ts
- indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
- indexer/services/comlink/src/controllers/api/v4/asset-positions-controller.ts
- indexer/services/comlink/src/controllers/api/v4/height-controller.ts
- indexer/services/ender/src/caches/block-cache.ts
- indexer/services/roundtable/src/tasks/cancel-stale-orders.ts
- indexer/services/roundtable/src/tasks/create-pnl-ticks.ts
- indexer/services/roundtable/src/tasks/remove-expired-orders.ts
- indexer/services/roundtable/src/tasks/track-lag.ts
- indexer/services/vulcan/__tests__/handlers/order-remove-handler.test.ts
- indexer/services/vulcan/src/handlers/order-remove-handler.ts
Update BlockTable.getLatest to throw an error and simplify logic
Update unit tests
> Update BlockTable.getLatest to throw an error and simplify logic

- indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
- indexer/services/roundtable/src/config.ts
- indexer/services/roundtable/src/index.ts
- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
Create Aggregate trading rewards roundtable task outline
none
> [IND-500]: Create Aggregate trading rewards roundtable task outline

- protocol/x/subaccounts/keeper/subaccount.go
Make the funding payment event ordering deterministic. Should address [this Github issue](https://github.com/dydxprotocol/v4-chain/issues/895).
Not tested since the change is fairly simple and doesn't affect anything in state (only events).
> [bugfix][protocol] make funding payment event ordering deterministic

- protocol/app/process/other_msgs.go
- protocol/x/ratelimit/keeper/keeper_test.go
- protocol/x/ratelimit/types/expected_keepers.go
[CORE-538] Address nit and fix post Cosmos 0.50 merge conflict
Existing tests
> [CORE-538] Address nit

- protocol/app/app.go
- protocol/app/simulation_test.go
- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/testutil/app/app.go
- protocol/testutil/network/network.go
[CORE-538] Remove DB shutdown, Cosmos 0.50 SDK does this now.
Crashing app tests would discover that we are using the db while it is still open.
> [CORE-538] Remove DB shutdown, Cosmos 0.50 SDK does this now in BaseApp

- protocol/lib/metrics/constants.go
- protocol/lib/metrics/metric_keys.go
- protocol/x/clob/keeper/process_operations.go
- protocol/x/clob/keeper/process_operations_test.go
- protocol/x/clob/types/errors.go
- protocol/x/clob/types/expected_keepers.go
- protocol/x/clob/types/match_perpetual_deleveraging.go
- protocol/x/clob/types/match_perpetual_deleveraging_test.go
- protocol/x/clob/types/message_proposed_operations_test.go
When encountering a zero-fill deleveraging operation in `DeliverTx`, write the current block number to state.
Note the zero-fill deleveraging operation is meant to be a sentinel value to indicate a negative TNC subaccount exists in state at the time of processing the deleveraging operation.
Unit tests. Will add E2E tests when the feature is fully implemented.
> [feat][protocol] Write block number to state when encountering zero-fill deleveraging op [CLOB-1030]

- indexer/services/roundtable/src/lib/athena-ddl-tables/trading_reward_aggregations.ts
- indexer/services/roundtable/src/lib/athena-ddl-tables/trading_rewards.ts
- indexer/services/roundtable/src/tasks/update-research-environment.ts
Add support for trading reward tables in Athena
Unit tests
> [IND-553]: Add support for trading reward tables in Athena

- protocol/x/clob/e2e/long_term_orders_test.go
- protocol/x/clob/types/errors.go
- protocol/x/clob/types/message_place_order.go
- protocol/x/clob/types/message_place_order_test.go
* [CLOB-1056] add validations for enums in clob protos
* e2e test to verify that existing orders won't break things
* comment
> [CLOB-1056] add validations for enums in clob protos (#909)

- indexer/packages/base/src/date-helpers.ts
- indexer/packages/base/src/index.ts
- indexer/packages/postgres/__tests__/helpers/mock-generators.ts
- indexer/packages/postgres/__tests__/stores/trading-reward-aggregation-table.test.ts
- indexer/packages/postgres/__tests__/stores/trading-reward-table.test.ts
- indexer/packages/postgres/__tests__/stores/wallet-table.test.ts
- indexer/packages/postgres/src/models/trading-reward-aggregation-model.ts
- indexer/packages/postgres/src/stores/trading-reward-aggregation-table.ts
- indexer/packages/postgres/src/stores/wallet-table.ts
- indexer/packages/postgres/src/types/query-types.ts
- indexer/packages/postgres/src/types/wallet-types.ts
- indexer/packages/redis/__tests__/caches/aggregate-trading-rewards-processed-cache.test.ts
- indexer/packages/redis/src/caches/aggregate-trading-rewards-processed-cache.ts
- indexer/packages/redis/src/index.ts
- indexer/services/ender/__tests__/handlers/trading-rewards-handler.test.ts
- indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
- indexer/services/roundtable/src/config.ts
- indexer/services/roundtable/src/index.ts
- indexer/services/roundtable/src/lib/constants.ts
- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
- Add AggregateTradingRewardsProcessedCache cache
- Set and pull from AggregateTradingRewardsProcessedCache in AggregateTradingRewardsTask
- Generate interval in AggregateTradingRewardsTask
Extensive unit tests
> [IND-499]: Add AggregateTradingRewardsProcessedCache with roundtable task

- indexer/packages/postgres/__tests__/stores/perpetual-market-table.test.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20240108175501_add_perpetual_markets_status_final_settlement.ts
breaking staging env currently
add FINAL_SETTLEMENT to perpetual markets status constraint
unit tested
> add FINAL_SETTLEMENT to perpetual markets status constraint

- indexer/services/roundtable/__tests__/helpers/pnl-ticks-helper.test.ts
- indexer/services/roundtable/__tests__/tasks/create-pnl-ticks.test.ts
- indexer/services/roundtable/src/helpers/pnl-ticks-helper.ts
- indexer/services/roundtable/src/tasks/create-pnl-ticks.ts
Fix occasional missing pnl ticks.
Pnl computation is skipping some hours for some subaccounts. 
For example, 106bcbc8-f80d-5d62-bf65-e88708c88ec9 subaccount id in staging missed the pnl computation at 2024-01-09 04:00:25.572+00 because the last pnl tick happened at 2024-01-09 03:00:50.58+00, which is slightly < 1 hr ago.
When checking whether or not to update a subaccount's pnl, change the time threshold from 1 hr to 0.9 hrs.
unit tested.
> [IND-557] fix occasional missing pnl ticks

- indexer/packages/postgres/__tests__/helpers/conversion-helpers.ts
- indexer/packages/postgres/src/stores/trading-reward-aggregation-table.ts
- indexer/packages/postgres/src/stores/trading-reward-table.ts
- indexer/packages/postgres/src/types/query-types.ts
- indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
- indexer/services/roundtable/src/config.ts
- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
Add logic to aggregate trading rewards
Unit tests
> [IND-500]: Add logic to aggregate trading rewards

- protocol/lib/metrics/constants.go
- protocol/lib/metrics/metric_keys.go
- protocol/mocks/MemClob.go
- protocol/mocks/MemClobKeeper.go
- protocol/x/clob/abci.go
- protocol/x/clob/e2e/withdrawal_gating_test.go
- protocol/x/clob/keeper/deleveraging.go
- protocol/x/clob/keeper/process_operations.go
- protocol/x/clob/memclob/memclob.go
- protocol/x/clob/types/internal_operation.go
- protocol/x/clob/types/memclob.go
- protocol/x/clob/types/operations_to_propose.go
Gate withdrawals if a negative TNC subaccount is encountered after the liquidation and deleveraging steps in `PrepareCheckState`.
Note that all potentially liquidatable subaccounts specified by the daemon will be checked for simplicity.
Wrote E2E tests verifying that when there's negative TNC subaccounts found in state, that withdrawals are blocked.
> [feat][protocol]: gate withdrawals if negative TNC subaccount encountered after liquidation and deleveraging steps

- protocol/go.mod
- protocol/go.sum
- Latest cosmos fork https://github.com/dydxprotocol/cosmos-sdk/pull/33 needed to fix RPC queries
- Tested locally. Will test on internal node before releasing testnet validators.
> Upgrade cosmos fork to fix RPC queries

- indexer/services/roundtable/src/config.ts
- indexer/services/roundtable/src/index.ts
add lock multiplier for pnl ticks roundtable task
Sometimes, we see multiple pnl ticks for the same hour. The current interval is set to 30s. If the pnl computation takes longer than 30s, it's possible another pnl task starts concurrently. Introduce a lock interval multiplier for pnl task to ensure there's only 1 pnl tick computed per hour.
test in dev/staging
> add lock multiplier for pnl ticks roundtable task

- indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
Fix bug that in a long running chain with only `trading_rewards` recently introduced, we should process aggregate trading rewards from the first trading reward instead of the first block, other we'll be processing no data
Unit tests
> Start processing aggregate trading rewards from first reward

- protocol/indexer/shared/order_removal_reason.go
- protocol/indexer/shared/order_removal_reason_test.go
Datadog error [here](https://app.datadoghq.com/logs?query=env%3Adev%20status%3Aerror&agg_q=status%2Cservice&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_t=%2C&stream_sort=desc&top_n=10%2C10&top_o=top%2Ctop&viz=pattern&x_missing=true%2Ctrue&from_ts=1704995802250&to_ts=1705082202250&live=true) after running load tester
Account for the specific error type
> Indexer account for reduce only resize errors

- indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
Remove first block from aggregate trading rewards roundtable task interval. Turns the block time for the genesis block can be years ago. We don't need to calculate from the first block ever, we can just wait for the first trading reward to calculate aggregations.
Tested in staging, and works
> Remove first block from aggregate trading rewards roundtable task interval

- protocol/scripts/genesis/sample_pregenesis.json
- protocol/testing/genesis.sh
[CORE-538] Have testing genesis.sh match expected gov parameters for 0.50
Updated existing test result
> [CORE-538] Have testing genesis.sh match expected gov parameters for 0.50

- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/cmd/dydxprotocold/cmd/root_test.go
- protocol/cmd/dydxprotocold/main.go
- protocol/testing/containertest/node.go
- protocol/testutil/app/app.go
[DEC-2201] Ensure that we use the client context with AutoCLI
Note that the basis of this code is from https://github.com/dydxprotocol/cosmos-sdk/blob/b48250d4e0efacbd40f3e0b980c1e1004d29e351/simapp/simd/cmd/root.go#L103 which is linked from the Cosmos 0.50 upgrade guide.
Added unit test.
> [DEC-2201] Ensure that we use the client context with AutoCLI

- indexer/datadog/Dockerfile
- protocol/docker-compose.yml
Update usages of `datadog/agent` to `public.ecr.aws/datadog/agent` due to more aggressive rate-limiting from Dockerhub. 
Built images.
> [DEC-2202] Update datadog agent image to use ECR hosted image.

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20240117120410_remove_unused_liquidity_tiers_columns.ts
- indexer/packages/postgres/src/models/liquidity-tiers-model.ts
- indexer/packages/postgres/src/types/db-model-types.ts
- indexer/packages/postgres/src/types/liquidity-tiers-types.ts
- indexer/packages/postgres/src/types/websocket-message-types.ts
- indexer/services/comlink/__tests__/lib/request-helpers/request-transformer.test.ts
- indexer/services/comlink/public/api-documentation.md
- indexer/services/comlink/public/swagger.json
- indexer/services/comlink/public/websocket-documentation.md
- indexer/services/comlink/src/request-helpers/request-transformer.ts
- indexer/services/comlink/src/types.ts
- indexer/services/ender/__tests__/handlers/liquidity-tier-handler.test.ts
- indexer/services/ender/__tests__/validators/liquidity-tier-validator.test.ts
- indexer/services/ender/src/helpers/kafka-helper.ts
- indexer/services/ender/src/scripts/handlers/dydx_liquidity_tier_handler.sql
- indexer/services/ender/src/validators/liquidity-tier-validator.ts
- indexer/services/roundtable/src/helpers/websocket.ts
- indexer/services/roundtable/src/lib/athena-ddl-tables/liquidity_tiers.ts
Cherry-pick basePositionNotional deprecation in Indexer APIs
Unit tested.
> Cherry-pick basePositionNotional deprecation in Indexer APIs

- protocol/lib/metrics/metric_keys.go
- protocol/x/clob/keeper/deleveraging.go
Fix withdrawal gating double usage of metrics name for two different types of counters.
Manually test on persistent environment.
> Fix withdrawal gating double usage of metrics name for two different types of counters.

- indexer/scripts/deploy-commit-to-env.sh
- indexer/services/auxo/src/index.ts
Wait until bazooka image finishes upgrading before running bazooka in auxo lambda.
When running auxo in our testnet environment, the old bazooka image was used, which led to an expected db migration not happening.
ran in dev
> [IND-556] wait until bazooka image finishes upgrading before running bazooka in auxo lambda

- protocol/testutil/auth/auth_helpers.go
- protocol/x/subaccounts/keeper/transfer_test.go
[CORE-538] Fix bogus account numbers being generated in tests and re-enable tests.
Tests re-enabled.
> [CORE-538] Fix bogus account numbers being generated in tests and re-enable tests.

- protocol/x/clob/keeper/mev_test.go
[CORE-538] Update usage of mocks and re-enable test.
Re-enabled existing test.
> [CORE-538] Update usage of mocks and re-enable test.

- protocol/testutil/bank/bank_helpers.go
- protocol/x/clob/client/cli/cancel_order_cli_test.go
- protocol/x/clob/client/cli/liquidations_cli_test.go
- protocol/x/clob/client/cli/place_order_cli_test.go
[CORE-538] Fix CLI tests to correctly generate module address. 
Incorrectly converted how we generate module address during Cosmos 0.50 upgrade. This was the only case of where I swapped module address generation with using the signing context erroneously.
Re-enabled existing tests.
> [CORE-538] Fix CLI tests to correctly generate module address

- protocol/scripts/iaviewer/iaviewer.go
[CORE-538] Update iaviewer comment.
Turns out that during the 0.47 -> 0.50 upgrade I made all same changes the 0.20.0 -> 1.0.0 conversion did so there is nothing left to do here.
N/A
> [CORE-538] Update iaviewer comment.

- protocol/app/app.go
- protocol/contracts/dydx-messages-example/Cargo.lock
- protocol/contracts/dydx-messages-example/src/contract.rs
- protocol/contracts/dydx-messages-example/src/msg.rs
- protocol/dydx-cosmwasm/src/lib.rs
- protocol/dydx-cosmwasm/src/msg.rs
- protocol/dydx-cosmwasm/src/proto_structs.rs
- protocol/dydx-cosmwasm/src/querier.rs
- protocol/dydx-cosmwasm/src/query.rs
- protocol/dydx-cosmwasm/src/route.rs
- protocol/wasmbinding/queries.go
- Added query for market price in smart contract
Reference: [Example Sei contract](https://github.com/y-pakorn/sei-cosmwasm/tree/1bf3aeebbce891265f715dd7e5b6d4c117992b1a/contracts/sei-tester)
To test this locally, follow below steps:
- Follow steps 1~5 in this [PR](https://github.com/dydxprotocol/v4-chain/pull/977) description to build contract
- Make a `market_price` query on smart contract: `$ build/dydxprotocold query wasm contract-state smart dydx14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s2de90j '{"market_price":{"id": 0}}'`
> Add `MarketPrice` query in example smart contract

- protocol/contracts/dydx-messages-example/src/contract.rs
- protocol/wasmbinding/msg_plugin.go
- Build, deploy, instantiate contract as usual.
- Construct a json payload 
```
PLACE_ORDER='{ 
"place_order": {
"subaccount_id": {
"owner": "dydx199tqg4wdlnu4qjlxchpd7seg454937hjrknju4",
"number": 0
},
"client_id": 0,
"order_flags": 64,
"clob_pair_id": 0,
"side": 1,
"quantums": 10000000,
"subticks": 5000000000,
"good_til_block_time": 1705616300,
"time_in_force": 0,
"reduce_only": false,
"client_metadata": 0,
"condition_type": 0,
"conditional_order_trigger_subticks": 0
}
}'
```
- Send a transaction to contract 
```
dydxprotocold tx wasm execute dydx14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s2de90j "$PLACE_ORDER" --from alice --gas auto --fees 1256394675000000000adv4tnt --chain-id localdydxprotocol --node $NODE
```
- Verify that …
> market make

- protocol/testutil/app/app.go
- protocol/testutil/keeper/delaymsg.go
- protocol/testutil/logger/logger.go
- protocol/x/clob/abci.go
[CORE-538] Remove genesis check that isn't needed since the issue was with how testapp was simulating block processing.
Also clean-up TODO comments that aren't important and are low value.
No changes to tests, existing tests pass.
> [CORE-538] Remove genesis check that isn't needed since the issue was with how testapp was simulating block processing.

- indexer/packages/postgres/src/stores/fill-table.ts
- indexer/packages/postgres/src/stores/order-table.ts
- indexer/packages/postgres/src/stores/perpetual-position-table.ts
- indexer/packages/postgres/src/stores/subaccount-table.ts
Update default postgres options for tables. Set to DEFAULT_POSTGRES_OPTIONS for all read operations and `{ txId: undefined }` for all write operations
N/A
> Update default postgres options for tables

- protocol/Dockerfile
Add `bintutils-gold` to the builder image as indicated by this [open issue](https://github.com/golang/go/issues/22040) on golang to fix issues when building the image locally on arm64.
Built docker image locally (on arm64).
> Fix Dockerfile, add bintuils-gold.

- protocol/app/msgs/normal_msgs.go
- protocol/app/msgs/normal_msgs_test.go
- protocol/app/msgs/unsupported_msgs.go
- protocol/app/msgs/unsupported_msgs_test.go
- protocol/lib/ante/unsupported_msgs.go
- Disable `MsgCancelProposal` which was a new message introduced in Cosmos SDK 0.50 (Context [here](https://www.notion.so/dydx/AC-Priv-Genesis-Parameters-d2321636dd494ee49cc95b7825cbbc98?pvs=4#2490f3813f944d3e9baac8633e240e8a))
> Disable `MsgCancelProposal` 

- protocol/app/testdata/default_genesis_state.json
- protocol/go.mod
- protocol/go.sum
- protocol/testutil/constants/genesis.go
- Bump `cosmos-sdk` fork version which updates default gov parameters as part of state migration
No easy way to test this currently, except for a container test for `v4.0.0` upgrade discussed [here](https://dydx-team.slack.com/archives/C0586UVB6J1/p1706303069661969?thread_ts=1703004791.136919&cid=C0586UVB6J1)
> [CORE-850] Bump Cosmos-SDK version for updated default gov parameters

- protocol/app/upgrades.go
- protocol/app/upgrades/v4.0.0/upgrade.go
Set default rate limit params for x/ratelimit in upgrade handler. 
No easy way to test this right now except for an upgrade container test discussed [here](https://dydx-team.slack.com/archives/C0586UVB6J1/p1706303069661969?thread_ts=1703004791.136919&cid=C0586UVB6J1)
> [CORE-824] Add upgrade handler for ratelimit keeper

- indexer/packages/postgres/src/stores/candle-table.ts
- indexer/packages/postgres/src/stores/fill-table.ts
- indexer/packages/postgres/src/stores/funding-index-updates-table.ts
- indexer/packages/postgres/src/stores/oracle-price-table.ts
- indexer/packages/postgres/src/stores/order-table.ts
- indexer/packages/postgres/src/stores/perpetual-position-table.ts
- indexer/packages/postgres/src/stores/pnl-ticks-table.ts
- indexer/packages/postgres/src/stores/subaccount-table.ts
- indexer/packages/postgres/src/stores/tendermint-event-table.ts
- indexer/packages/postgres/src/stores/trading-reward-aggregation-table.ts
- indexer/packages/postgres/src/stores/trading-reward-table.ts
- indexer/packages/postgres/src/stores/transaction-table.ts
- indexer/packages/postgres/src/stores/transfer-table.ts
- indexer/services/roundtable/__tests__/tasks/aggregate-trading-rewards.test.ts
- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
Fix Aggregate Historical Trading rewards and always use generated id in tables
- Since we did not query for existing `trading_reward_aggregations` with `startedAtHeight`, any existing trading aggregation for that address and period was found and we would attempt to update a `trading_reward_aggregations` that did not exist rather than create a new aggregation.
- Always use generated ids in tables instead of defaulting to the object that is passed in. This will prevent errors where the object contains an id that is incorrect is sent to the table. Instead of overwriting the incorrect id with the generated id, postgres would use the passed in id.
Unit tests, will test in staging before merging
> Fix Aggregate Historical Trading rewards and always use generated id in tables

- indexer/packages/kafka/__tests__/consumer.test.ts
- indexer/packages/kafka/src/config.ts
- indexer/packages/kafka/src/consumer.ts
- indexer/services/ender/src/helpers/kafka/kafka-controller.ts
- indexer/services/scripts/src/print-block.ts
- indexer/services/socks/src/lib/message-forwarder.ts
- indexer/services/vulcan/src/config.ts
- indexer/services/vulcan/src/helpers/kafka/kafka-controller.ts
- indexer/services/vulcan/src/index.ts
- indexer/services/vulcan/src/lib/on-batch.ts
Batch Process Vulcan messages. It doesn't seem like this change makes much of an impact on processing, I believe it's because Vulcan is reading from multiple partitions and the benefit would be improved if there the same number of partitions as instances of vulcan.
See research [here](https://www.notion.so/dydx/Vulcan-Batch-Processing-646a032e6d2c4a939fe6016f4d8e6516?pvs=4)
Tested in Staging and internal mainnet
> [IND-545]: Batch Process Vulcan messages

- protocol/testutil/constants/positions.go
- protocol/x/subaccounts/keeper/subaccount_test.go
Testutil has some already defined PerpetualPosition constants. Employ these constants in the subaccounts module tests
> [CT-34] Use constants defined in testutil for subaccount module tests

- protocol/x/ratelimit/LICENSE
- protocol/x/ratelimit/README.md
- protocol/x/ratelimit/ibc_middleware.go
- protocol/x/ratelimit/keeper/packet.go
- protocol/x/ratelimit/util/ibc.go
- protocol/x/ratelimit/util/ibc_test.go
- protocol/x/ratelimit/util/parse_denom.go
Add licensing info in `x/ratelimit` and attributions to Stride. Changes will be backported to `v4.x`
> [CORE-854] Add licensing info in `x/ratelimit` and attributions to Stride

- indexer/services/comlink/src/controllers/api/v4/candles-controller.ts
- indexer/services/comlink/src/controllers/api/v4/compliance-controller.ts
- indexer/services/comlink/src/controllers/api/v4/height-controller.ts
- indexer/services/comlink/src/controllers/api/v4/historical-funding-controller.ts
- indexer/services/comlink/src/controllers/api/v4/orderbook-controller.ts
- indexer/services/comlink/src/controllers/api/v4/perpetual-markets-controller.ts
- indexer/services/comlink/src/controllers/api/v4/sparklines-controller.ts
- indexer/services/comlink/src/controllers/api/v4/time-controller.ts
- indexer/services/comlink/src/controllers/api/v4/trades-controller.ts
Remove geoblocking from Indexer endpoints:
- Compliance endpoints
- GetCandles
- GetHeight
- GetHistoricalFunding
- GetPerpetualMarket
- ListPerpetualMarkets
- GetSparkLines
- GetTime
- GetTrades
> [OTE-129] remove geoblocking from Indexer endpoints

- indexer/packages/postgres/src/db/migrations/migration_files/20240202084811_add_perpetual_positions_open_event_id_index.ts
Fetching SELECT * FROM perpetual_positions WHERE "subaccountId" = subaccount_uuid AND "perpetualId" = perpetual_id ORDER BY "openEventId" DESC LIMIT 1 was very slow on mainnet.
Tested and verified manually.
> [CT-423] Add missing index

- indexer/packages/postgres/src/db/migrations/migration_files/20240202084811_add_perpetual_positions_open_event_id_index.ts
* [CT-423] Add missing index
Fetching SELECT * FROM perpetual_positions WHERE "subaccountId" = subaccount_uuid AND "perpetualId" = perpetual_id ORDER BY "openEventId" DESC LIMIT 1 was very slow on mainnet.
Tested and verified manually.
> [cherry-pick] [CT-423] Add missing index (#1039)

- protocol/mocks/MemClobKeeper.go
- protocol/testutil/memclob/keeper.go
- protocol/x/clob/keeper/equity_tier_limit.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/types/mem_clob_keeper.go
Split the equity tier limit validation checks into separate functions for short term orders and stateful orders
Existing test suite since this is just a superficial refactor
> [CT-82] Split equity tier validation for short term and stateful orders

- indexer/packages/postgres/src/loops/asset-refresher.ts
- indexer/packages/postgres/src/loops/liquidity-tier-refresher.ts
- indexer/packages/postgres/src/loops/loopHelper.ts
- indexer/packages/postgres/src/loops/perpetual-market-refresher.ts
The cache update loops don't handle errors thrown during their execution, and can crash a service that is running the loop. This occurred when the RDS instance the services connected to was momentarily restarted to apply a security patch.
Instead, wrap the update function in a `try ... catch` to ensure services running the refresher loops don't crash.
N/A.
> Try-catch update functions in cache-update loops.

- protocol/lib/metrics/constants.go
- protocol/x/ratelimit/keeper/keeper.go
- protocol/x/ratelimit/keeper/keeper_test.go
- protocol/x/ratelimit/keeper/packet.go
- protocol/x/ratelimit/util/ibc.go
- Fixed an issue where un-ratelimited denom cannot be IBC transferred
- Improved info logs in various places
- Unit test (newly added)
- Local IBC testnet (documented [here](https://www.notion.so/dydx/Rate-Limiting-Local-IBC-Testnet-Notes-c9b2913c13b14f76b81c17b19e1f2421?pvs=4))
> Fix `x/ratelimit` `ProcessWithdrawal` logic; improve info logs

- protocol/x/subaccounts/types/events.go
Update the event key for subaccount number. Bug was found since downstream event indexers broke.
Note this shouldn't be consensus-breaking since this only changes event emissions.
N/A since trying to get this in next release.
> [bugfix][protocol] fix settled funding event emission

- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/go.mod
- protocol/go.sum
- `--home` flag is being ignored for queries after v0.50 cosmos upgrade
- Verified manually that query now accepts `--home` properly.
- Verified that other flags aren't broken (tested with `--node`)
> Fix --home flag being ignored in cosmos v0.50

- protocol/app/ante.go
- protocol/app/ante_whitebox_test.go
- protocol/go.mod
- protocol/go.sum
[STAB-32] Push CheckTx concurrency into protocol
This pushes locking slightly closer to the CLOB ante decorator hopefully allowing for protocol to control parallelism more finely in the future.
Tests were added in the [Cosmos SDK fork PR](https://github.com/dydxprotocol/cosmos-sdk/pull/37) and there is this [existing concurrency test](https://github.com/dydxprotocol/v4-chain/blob/bc578353766af1b81ecfb93720b54d5890e4f96e/protocol/x/clob/e2e/app_test.go#L231) that is of note.
> [STAB-32] Push CheckTx concurrency into protocol

- protocol/app/testdata/default_genesis_state.json
- protocol/scripts/genesis/sample_pregenesis.json
- protocol/testutil/constants/genesis.go
- protocol/x/ratelimit/types/params.go
- protocol/x/ratelimit/types/params_test.go
Update rate limit params per discussion with research ([thread](https://dydx-team.slack.com/archives/C064WHM02QJ/p1707152411825039)):
```
max(1% of TVL, $1mm) per hour
AND
max(10% of TVL, $10mm) per day
```
Unit tests
> Update default rate limit params for USDC

- protocol/app/ante/gas.go
- protocol/x/clob/ante/ante_wrapper.go
- protocol/x/clob/ante/clob.go
- protocol/x/clob/ante/clob_test.go
> [OTE-154] Update CLOB IsSingleClobMsgTx to not take ctx

- protocol/lib/context.go
- protocol/lib/log/constants.go
example logs, now with request logs:
```
protocol-dydxprotocold0-1  | 4:01AM INF creating transfer!!! module=x/sending request_id=7767e19a8e3229a1bfe4
```
> [feature] Add request_id to all code paths using lib.UnwrapSDKContext

- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/cmd/dydxprotocold/main.go
- protocol/testing/containertest/node.go
- Create a temp dir instead as a quick hack.
- Run localnet, inspect the containers and see that no default home dir was created during any step.
- Run a command `./build/dydxprotocold  query subaccounts show-subaccount dydx1q628jg3e8vzy6xcns6fxls7k7kplqgxr0gy87t 0 --home ~/.dydxprotocol2`, with existing custom home dir, ensure it works properly and doesn't create default home dir.
- Now run it without custom home dir, ensure it creates default home dir and uses it
- Now run it with custom home dir again, ensure it's still using the custom home dir
> Make app runnable without creating default home dir

- indexer/packages/postgres/src/stores/funding-index-updates-table.ts
Optimize funding index update query
- 175ms -> 0.2ms for funding_index_updates
- `select distinct on ("perpetualId") "funding_index_updates".* from "funding_index_updates" where "effectiveAtHeight" <= $1 order by "perpetualId" asc, "effectiveAtHeight" DESC`
Tested in internal mainnet
> Optimize funding index update query

- indexer/packages/postgres/src/db/migrations/migration_files/20240208153050_add_candles_ticket_resolution_index.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20240208161948_add_orders_clobpairid_subaccountid_index.ts
Add Indexes to candles and orders to optimize queries:
- 150ms -> 3ms for candles
- `select "candles".* from "candles" where "ticker" in ($1) and "resolution" = $2 order by "ticker" DESC, "resolution" DESC, "startedAt" DESC limit $3`
- 2500ms -> 180ms for orders
- `select distinct on ("perpetualId") "funding_index_updates".* from "funding_index_updates" where "effectiveAtHeight" <= $1 order by "perpetualId" asc, "effectiveAtHeight" DESC`
Tested in database directly that this reduced latency
> Add Indexes to candles and orders to optimize queries

- protocol/x/subaccounts/keeper/subaccount.go
Cache net collateral and margin requirements per subaccount when applying asset and perpetual updates
No change in functionality but a minor optimization, so the existing tests should cover this
> [CORE-598] Cache current collateralization and margin requirements per subaccount

- protocol/cmd/dydxprotocold/cmd/root.go
- protocol/cmd/dydxprotocold/main.go
- protocol/go.mod
- protocol/go.sum
- Revert https://github.com/dydxprotocol/v4-chain/pull/1062 temporary fix and bring in official cosmos fix for it
- Pass in a temp dir in client tempApp to prevent creation of `data` directory in the cwd
- Tested query commands to ensure correct home directory was being used in default and non-default cases. Checked to make sure default one wasn't created when not intended.
- Ran local net and inspected containers to make sure data directory isn't created in `/dydxprotocol/`.
> Fix unnecessary home directory creation issues

- protocol/go.mod
- protocol/go.sum
- We need this change https://github.com/cosmos/iavl/pull/876
- Without this change, orphan nodes are pruned all at once when we hit upgrade height + keep-recent number of nodes. This took hours on testnet and caused a chain halt.
- N/A
> Upgrade iavl to v1.0.1 to prune orphan nodes async

- protocol/cmd/dydxprotocold/cmd/config.go
[OTE-178] Increase maximum number of connections
Allowed load tester to scale even higher removing one of the bottlenecks.
Before this change:
After this change:
Manually verified during load testing.
> [OTE-178] Increase maximum number of connections

- protocol/go.mod
- protocol/go.sum
Use client/v2 commit from cosmos-sdk v0.50.4. This package released separately, but the latest fixes aren't released yet.
Specifically, we need the deleted block in msg.go to fix the bug: https://github.com/cosmos/cosmos-sdk/pull/19219/files#diff-5560b4d40a3e412c5265a379f1e495c01249be7b08bdb6931555088832fa34d6
Without this change, sign mode handlers are overwritten and we can't sign for pure autocli messages (e.g. `slashing unjail`) (with direct mode).
Note: We don't actually support or intend to support sign mode textual.
Tested `slashing unjail`. Without this change we get the error `unsuppored sign mode SIGN_MODE_TEXTUAL` when trying to run that command.
> Upgrade client/v2 to fix autocli signing issues

- indexer/services/ender/__tests__/handlers/funding-handler.test.ts
- indexer/services/ender/__tests__/helpers/constants.ts
- indexer/services/ender/__tests__/validators/funding-validator.test.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/scripts/handlers/dydx_funding_handler.sql
- indexer/services/ender/src/validators/funding-validator.ts
Introduce flag to ignore invalid FundingEvent where the perpetualId doesn't exist
Fix error handling in funding handler SQL script
unit tested
> Introduce flag to ignore invalid FundingEvent where the perpetualId doesn't exist

- indexer/services/ender/__tests__/handlers/funding-handler.test.ts
- indexer/services/ender/__tests__/handlers/perpetual-market-handler.test.ts
- indexer/services/ender/__tests__/helpers/constants.ts
- indexer/services/ender/__tests__/helpers/postgres-helpers.ts
- indexer/services/ender/__tests__/lib/on-message.test.ts
- indexer/services/ender/__tests__/validators/funding-validator.test.ts
- indexer/services/ender/src/lib/sync-handlers.ts
- indexer/services/ender/src/scripts/handlers/dydx_block_processor_ordered_handlers.sql
- indexer/services/ender/src/scripts/handlers/dydx_block_processor_unordered_handlers.sql
- indexer/services/ender/src/scripts/handlers/dydx_funding_handler.sql
- indexer/services/ender/src/validators/funding-validator.ts
- move funding handler from unordered_handlers to ordered_handlers
- fix funding sql script error handling as in https://github.com/dydxprotocol/v4-chain/pull/1093, and corresponding unit test
- the perp market can be created in the same block as the funding sample, so only log an error in funding validator if the perpetualId can't be found in the `perpetual-markets-refresher` cache
- add an e2e test in `on-message.test.ts` that tests the case where a single block both creates the event & has a funding sample for the newly created market
unit tested
> [CT-521] move funding handler from unordered_handlers to ordered_handlers

- protocol/x/clob/types/constants.go
- protocol/x/clob/types/errors.go
- protocol/x/clob/types/message_batch_cancel.go
- protocol/x/clob/types/message_batch_cancel_test.go
MsgBatchCancel stateless validation.
> [CT-520] Validatebasic for new MsgBatchCancel

- protocol/testing/e2e/gov/add_new_market_test.go
- protocol/x/clob/keeper/msg_server_place_order_test.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/keeper/orders_test.go
- Deprecate pessimistic add-to-book collateralization check
> [CT-619] deprecate pessimistic add-to-book collateralization check

- indexer/packages/postgres/src/stores/order-table.ts
- indexer/packages/postgres/src/types/query-types.ts
- indexer/services/comlink/__tests__/controllers/api/v4/orders-controller.test.ts
- indexer/services/comlink/src/controllers/api/v4/orders-controller.ts
- indexer/services/roundtable/src/tasks/cancel-stale-orders.ts
When listing orders, we were previously only querying the latest ${limit} orders, and not matching by status. So if the latest 100 orders were all filled, and a user was attempting to untriggered orders, they would not receive any orders.
add a test to ensure that status is properly filtered for
> Ensure that all matching status are returned in list orders endpoint

- protocol/x/clob/types/operation.go
Optimize string building loop to write to a single buffer instead of to multiple buffers that are concatenated.
This reduced the cost of the method from 1.86s to 600ms when executing on the dev5 testnet when the nodes were at full load. This is a method that is performed when a block is applied so it reduces how long we hold an exclusive lock preventing CheckTx from occurring.
Existing tests.
> Optimize string building loop to write to a single buffer instead of to multiple buffers that are concatenated.

- indexer/services/scripts/README.md
- indexer/services/scripts/package.json
- indexer/services/scripts/src/print-candle-time-boundaries.ts
Add script to print candle time boundaries
Ran locally
> Add script to print candle time boundaries

- protocol/app/app.go
- protocol/streaming/grpc/grpc_streaming_manager.go
- protocol/streaming/grpc/noop_streaming_manager.go
- protocol/streaming/grpc/types/manager.go
- protocol/testutil/keeper/clob.go
- protocol/x/clob/keeper/keeper.go
> [CT-644] instantiate grpc stream manager

- indexer/packages/postgres/src/db/migrations/migration_files/20240304115004_create_fills_clob_pair_id_created_at_height_created_at_index.ts
add index that includes createdAt to fills to address read replica lag
pushed to mainnet over weekend. See https://dydx-team.slack.com/archives/C05SD03C1A7/p1709414088044459 for details. Metrics [here](https://ap1.datadoghq.com/dashboard/wvp-x3m-ghh/v4-indexer-comlink?fromUser=false&fullscreen_end_ts=1709435097529&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_section=overview&fullscreen_start_ts=1709403169928&fullscreen_widget=7176307515184638&refresh_mode=sliding&view=spans&from_ts=1709485068252&to_ts=1709571468252&live=true)
> [CT-631] add index that includes createdAt to fills to address read replica lag

- protocol/mocks/Makefile
It seems that with this pr [here](https://github.com/dydxprotocol/cosmos-sdk/commit/f4e166bc10570e14ef243a00a28b5033aa5e67f6#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R203) we have changed dependencies in the go.mod file.
Now our previous approach of grepping out the version via:
```
hyperon@Hyperon protocol % go list -m all | grep "github.com/dydxprotocol/cosmos-sdk" 
cosmossdk.io/store v1.0.2 => github.com/dydxprotocol/cosmos-sdk/store v1.0.3-0.20240227194839-f4e166bc1057
github.com/cosmos/cosmos-sdk v0.50.4 => github.com/dydxprotocol/cosmos-sdk v0.50.5-0.20240227194839-f4e166bc1057
hyperon@Hyperon protocol %
```
is incorrect because there are multiple lines and nested strings.
Fix:
1. add regex to ensure there's no nested strings
2. Remove `Marshaler` mock …
> Fix mock-gen build

- protocol/x/subaccounts/keeper/subaccount.go
- protocol/x/subaccounts/keeper/subaccount_test.go
Add functions to get collateral pool address for cross or isolated markets based on the subaccount being used
> [TRA-78] Add function to retrieve collateral pool addr for a subaccount

- protocol/app/app.go
- protocol/streaming/grpc/grpc_streaming_manager.go
- protocol/streaming/grpc/noop_streaming_manager.go
- protocol/streaming/grpc/types/manager.go
- protocol/x/clob/keeper/grpc_stream_orderbook.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/types/errors.go
> [CT-646] stream offchain updates through stream manager

- protocol/app/app.go
- protocol/app/flags/flags.go
- protocol/app/flags/flags_test.go
> [CT-652] add command line flag for full node streaming

- protocol/mocks/ClobKeeper.go
- protocol/mocks/MemClob.go
- protocol/streaming/grpc/grpc_streaming_manager.go
- protocol/streaming/grpc/noop_streaming_manager.go
- protocol/streaming/grpc/types/manager.go
- protocol/x/clob/abci.go
- protocol/x/clob/keeper/keeper.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/memclob/memclob_grpc_streaming.go
- protocol/x/clob/memclob/memclob_grpc_streaming_test.go
- protocol/x/clob/types/clob_keeper.go
- protocol/x/clob/types/memclob.go
> [CT-647] construct the initial orderbook snapshot

- protocol/app/upgrades.go
- protocol/app/upgrades/v5.0.0/constants.go
- protocol/app/upgrades/v5.0.0/upgrade.go
- protocol/testing/containertest/containertest.sh
- protocol/testing/containertest/preupgrade_genesis.json
- protocol/testing/containertest/testnet.go
- protocol/testing/containertest/testnet_test.go
Sets up v5 upgrade as well upgrade container test
> Add `v5` upgrade handler and set up container upgrade test

- protocol/testutil/constants/orders.go
- protocol/x/clob/e2e/batch_cancel_test.go
- protocol/x/clob/keeper/orders.go
add some of those e2e tests.
- batch canceling
- verify offchain events work
> [CT-517] E2E tests batch cancel

- indexer/services/comlink/src/request-helpers/export-response-code-stats.ts
Add aggregate comlink response code stats.
Plan to set up monitor on 500 errors.
> Add aggregate comlink response code stats

- indexer/packages/v4-protos/src/codegen/dydxprotocol/subaccounts/subaccount.ts
- proto/dydxprotocol/subaccounts/subaccount.proto
- protocol/x/clob/types/message_cancel_order_test.go
- protocol/x/clob/types/message_place_order_test.go
- protocol/x/sending/types/message_create_transfer_test.go
- protocol/x/subaccounts/module_test.go
- protocol/x/subaccounts/types/errors.go
- protocol/x/subaccounts/types/genesis_test.go
- protocol/x/subaccounts/types/subaccount.go
- protocol/x/subaccounts/types/subaccount.pb.go
- protocol/x/subaccounts/types/subaccount_test.go
Increase upper limit of subaccount number to 128,000 to allow for isolated margin subaccounts
Unit tests
> [TRA-98] Update upper limit of subaccount number constraint

- protocol/x/subaccounts/keeper/subaccount.go
> Make funding payment event ordering deterministic

- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/perpetuals/types/liquidity_tier.go
- protocol/x/perpetuals/types/liquidity_tier_test.go
Modify `GetInitialMarginQuoteQuantums` to reflect OIMF. Note that this PR doesn't introduce behavior change due to `zero` being passed in as open interest
Unit tests
> [OTE-162] Modify `GetInitialMarginQuoteQuantums` to reflect OIMF

- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/perpetuals/types/errors.go
Calculate current OI and pass to GetMarginRequirements calculation 
Unit tests
> [OTE-214] Calculate current OI and pass to `GetMarginRequirements` calculation

- indexer/packages/postgres/__tests__/lib/api-translations.test.ts
- indexer/packages/postgres/src/constants.ts
- indexer/packages/postgres/src/lib/api-translations.ts
Add utils to provide conversions between parent (user-level) subaccount numbers and child (protocol-level) subaccount numbers
Unit tests
> [TRA-112] Add util to convert between parent and child subaccount numbers

- indexer/services/ender/__tests__/lib/on-message.test.ts
- indexer/services/ender/src/caches/block-cache.ts
rename block_already_parsed metric since it's now expected
see https://github.com/dydxprotocol/v4-infrastructure/pull/81 for context
unit tested
> rename block_already_parsed metric since it's now expected

- indexer/services/comlink/src/controllers/api/v4/historical-block-trading-rewards-controller.ts
- indexer/services/comlink/src/controllers/api/v4/historical-trading-reward-aggregations-controller.ts
- indexer/services/comlink/src/request-helpers/export-response-code-stats.ts
Fix stats prefix for trading rewards API
for dashboarding
> Fix stats prefix for trading rewards API

- protocol/testutil/constants/vault.go
- protocol/x/vault/keeper/shares.go
- protocol/x/vault/keeper/shares_test.go
- protocol/x/vault/types/errors.go
- protocol/x/vault/types/keys.go
- protocol/x/vault/types/keys_test.go
- protocol/x/vault/types/vault_id.go
- protocol/x/vault/types/vault_id_test.go
Add `TotalShares` store (and getter and setter methods)
added unit tests in this PR
> [TRA-116] add x/vault total shares store

- protocol/mocks/ClobKeeper.go
- protocol/x/clob/keeper/msg_server_place_order.go
- protocol/x/clob/types/clob_keeper.go
move place stateful order logic from msg server to keeper
existing tests are sufficient
> [TRA-121] move place stateful order logic from msg server to keeper

- indexer/services/roundtable/src/tasks/aggregate-trading-rewards.ts
Use read replica rather than main instance for aggregate-trading-rewards query.
Over the past week, this is the 2nd top query by db wait time on the primary db instance.
> Use read replica rather than main instance for aggregate-trading-rewards query

- indexer/services/comlink/__tests__/controllers/api/v4/fills-controller.test.ts
- indexer/services/comlink/public/api-documentation.md
- indexer/services/comlink/public/swagger.json
- indexer/services/comlink/src/controllers/api/v4/fills-controller.ts
- indexer/services/comlink/src/request-helpers/request-transformer.ts
- indexer/services/comlink/src/types.ts
Add subAccountNumber as a field on FillResponseObject
Existing unit tests
> [TRA-103] Add subaccountNumber field in fills response result

- indexer/services/ender/__tests__/lib/on-message.test.ts
- indexer/services/ender/src/lib/on-message.ts
Do not emit stat if we are skipping block
unit tested
> Do not emit stat if we are skipping block

- protocol/lib/big_math.go
- protocol/lib/big_math_test.go
- protocol/x/vault/keeper/orders.go
- protocol/x/vault/keeper/orders_test.go
- protocol/x/vault/types/errors.go
- protocol/x/vault/types/expected_keepers.go
construct simple vault orders
unit tests
> [TRA-134] construct simple vault orders

- protocol/testutil/constants/subaccounts.go
- protocol/x/sending/e2e/isolated_subaccount_transfers_test.go
Add E2E test for transfers from / to isolated subaccounts.
Additional changes:
- cleaned up some tech debt I found where subaccounts with no perpetual positions should have `nil` and not an empty slice for test constants
- cleaned up some tech debt I found where perpetual positions should be initialized with a 0 funding index rather than the default value for the byte array for test constants
Ran test.
> [TRA-126] Add E2E test for isolated subaccount transfers.

- protocol/app/upgrades/v5.0.0/upgrade.go
```
8:18PM INF Combining the short term order placement and cancellation limits of previous config: {MaxShortTermOrdersPerNBlocks:[{NumBlocks:1 Limit:200}] MaxStatefulOrdersPerNBlocks:[{NumBlocks:1 Limit:2} {NumBlocks:100 Limit:20}] MaxShortTermOrderCancellationsPerNBlocks:[{NumBlocks:1 Limit:200}] MaxShortTermOrdersAndCancelsPerNBlocks:[]}
module=x/app/upgrades request_id=482b618d61d19ca567a7
8:18PM INF Attempting to set rate limiting config to newly combined config: {MaxShortTermOrdersPerNBlocks:[] MaxStatefulOrdersPerNBlocks:[{NumBlocks:1 Limit:2} {NumBlocks:100 Limit:20}] MaxShortTermOrderCancellationsPerNBlocks:[] MaxShortTermOrdersAndCancelsPerNBlocks:[{NumBlocks:5 Limit:2000}]}
```
> Fix upgrade rate limit config logic, add helpful logs

- protocol/Makefile
- protocol/go.mod
- protocol/go.sum
Previously we had to revert libsecp256k1 because of duplicate symbol issue. Using it from go-ethereum directly solves this issue.
Existing tests
> Upgrade cosmos fork to use libsecp256k1 from go-ethereum

- indexer/packages/kafka/__tests__/batch-kafka-producer.test.ts
- indexer/packages/kafka/src/batch-kafka-producer.ts
- indexer/services/bazooka/src/vulcan-helpers.ts
- indexer/services/ender/__tests__/handlers/stateful-order/conditional-order-triggered-handler.test.ts
- indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-placement-handler.test.ts
- indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-removal-handler.test.ts
- indexer/services/ender/__tests__/helpers/indexer-proto-helpers.ts
- indexer/services/ender/__tests__/lib/block-processor.test.ts
- indexer/services/ender/src/handlers/handler.ts
- indexer/services/ender/src/handlers/stateful-order/conditional-order-triggered-handler.ts
- indexer/services/ender/src/handlers/stateful-order/stateful-order-placement-handler.ts
- indexer/services/ender/src/handlers/stateful-order/stateful-order-removal-handler.ts
- indexer/services/ender/src/lib/block-processor.ts
- indexer/services/ender/src/lib/kafka-publisher.ts
- indexer/services/ender/src/lib/on-message.ts
- indexer/services/ender/src/lib/types.ts
- indexer/services/ender/src/validators/asset-validator.ts
- indexer/services/ender/src/validators/deleveraging-validator.ts
- indexer/services/ender/src/validators/funding-validator.ts
- indexer/services/ender/src/validators/liquidity-tier-validator.ts
- indexer/services/ender/src/validators/market-validator.ts
- indexer/services/ender/src/validators/order-fill-validator.ts
- indexer/services/ender/src/validators/perpetual-market-validator.ts
- indexer/services/ender/src/validators/stateful-order-validator.ts
- indexer/services/ender/src/validators/subaccount-update-validator.ts
- indexer/services/ender/src/validators/trading-rewards-validator.ts
- indexer/services/ender/src/validators/transfer-validator.ts
- indexer/services/ender/src/validators/update-clob-pair-validator.ts
- indexer/services/ender/src/validators/update-perpetual-validator.ts
- indexer/services/ender/src/validators/validator.ts
pass initial kafka timestamp from Ender -> Vulcan for better e2e order latency tracking
unit tested.
> pass initial kafka timestamp from Ender -> Vulcan for better e2e order latency tracking

- protocol/app/app.go
- protocol/mocks/ClobKeeper.go
- protocol/mocks/MemClob.go
- protocol/mocks/MemClobKeeper.go
- protocol/streaming/grpc/grpc_streaming_manager.go
- protocol/testutil/memclob/keeper.go
- protocol/x/clob/abci.go
- protocol/x/clob/keeper/keeper.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/memclob/memclob.go
- protocol/x/clob/memclob/memclob_grpc_streaming.go
- protocol/x/clob/memclob/memclob_grpc_streaming_test.go
- protocol/x/clob/memclob/memclob_purge_invalid_memclob_state_test.go
- protocol/x/clob/memclob/memclob_remove_order_test.go
- protocol/x/clob/types/clob_keeper.go
- protocol/x/clob/types/mem_clob_keeper.go
- protocol/x/clob/types/memclob.go
> [CT-700] separate indexer and grpc streaming events

- protocol/streaming/grpc/grpc_streaming_manager.go
> [CT-700] only send response when there is at least one update

- indexer/packages/kafka/package.json
- indexer/packages/kafka/src/index.ts
- indexer/packages/kafka/src/websocket-helper.ts
- indexer/pnpm-lock.yaml
- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/src/handlers/helpers.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
- indexer/services/vulcan/src/handlers/order-remove-handler.ts
Refactor helper methods for sending subaccount websocket message into kafka package for re-use in Ender
Existing tests
> [CT-709] Refactor helper methods into kafka package for re-use in Ender

- protocol/lib/metrics/constants.go
- protocol/x/vault/abci_test.go
- protocol/x/vault/keeper/orders.go
- protocol/x/vault/keeper/orders_test.go
- protocol/x/vault/keeper/shares.go
- protocol/x/vault/types/vault_id.go
- protocol/x/vault/types/vault_id_test.go
refresh all vault orders
added unit tests
> [TRA-152] refresh all vault orders

- protocol/testutil/constants/positions.go
- protocol/x/subaccounts/keeper/isolated_subaccount.go
- protocol/x/subaccounts/keeper/isolated_subaccount_test.go
- protocol/x/subaccounts/keeper/subaccount.go
- protocol/x/subaccounts/keeper/subaccount_helper.go
- protocol/x/subaccounts/keeper/subaccount_test.go
- protocol/x/subaccounts/keeper/update.go
- protocol/x/subaccounts/types/isolated_perpetual_position_state_transition.go
- protocol/x/subaccounts/types/isolated_perpetual_position_state_transition_test.go
Update `UpdateSubaccounts` to transfer collateral between collateral pools when a subaccount opens/closes an isolated perpetual position.
Adds multiple helper functions to calculate / track the collateral transfers.
Note: This changes the assumption that `UpdateSubaccounts` only changes state in the `x/subaccount` module as it will now change state in the `x/bank` module as well.
Unit tests. E2E tests are planned under this [ticket](https://linear.app/dydx/issue/TRA-99/add-integration-e2e-tests-for-placing-orders-in-isolated-markets-cross).
> [TRA-139] Add logic to transfer collateral when open/close isolated perpetual position.

- protocol/app/app.go
- protocol/x/prices/keeper/currency_pair_id_cache.go
- protocol/x/prices/keeper/keeper.go
- protocol/x/prices/keeper/market.go
- protocol/x/prices/keeper/market_param.go
- protocol/x/prices/keeper/market_param_test.go
- protocol/x/prices/keeper/slinky_adapter.go
- Introduces a `CurrencyPairIDCache` to the `PricesKeeper`
- Reads from the `slinky_adapter` hit the cache first
- Caching semantics
- Stores an in-memory cache between `currency-pair-id -> currency-pair`
- `ticker -> ID`
- The cache is updated dynamically, as new currency-pairs are queried + placed in vote-extensions
- unit-tests, tested via petri
> perf: optimize `slinky_adapter` via in-memory cache [SKI-13]

- protocol/x/subaccounts/keeper/oimf.go
- protocol/x/subaccounts/keeper/oimf_test.go
- protocol/x/subaccounts/keeper/subaccount.go
Simply `GetDeltaOpenInterestFromUpdates` interface as well as upstream usage
unit tests
> OIMF: Simplify interface for `GetDeltaOpenInterestFromUpdates`

- indexer/packages/kafka/src/websocket-helper.ts
- indexer/packages/redis/src/helpers/order-helper.ts
- indexer/packages/redis/src/index.ts
- indexer/services/ender/__tests__/handlers/stateful-order/stateful-order-placement-handler.test.ts
- indexer/services/ender/__tests__/helpers/indexer-proto-helpers.ts
- indexer/services/ender/src/config.ts
- indexer/services/ender/src/handlers/stateful-order/stateful-order-placement-handler.ts
- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/src/handlers/helpers.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
Add flag to send subaccount websocket message from Ender for long term orders
Unit tested.
> [CT-709] Add flag to send subaccount websocket message from Ender for long term orders

- protocol/app/upgrades/v5.0.0/upgrade.go
- protocol/mocks/PerpetualsKeeper.go
- protocol/scripts/genesis/sample_pregenesis.json
- protocol/testing/genesis.sh
- protocol/x/perpetuals/types/types.go
Initialize lower and upper caps in upgrade handler
[TODO](https://linear.app/dydx/issue/OTE-249/add-upgrade-handler-test-for-liquidity-tier-being-correctly-updated)
> [OTE-244] Add upgrade handler for OIMF

- protocol/Makefile
- protocol/app/upgrades/v5.0.0/upgrade_container_test.go
- protocol/testing/containertest/testnet_test.go
- protocol/testing/containertest/testnet_utils.go
Adds an upgrade test which checks state validity for perpetual market type
Refactors testnet upgrade code so that it can be used across tests
> [OTE-218] Add state validity test for perpetual market type

- protocol/testutil/constants/perpetuals.go
- protocol/testutil/perpetuals/perpetuals.go
- protocol/x/clob/keeper/deleveraging_test.go
- protocol/x/clob/keeper/liquidations_test.go
- protocol/x/clob/keeper/orders_test.go
- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/perpetuals/types/types.go
- protocol/x/subaccounts/keeper/oimf.go
- protocol/x/subaccounts/keeper/oimf_test.go
- protocol/x/subaccounts/keeper/subaccount.go
- protocol/x/subaccounts/keeper/subaccount_test.go
- protocol/x/subaccounts/types/errors.go
In `UpdateSubaccounts`, update OI for a perpetual. 
Added new/modified current unit tests
> [OTE-245] Update OI after fill and added unit tests

- protocol/x/clob/abci.go
> [CT-712] send fill amount updates for reverted operations in prepare check state

- protocol/x/vault/keeper/orders.go
- protocol/x/vault/types/vault_id.go
- protocol/x/vault/types/vault_id_test.go
Don't use serialization to generate state keys of vault IDs.
unit tests
> [TRA-172] change vault state key to not use serialization

- protocol/docker-compose.yml
- protocol/testing/testnet-local/local.sh
Fix localnet run by using the slinky docker image.  
I ended up having to disable the test volatile network because slinky doesn't know about this network and grabbing markets will fail on it. We can have a follow up issue tracking adding this in the sidecar and re-enabling here.
make localnet-start
> [SKI-18] Fix localnet

- protocol/x/perpetuals/simulation/genesis.go
Updated randomization of perpetuals genesis for simulation to include generating isolated perpetuals.
Ran non-determinism test multiple times locally.
> Enable isolated perpetuals in sim tests.

- protocol/x/clob/keeper/order_state.go
> [CT-727] avoid state reads when sending updates

- protocol/x/clob/keeper/order_state.go
- protocol/x/clob/keeper/order_state_test.go
- Bug: Wriiting to incorrect height
- Bug: Didn't delete old keys
- Fixed unit test
> Fix bugs in pruneable order migration

- indexer/services/socks/src/config.ts
Enable rate limiting in socks by default
> Enable rate limiting in socks by default

- indexer/packages/postgres/__tests__/helpers/constants.ts
- indexer/packages/postgres/src/db/migrations/migration_files/20240327144524_add_perpetual_markets_market_type.ts
- indexer/packages/postgres/src/models/perpetual-market-model.ts
- indexer/packages/postgres/src/types/db-model-types.ts
- indexer/packages/postgres/src/types/perpetual-market-types.ts
- indexer/packages/postgres/src/types/websocket-message-types.ts
- indexer/services/comlink/__tests__/lib/request-helpers/request-transformer.test.ts
- indexer/services/comlink/public/api-documentation.md
- indexer/services/comlink/public/swagger.json
- indexer/services/comlink/src/request-helpers/request-transformer.ts
- indexer/services/comlink/src/types.ts
- indexer/services/ender/__tests__/helpers/indexer-proto-helpers.ts
- indexer/services/ender/__tests__/helpers/postgres-helpers.ts
- indexer/services/ender/__tests__/validators/asset-validator.test.ts
- indexer/services/ender/src/helpers/postgres/postgres-functions.ts
- indexer/services/ender/src/scripts/handlers/dydx_perpetual_market_handler.sql
- indexer/services/ender/src/scripts/helpers/dydx_protocol_market_type_to_perpetual_market_type.sql
Updates to postgres, ender and comlink to add market type for perpetuals
> [TRA-108] Update indexer to ingest and return market type for perpetuals

- protocol/x/vault/client/cli/query.go
- protocol/x/vault/client/cli/tx.go
- protocol/x/vault/client/cli/util.go
add cli for deposit to vault
local testing
> [TRA-188] add cli for deposit to vault

- indexer/services/comlink/__tests__/controllers/api/v4/addresses-controller.test.ts
- indexer/services/comlink/__tests__/controllers/api/v4/perpetual-positions-controller.test.ts
- indexer/services/comlink/public/api-documentation.md
- indexer/services/comlink/public/swagger.json
- indexer/services/comlink/src/controllers/api/v4/addresses-controller.ts
- indexer/services/comlink/src/controllers/api/v4/perpetual-positions-controller.ts
- indexer/services/comlink/src/request-helpers/request-transformer.ts
- indexer/services/comlink/src/types.ts
Add subaccountNumber field to PerpetualPositionResponseObject
Existing unit tests
> [TRA-105] Add subaccountNumber to PerpetualPositionResponseObject

- protocol/testing/testnet-dev/dev.sh
- protocol/testing/testnet-staging/staging.sh
Removes volatile market from dev/staging/local testnets. Will be re-enabled at a later time when Slinky supports it.
> Remove volatile market

- indexer/services/socks/src/helpers/wss.ts
Logging is causing memory spikes. See discussion [here](https://dydx-team.slack.com/archives/C06PXDP9K2A/p1711635099485299) for details.
N/A
> Clean up socks logging

- indexer/services/socks/src/helpers/wss.ts
Use sample rate with stats for messages sent to a destroyed stream to reduce # of stats sent.
N/A
> Use sample rate with stream destroyed stats.

- protocol/x/vault/keeper/orders.go
remove unused placeholder constants (now defined in state) 
N/A
> remove vault constants

- protocol/x/vault/keeper/orders.go
> remove vault constants (#1293)

- indexer/services/socks/src/websocket/index.ts
> Sample more stats in socks

- protocol/app/upgrades/v5.0.0/upgrade.go
- protocol/app/upgrades/v5.0.0/upgrade_container_test.go
- protocol/testing/containertest/preupgrade_genesis.json
- Upgrade handler logic to aggregate OI for each perp market and initialize it. 
- Requires backporting 
-
Container test
> [OTE-256] Add upgrade handler to initialize OI during upgrade handler

- protocol/cmd/dydxprotocold/cmd/config.go
Increase this by a bit since it's the current bottleneck.
N/A
> Increase the number of allowed connections to 8000

- indexer/services/ender/__tests__/handlers/funding-handler.test.ts
- indexer/services/ender/src/scripts/handlers/dydx_funding_handler.sql
Ignore funding if no oracle prices
Unit tests
> [SKI-26]: Prevent funding index update with no oracle prices from halting indexer

- protocol/x/clob/e2e/equity_tier_limit_test.go
- protocol/x/clob/keeper/equity_tier_limit.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/keeper/orders_test.go
These checks are not effective for their original purpose and take 30% of the CheckTx global lock time in testnet loads.
> Skip equity tier limit check in PlaceShortTermOrder

- protocol/testing/testnet-dev/dev.sh
- protocol/testing/testnet-local/local.sh
- protocol/testing/testnet-staging/staging.sh
- Delete unused flags
- Enable oracle prometheus metrics
Deployed to dev2
> [SKI-27]: Open prometheus port for Oracle to be exposed

- protocol/app/ante.go
- protocol/x/clob/ante/clob.go
Especially due to message serialization, this is more expensive than it should be. If msg is necessary, it can be serialized in individual logs.
N/A
> Remove unnecessary message serialization in clob AnteHandle

- protocol/go.mod
- protocol/go.sum
- protocol/lib/int256/int256.go
- protocol/lib/int256/int256_test.go
- Add uint256 package
- Add int256 signed wrapper with some methods implemented
- Added tests
> Add uint256 package and int256 wrapper

- indexer/packages/v4-protos/src/index.ts
- indexer/packages/v4-protos/src/utils.ts
- indexer/services/ender/__tests__/helpers/indexer-proto-helpers.ts
- indexer/services/ender/src/lib/helper.ts
- indexer/services/socks/src/lib/message-forwarder.ts
- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/__tests__/handlers/order-remove-handler.test.ts
- indexer/services/vulcan/__tests__/helpers/constants.ts
- indexer/services/vulcan/__tests__/helpers/helpers.ts
- indexer/services/vulcan/__tests__/helpers/websocket-helpers.ts
- indexer/services/vulcan/__tests__/lib/on-message.test.ts
- indexer/services/vulcan/src/handlers/handler.ts
- indexer/services/vulcan/src/handlers/order-place-handler.ts
- indexer/services/vulcan/src/handlers/order-remove-handler.ts
- indexer/services/vulcan/src/handlers/order-update-handler.ts
- indexer/services/vulcan/src/lib/on-message.ts
First PR failing because kafka doesn't like undefined values for kafka message headers. Pass through the headers verbatim.
> Indexer e2e latency round 2

- protocol/app/app.go
- protocol/testutil/keeper/vault.go
- protocol/x/vault/keeper/keeper.go
- protocol/x/vault/keeper/msg_server_deposit_to_vault.go
- protocol/x/vault/types/expected_keepers.go
use `ProcessTransfer` instead of `TransferFundsFromSubaccountToSubaccount` to emit a transfer indexer event on vault deposit. PnL roundtable task picks up transfer indexer events to show portfolio chart on the front-end
existing unit tests / integ tests
> [TRA-219] emit transfer indexer event on vault deposit

- protocol/docker-compose.yml
- protocol/testing/testnet-dev/dev.sh
- protocol/testing/testnet-local/local.sh
- protocol/testing/testnet-staging/staging.sh
Bumps slinky sidecar to use `v0.3.2` docker image which allows us to re-enable the volatile market.
Will need to be updated in dev deployments. I don't have access to that.
Ran localnet and got prices for TEST/USD.
> Bump slinky sidecar, re-enabled volatile market

- protocol/x/vault/keeper/orders.go
- protocol/x/vault/keeper/orders_test.go
- I bound the vault quotes by the oracle price (ask is max of what we compute and the oracle price, bid is the min). This is to make the strategy more oracle resistant. More details [here](https://www.notion.so/dydx/Proposal-to-bound-quotes-to-oracle-price-71493528753146209afb884d33d3413a).
- updated the test case to reflect the new desired behavior of the vaults
- I ran the test cases in vault/keeper/orders_test.go
> bounded quotes by oracle price

- protocol/app/flags/flags.go
- protocol/app/flags/flags_test.go
> decouple grpc and non validating full node flags

- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/perpetuals/keeper/perpetual_test.go
- protocol/x/subaccounts/keeper/negative_tnc_subaccount.go
Currently, IsIsolatedPerpetual returns True for cross perpetuals and its callers expect the same, which is the wrong orientation for the function. This change fixes this behavior
Existing tests
> [TRA-233] Fix IsIsolatedPerpetual function orientation

- indexer/services/roundtable/src/helpers/pnl-ticks-helper.ts
The `logger.error` is not functioning and still giving a null error. I assume this is because of some incorrect dereferencing for the fields in the logger object. remove them so that we don't error out within the `catch`
> remove logging referenced objects

- protocol/testutil/app/app.go
- so that we can modify state before `InitChain` is called
> move e2e test app instantiation to Build

- protocol/x/perpetuals/client/cli/query.go
- protocol/x/perpetuals/client/cli/query_all_liquidity_tiers.go
- protocol/x/perpetuals/client/cli/query_all_liquidity_tiers_test.go
- protocol/x/perpetuals/module_test.go
> Add `QueryAllLiquidityTiers` to CLI

- protocol/contrib/prometheus/prometheus.yml
- protocol/docker-compose.yml
- I introduce a prometheus data-base to the local-network in dydx
- I export metrics from the slinky-sidecar in the network + export metrics to the prometheus DB
- I change the sidecar version used in the local network to 0.4.1
- This [PR](https://github.com/dydxprotocol/v4-web/pull/489) to validate changes to the research-json against a slinky instance, depends on this PR
> feat: add a prometheus instance to the dydx local network

- protocol/app/upgrades/v5.0.0/upgrade.go
Add protections around nil VE ABCI Params
Send to a single validator first on testnet.
> fix: Fix v5 upgrade VE handler

- protocol/go.mod
- protocol/go.sum
WorkingHash was computed incorrectly for trees that are initialized with an InitialVersion. This happens when a new store is introduced in an upgrade. If the store is empty, the hash ends up being the same anyways so the bug only manifests when the store has values at the upgrade height.
See https://github.com/dydxprotocol/iavl/commit/1c8b8e787e85f78c5dfcdfb83339bd1e0b36939f.
> Update iavl with WorkingHash fix

- protocol/daemons/pricefeed/client/client_integration_test.go
- protocol/daemons/server/types/pricefeed/exchange_to_price.go
- protocol/daemons/server/types/pricefeed/exchange_to_price_test.go
- protocol/daemons/server/types/pricefeed/market_to_exchange_prices.go
- protocol/daemons/server/types/pricefeed/market_to_exchange_prices_test.go
- protocol/lib/metrics/constants.go
- protocol/x/prices/keeper/market_price.go
- protocol/x/prices/keeper/update_price.go
- protocol/x/prices/keeper/validate_market_price_updates.go
1. convert unnecessary metrics into logs
2. only emit metrics on invalid cases
Unit testing should be sufficient given that the changes are metrics only
> [TRA-241] Pricefeed Server: remove unnecessary metrics & only report invalid cases

- protocol/lib/big_math.go
- protocol/lib/big_math_test.go
- protocol/lib/quantums.go
- protocol/lib/quantums_test.go
- These are two of the most used function by the CPU at the moment.
- `BaseToQuoteQuantums` optimized by about 80% and `BigRatMulPpm` optimized by about 20%
- In a future PR, `multiplyByPrice` and `FundingRateToIndex` can be removed like in https://github.com/dydxprotocol/v4-chain/pull/1528, but am keeping this PR small for now to ensure it can be backported if needed
- New benchmark test for `BaseToQuoteQuantums`
- Unit tests already exist for `BaseToQuoteQuantums` including rounding for negative numbers
Before:
```
BenchmarkBigRatMulPpm-4          	16975401	       382.0 ns/op	     208 B/op	       9 allocs/op
BenchmarkBaseToQuoteQuantums-4   	 3997749	      1518 ns/op	    1056 B/op	      36 allocs/op
```
After:
```
BenchmarkBigRatMulPpm-4          	22503729	       289.2 ns/op	     192 …
```
> Improve the performance of `BaseToQuoteQuantums` & `BigRatMulPpm`

- protocol/lib/big_math.go
- protocol/lib/big_math_test.go
These changes are needed for future PRs that clean the repo of `big.Rat`
- Add functions to `big.Int`-ify any int/uint type
- Add function to multiply a `big.Int` by a `big.Int` ppm value (i.e. divide by `1_000_000` afterwards) and round up or down
- Add function to divide `big.Int` values and return the ceiling (whereas `Div` takes the floor, and `Quo` rounds towards zero
- Added unit tests and benchmarks for the introduced functions
> Add additional `big_math` helper functions

- protocol/lib/collections.go
- protocol/lib/collections_test.go
`ContainsDuplicates` accounts for over 10% of the time when placing vault orders on testnet. Optimize the runtime by around 50%, especially in the almost-always case of no duplicates. Therefore this should speed up placement of vault orders by around 5%.
- Added benchmarks
```
Before
BenchmarkContainsDuplicates_True-4    	12939104	       459.6 ns/op	     114 B/op	       1 allocs/op
BenchmarkContainsDuplicates_False-4   	 5010406	      1185 ns/op	     385 B/op	       3 allocs/op
After
BenchmarkContainsDuplicates_True-4    	21472302	       271.8 ns/op	     192 B/op	       1 allocs/op
BenchmarkContainsDuplicates_False-4   	11044560	       534.5 ns/op	     208 B/op	       1 allocs/op
```
> Add benchmark and optimize `ContainsDuplicates`

- protocol/x/clob/types/quantums.go
- protocol/x/clob/types/quantums_test.go
- protocol/x/perpetuals/keeper/perpetual.go
- protocol/x/rewards/keeper/keeper.go
- protocol/x/vault/keeper/orders.go
- protocol/x/vault/types/errors.go
- Remove `NotionalToCoinAmount()` in favor of using `QuoteToBaseQuantums()` since it seems to be duplicated logic
- `QuoteToBaseQuantums()` is also used in order-sizing for vaults since vaults was previously duplicating the logic
- TODO
> reduce use of `big.Rat` in various modules

- protocol/x/subaccounts/keeper/isolated_subaccount.go
- protocol/x/subaccounts/keeper/subaccount.go
Traced some CPU/runtime timing to the creation and updating of maps. Add hinting to map allocation when it's clear how many items will go in the map. Reduces amount of memory allocation and copying.
Hinting doesn't need to be tested directly.
> Add hints to maps

- protocol/lib/big_math.go
- protocol/x/clob/keeper/mev.go
- protocol/x/clob/keeper/process_single_match.go
- protocol/x/clob/types/pending_updates.go
- protocol/x/rewards/keeper/keeper.go
Remove deprecated function
Existing unit tests
> Remove use of `BigIntMulSignedPpm` in favor of `BigMulPpm`

- protocol/go.mod
- protocol/go.sum
Updating to this cosmos commit: https://github.com/dydxprotocol/cosmos-sdk/commit/18966898625ff8f6efe1cecd381123494715bdad
> Upgrade cosmos sdk to allow tx decoding to fail in QueryTxsByEvents

- protocol/app/app.go
Since Cosmos v0.50, the upgrade handler is moved to `Preblocker`. We need to move  `scheduleForkUpgrade` accordingly to ` Preblocker` so that the fork can be scheduled prior to the upgrade handler logic.  
Tested locally with https://github.com/dydxprotocol/v4-chain/pull/1628
> fix: Schedule fork upgrade during Preblocker

- protocol/streaming/grpc/grpc_streaming_manager.go
We were iterating over the orderbook subscriptions without the lock.
> GRPC streaming move lock above send orderbook updates

- protocol/lib/big_math_test.go
- protocol/lib/constants.go
- protocol/lib/convert.go
- protocol/x/clob/simulation/place_order.go
- protocol/x/rewards/keeper/keeper.go
- protocol/x/subaccounts/lib/updates.go
Removes superfluous functions that were only used to do `Cmp(0)` which can be substituted to use `Sign()` or `BitLen()` instead
> chore: remove `BigInt0()` & `BigFloat0()`

- indexer/services/vulcan/__tests__/handlers/order-place-handler.test.ts
- indexer/services/vulcan/__tests__/handlers/order-remove-handler.test.ts
- indexer/services/vulcan/__tests__/handlers/order-replace-handler.test.ts
- indexer/services/vulcan/__tests__/helpers/websocket-helpers.ts
- indexer/services/vulcan/src/handlers/order-replace-handler.ts
Send a subaccount websocket message on order replace for the cancelled order so that the FE displays the correct information
> Send order remove subaccount message on order replace

- protocol/x/clob/keeper/clob_pair_test.go
Adds a simple test to get perpetual clob details
> [OTE-415] Add test for getting perpetual clob details

- protocol/x/subaccounts/keeper/safety_heap_state.go
- protocol/x/subaccounts/keeper/safety_heap_state_test.go
- protocol/x/subaccounts/keeper/safety_heap_stores.go
- protocol/x/subaccounts/types/errors.go
- protocol/x/subaccounts/types/keys.go
- protocol/x/subaccounts/types/subaccount.go
The safety heap will be represented using an array in state. We don't want to serialize/deserialize the entire heap every time we read/write from state (i.e. putting the entire heap under the same key). Instead, we will use their heap indices as keys and store them under the same prefix.
Essentially we need three things in state
- SH/<perpetual_id>/\<side>/Heap/\<index> --> SubaccountId
- SH/<perpetual_id>/\<side>/Idx/\<subaccount_id> -> heap index (uint32)
- SH/<perpetual_id>/\<side>/Len/  -> length of the heap
> [CT-941] introduce state methods for managing the safety heap

- protocol/lib/metrics/constants.go
- protocol/x/clob/keeper/grpc_query_mev_node_to_node.go
- protocol/x/clob/keeper/liquidations.go
- protocol/x/clob/keeper/mev.go
- protocol/x/clob/keeper/orders.go
- protocol/x/clob/keeper/process_single_match.go
- Remove extra getFillQuoteQuantums() function which just wraps FillAmountToQuoteQuantums() and throws errors in certain cases unnecessarily
- This allows removal of `error` return value from some upstream functions
> Remove `getFillQuoteQuantums()` function

- protocol/contracts/dydx-messages-example/src/contract.rs
- protocol/contracts/dydx-messages-example/src/msg.rs
- protocol/dydx-cosmwasm/src/lib.rs
- protocol/dydx-cosmwasm/src/msg.rs
- protocol/wasmbinding/bindings/msg.go
- protocol/wasmbinding/msg_plugin.go
- protocol/wasmbinding/wasm.go
- Updates wasm keeper to use custom encoder
- Updates message schemas for rust and golang
- Adds rust tests for schemas
- GetSigners is called by the default message handler, we dont need to add this ourselves
Added rust unit tests
> [OTE-407][OTE-409][OTE-426]Update wasm bindings to use custom encoder

- protocol/docker-compose.yml
Allow passing in RAYDIUM_URL as a env var to localnet's slinky
Tested this by spinning up localnet and ran https://github.com/dydxprotocol/v4-web/blob/ce9180e1d8d48c4739782c60a0aafaddc09bdc10/scripts/validate-other-market-data.ts against it with RAYDIUM_URL set, which successfully queried prices for raydium markets.
> add raydium url to localnet slinky

- protocol/x/clob/ante/clob.go
Add additional logging when rejecting ST orders to have better visibility as to who is sending the order and the difference between `TimeoutHeight` and `GoodTilBlock`.
N/A
> Log order id and good til block of rejected st orders.

- protocol/lib/metrics/metric_keys.go
- protocol/x/blocktime/keeper/keeper.go
Emit block time as sample so we could graph by quantile (e.g. p50 for median)
Tested on branch `td/v5.x-oe` running on `dev3`. Example [graph](https://app.datadoghq.com/dashboard/25s-bg4-rfr?fromUser=false&fullscreen_end_ts=1721143077000&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_section=overview&fullscreen_start_ts=1721142616752&fullscreen_widget=3656051188985576&refresh_mode=paused&tile_focus=7899691207155956&tpl_var_env%5B0%5D=dev3&view=spans&from_ts=1721142616752&to_ts=1721143077000&live=false)
> perf: Emit blocktime as sample 

- protocol/app/app.go
There was a typo in the previous PR #1910 that incorrectly changed the ordering in `BeginBlocker` and `EndBlocker`.
Checked against rc2.
> Fix ordering of begin/end blocker to match rc2.

- protocol/app/app.go
- protocol/app/flags/flags.go
- protocol/app/flags/flags_test.go
Add flag to enable optimistic block execution. Default is false this this is no-op.
> [CT-850] feat(OE): add flag to enable optimistic block execution

- protocol/app/flags/flags.go
- protocol/app/flags/flags_test.go
- protocol/docker-compose.yml
Localnet build uses 9091 for prometheus (PR #1452 )
> Full Node Streaming default port 9092

- protocol/testing/current_version.sh
- protocol/testing/mainnet/Dockerfile
- protocol/testing/mainnet/mainnet.sh
- protocol/testing/mainnet/vars.sh
- protocol/testing/testnet/Dockerfile
- protocol/testing/testnet/testnet.sh
- protocol/testing/testnet/vars.sh
Remove genesis binary and unify version file
> Simplify container builds

- protocol/app/upgrades.go
- protocol/app/upgrades/v6.0.0_testnet_fix/constants.go
- protocol/app/upgrades/v6.0.0_testnet_fix/upgrade.go
No-op upgrade to be used for a testnet upgrade. Not intended for prod use.
> Add no-op v6.0.0_testnet_fix upgrade for testnet

- protocol/x/vault/keeper/orders.go
- protocol/x/vault/keeper/orders_test.go
This reverts commit 25dbec5bae7b59426b499c2b2d3769d90f1cb608.
> Revert "Sp/vault post only orders (#2198)"

- indexer/packages/kafka/__tests__/consumer.test.ts
- indexer/packages/kafka/src/consumer.ts
- indexer/services/ender/src/helpers/kafka/kafka-controller.ts
- indexer/services/scripts/src/print-block.ts
- indexer/services/socks/src/helpers/kafka/kafka-controller.ts
- indexer/services/vulcan/src/helpers/kafka/kafka-controller.ts
> Create consumer using rack id

- indexer/services/ender/__tests__/handlers/order-fills/liquidation-handler.test.ts
- indexer/services/ender/__tests__/handlers/order-fills/order-handler.test.ts
- indexer/services/ender/src/scripts/helpers/dydx_liquidation_fill_handler_per_order.sql
- indexer/services/ender/src/scripts/helpers/dydx_update_perpetual_position_aggregate_fields.sql
Reverts dydxprotocol/v4-chain#2415
> Revert "[CT-629] Fix entryPrice calc"

- indexer/services/ender/__tests__/lib/candles-generator.test.ts
Modifies candles generator test to using a starting time far enough in the past to ensure candles are started before the current candle
Automated tests passing
> Fix issue with flaky candle test

- protocol/scripts/genesis/sample_pregenesis.json
> remove megavault subaccount from sample pregenesis

- protocol/go.mod
- protocol/go.sum
Bump SDK to adopt this [change](https://github.com/dydxprotocol/cosmos-sdk/pull/57). Non-breaking change for OE, completely no-op for nodes not enabling OE. 
Stably running on prod FNS full node
> Bump SDK - Always Reset OE

- indexer/services/roundtable/__tests__/helpers/usernames-helper.test.ts
- indexer/services/roundtable/src/config.ts
- indexer/services/roundtable/src/helpers/usernames-helper.ts
- indexer/services/roundtable/src/tasks/subaccount-username-generator.ts
Expand username space and reduce collision
> Use alphanumeric suffix for username

- indexer/packages/postgres/__tests__/stores/affiliate-info-table.test.ts
- indexer/packages/postgres/src/stores/affiliate-info-table.ts
Currently the affiliates referred fee include liquidation fee, which is an order of magnitude higher than regular maker/taker fees. Including this stats in "referred fees" stats is a bit misleading since this is "taker fee", but goes to insurance fund and is not rev sharable. Therefore we exclude liquidation fees in the stat (while keeping volume/trade count from liquidated fills).
Example from https://indexer.dydx.trade/v4/affiliates/snapshot: `GreenKiteIMX` is a VIP affiliate but its earnings is less than taker fees
Sort affiliates by default when offset != 0 so there's strict ordering
> fix(affiliates): exclude liquidation fees in referred fee calculation

- protocol/go.mod
- protocol/go.sum
Advisory: https://github.com/cosmos/ibc-go/security/advisories/GHSA-jg6f-48ff-5xrw
Official patch: https://github.com/cosmos/ibc-go/compare/v8.5.3...v8.6.1
Patch on forked ibc-go v8.0.0: https://github.com/cosmos/ibc-go/compare/v8.0.0...dydxprotocol:ibc-go:td/v8.0.0-ASA-2025-004?expand=1
> Bump ibc-go from `v8.0.0` to fork

- indexer/packages/postgres/src/types/perpetual-market-types.ts
- indexer/packages/redis/__tests__/caches/next-funding-cache.test.ts
- indexer/packages/redis/src/caches/next-funding-cache.ts
- indexer/services/ender/__tests__/handlers/funding-handler.test.ts
- indexer/services/ender/__tests__/helpers/redis-helpers.ts
- indexer/services/roundtable/__tests__/tasks/market-updater.test.ts
- indexer/services/roundtable/src/tasks/market-updater.ts
Follow-up to https://github.com/dydxprotocol/v4-chain/pull/2674. Now that default funding is stored, add it to `nextFunding` calculation. 
Unit test
> feat(default-funding): Add default funding to `nextFunding` calculation

- indexer/pnpm-lock.yaml
- indexer/services/socks/__tests__/websocket/index.test.ts
- indexer/services/socks/package.json
- indexer/services/socks/src/helpers/wss.ts
- indexer/services/socks/src/lib/message-forwarder.ts
- indexer/services/socks/src/websocket/index.ts
bug: close event handler was removed on ping/pong failure disconnect
this prevented removal of connection from subscription and connection maps
avoid excessive logging during socket disconnection
mitigate misbehaving clients
do not attempt to send remaining batch messages on publishing errors
recommended by ws and automatically enabled
binary polyfills for handling and validating strings
since we only use v4's, we don't need a third-party dep
a node application with these components can utilize 1-2cpu effectively
typical memory provisioned by vendors is 2-8Gib/cpu
based on a 4Gib host:
256 Mib datadog sidecar container reservation
960 Mib application container system reservation
256 Mib semi space to handle object generation rate at load
2624 Mib old heap to utilize minimum expected …
> (bug) don't remove CLOSE event handler on websocket send error

- indexer/services/roundtable/package.json
Roundtable is crashing on OOM during the create-pnl-ticks task.
This change raises the heap limits.
Deploy to internal environments and public testnet.
> (fix) raise roundtable heap limit to 6G

- .gitignore
- indexer/packages/base/src/instance-id.ts
- indexer/services/socks/__tests__/lib/subscriptions.test.ts
- indexer/services/socks/src/config.ts
- indexer/services/socks/src/index.ts
- indexer/services/socks/src/lib/subscription.ts
This PR enhances the **socks** service observability by introducing a new periodic metric that reports the **largest subscriber per channel**.
It helps identify imbalanced load or oversubscription patterns across websocket channels, improving visibility and long-term stability.
- Adds periodic "largest subscriber" metric with a configurable interval for improved observability:
socks.largest_subscriber{channel, instance}
Reports the highest subscription count (number of channel subscriptions) held by any single connection per channel.
- Introduced configuration:
LARGEST_SUBSCRIBER_METRIC_INTERVAL_MS = 60_000  // default 1 minute
- Added `Subscriptions#subsByChannelByConnectionId` to track per-connection subscription counts per channel.
- Implemented `emitLargestSubscriberMetric()`:
- …
> metrics(socks): add largest subscription per channel
